<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetSecuritySnapshot.proto

namespace Futu\Qot_GetSecuritySnapshot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * 正股类型额外数据
 *
 * Generated from protobuf message <code>Qot_GetSecuritySnapshot.EquitySnapshotExData</code>
 */
class EquitySnapshotExData extends \Google\Protobuf\Internal\Message
{
    /**
     * 发行股本,即总股本
     *
     * Generated from protobuf field <code>int64 issuedShares = 1;</code>
     */
    protected $issuedShares = 0;
    /**
     * 总市值 =总股本*当前价格（单位：元）
     *
     * Generated from protobuf field <code>double issuedMarketVal = 2;</code>
     */
    protected $issuedMarketVal = 0.0;
    /**
     * 资产净值
     *
     * Generated from protobuf field <code>double netAsset = 3;</code>
     */
    protected $netAsset = 0.0;
    /**
     * 盈利（亏损）
     *
     * Generated from protobuf field <code>double netProfit = 4;</code>
     */
    protected $netProfit = 0.0;
    /**
     * 每股盈利
     *
     * Generated from protobuf field <code>double earningsPershare = 5;</code>
     */
    protected $earningsPershare = 0.0;
    /**
     * 流通股本
     *
     * Generated from protobuf field <code>int64 outstandingShares = 6;</code>
     */
    protected $outstandingShares = 0;
    /**
     * 流通市值 =流通股本*当前价格（单位：元）
     *
     * Generated from protobuf field <code>double outstandingMarketVal = 7;</code>
     */
    protected $outstandingMarketVal = 0.0;
    /**
     * 每股净资产
     *
     * Generated from protobuf field <code>double netAssetPershare = 8;</code>
     */
    protected $netAssetPershare = 0.0;
    /**
     * 收益率（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double eyRate = 9;</code>
     */
    protected $eyRate = 0.0;
    /**
     * 市盈率
     *
     * Generated from protobuf field <code>double peRate = 10;</code>
     */
    protected $peRate = 0.0;
    /**
     * 市净率
     *
     * Generated from protobuf field <code>double pbRate = 11;</code>
     */
    protected $pbRate = 0.0;
    /**
     * 市盈率TTM
     *
     * Generated from protobuf field <code>double peTTMRate = 12;</code>
     */
    protected $peTTMRate = 0.0;
    /**
     * 股息TTM，派息
     *
     * Generated from protobuf field <code>double dividendTTM = 13;</code>
     */
    protected $dividendTTM = 0.0;
    /**
     * 股息率TTM（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendRatioTTM = 14;</code>
     */
    protected $dividendRatioTTM = 0.0;
    /**
     * 股息LFY，上一年度派息
     *
     * Generated from protobuf field <code>double dividendLFY = 15;</code>
     */
    protected $dividendLFY = 0.0;
    /**
     * 股息率LFY（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendLFYRatio = 16;</code>
     */
    protected $dividendLFYRatio = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $issuedShares
     *           发行股本,即总股本
     *     @type float $issuedMarketVal
     *           总市值 =总股本*当前价格（单位：元）
     *     @type float $netAsset
     *           资产净值
     *     @type float $netProfit
     *           盈利（亏损）
     *     @type float $earningsPershare
     *           每股盈利
     *     @type int|string $outstandingShares
     *           流通股本
     *     @type float $outstandingMarketVal
     *           流通市值 =流通股本*当前价格（单位：元）
     *     @type float $netAssetPershare
     *           每股净资产
     *     @type float $eyRate
     *           收益率（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *     @type float $peRate
     *           市盈率
     *     @type float $pbRate
     *           市净率
     *     @type float $peTTMRate
     *           市盈率TTM
     *     @type float $dividendTTM
     *           股息TTM，派息
     *     @type float $dividendRatioTTM
     *           股息率TTM（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *     @type float $dividendLFY
     *           股息LFY，上一年度派息
     *     @type float $dividendLFYRatio
     *           股息率LFY（该字段为百分比字段，默认不展示%，如20实际对应20%）
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetSecuritySnapshot\pb\QotGetSecuritySnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * 发行股本,即总股本
     *
     * Generated from protobuf field <code>int64 issuedShares = 1;</code>
     * @return int|string
     */
    public function getIssuedShares()
    {
        return $this->issuedShares;
    }

    /**
     * 发行股本,即总股本
     *
     * Generated from protobuf field <code>int64 issuedShares = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIssuedShares(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->issuedShares = $var;

        return $this;
    }

    /**
     * 总市值 =总股本*当前价格（单位：元）
     *
     * Generated from protobuf field <code>double issuedMarketVal = 2;</code>
     * @return float
     */
    public function getIssuedMarketVal()
    {
        return $this->issuedMarketVal;
    }

    /**
     * 总市值 =总股本*当前价格（单位：元）
     *
     * Generated from protobuf field <code>double issuedMarketVal = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setIssuedMarketVal(float $var)
    {
        $this->issuedMarketVal = $var;

        return $this;
    }

    /**
     * 资产净值
     *
     * Generated from protobuf field <code>double netAsset = 3;</code>
     * @return float
     */
    public function getNetAsset()
    {
        return $this->netAsset;
    }

    /**
     * 资产净值
     *
     * Generated from protobuf field <code>double netAsset = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setNetAsset(float $var)
    {
        $this->netAsset = $var;

        return $this;
    }

    /**
     * 盈利（亏损）
     *
     * Generated from protobuf field <code>double netProfit = 4;</code>
     * @return float
     */
    public function getNetProfit()
    {
        return $this->netProfit;
    }

    /**
     * 盈利（亏损）
     *
     * Generated from protobuf field <code>double netProfit = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setNetProfit(float $var)
    {
        $this->netProfit = $var;

        return $this;
    }

    /**
     * 每股盈利
     *
     * Generated from protobuf field <code>double earningsPershare = 5;</code>
     * @return float
     */
    public function getEarningsPershare()
    {
        return $this->earningsPershare;
    }

    /**
     * 每股盈利
     *
     * Generated from protobuf field <code>double earningsPershare = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setEarningsPershare(float $var)
    {
        $this->earningsPershare = $var;

        return $this;
    }

    /**
     * 流通股本
     *
     * Generated from protobuf field <code>int64 outstandingShares = 6;</code>
     * @return int|string
     */
    public function getOutstandingShares()
    {
        return $this->outstandingShares;
    }

    /**
     * 流通股本
     *
     * Generated from protobuf field <code>int64 outstandingShares = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOutstandingShares(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->outstandingShares = $var;

        return $this;
    }

    /**
     * 流通市值 =流通股本*当前价格（单位：元）
     *
     * Generated from protobuf field <code>double outstandingMarketVal = 7;</code>
     * @return float
     */
    public function getOutstandingMarketVal()
    {
        return $this->outstandingMarketVal;
    }

    /**
     * 流通市值 =流通股本*当前价格（单位：元）
     *
     * Generated from protobuf field <code>double outstandingMarketVal = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setOutstandingMarketVal(float $var)
    {
        $this->outstandingMarketVal = $var;

        return $this;
    }

    /**
     * 每股净资产
     *
     * Generated from protobuf field <code>double netAssetPershare = 8;</code>
     * @return float
     */
    public function getNetAssetPershare()
    {
        return $this->netAssetPershare;
    }

    /**
     * 每股净资产
     *
     * Generated from protobuf field <code>double netAssetPershare = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setNetAssetPershare(float $var)
    {
        $this->netAssetPershare = $var;

        return $this;
    }

    /**
     * 收益率（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double eyRate = 9;</code>
     * @return float
     */
    public function getEyRate()
    {
        return $this->eyRate;
    }

    /**
     * 收益率（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double eyRate = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setEyRate(float $var)
    {
        $this->eyRate = $var;

        return $this;
    }

    /**
     * 市盈率
     *
     * Generated from protobuf field <code>double peRate = 10;</code>
     * @return float
     */
    public function getPeRate()
    {
        return $this->peRate;
    }

    /**
     * 市盈率
     *
     * Generated from protobuf field <code>double peRate = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setPeRate(float $var)
    {
        $this->peRate = $var;

        return $this;
    }

    /**
     * 市净率
     *
     * Generated from protobuf field <code>double pbRate = 11;</code>
     * @return float
     */
    public function getPbRate()
    {
        return $this->pbRate;
    }

    /**
     * 市净率
     *
     * Generated from protobuf field <code>double pbRate = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setPbRate(float $var)
    {
        $this->pbRate = $var;

        return $this;
    }

    /**
     * 市盈率TTM
     *
     * Generated from protobuf field <code>double peTTMRate = 12;</code>
     * @return float
     */
    public function getPeTTMRate()
    {
        return $this->peTTMRate;
    }

    /**
     * 市盈率TTM
     *
     * Generated from protobuf field <code>double peTTMRate = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setPeTTMRate(float $var)
    {
        $this->peTTMRate = $var;

        return $this;
    }

    /**
     * 股息TTM，派息
     *
     * Generated from protobuf field <code>double dividendTTM = 13;</code>
     * @return float
     */
    public function getDividendTTM()
    {
        return $this->dividendTTM;
    }

    /**
     * 股息TTM，派息
     *
     * Generated from protobuf field <code>double dividendTTM = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setDividendTTM(float $var)
    {
        $this->dividendTTM = $var;

        return $this;
    }

    /**
     * 股息率TTM（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendRatioTTM = 14;</code>
     * @return float
     */
    public function getDividendRatioTTM()
    {
        return $this->dividendRatioTTM;
    }

    /**
     * 股息率TTM（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendRatioTTM = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setDividendRatioTTM(float $var)
    {
        $this->dividendRatioTTM = $var;

        return $this;
    }

    /**
     * 股息LFY，上一年度派息
     *
     * Generated from protobuf field <code>double dividendLFY = 15;</code>
     * @return float
     */
    public function getDividendLFY()
    {
        return $this->dividendLFY;
    }

    /**
     * 股息LFY，上一年度派息
     *
     * Generated from protobuf field <code>double dividendLFY = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setDividendLFY(float $var)
    {
        $this->dividendLFY = $var;

        return $this;
    }

    /**
     * 股息率LFY（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendLFYRatio = 16;</code>
     * @return float
     */
    public function getDividendLFYRatio()
    {
        return $this->dividendLFYRatio;
    }

    /**
     * 股息率LFY（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendLFYRatio = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setDividendLFYRatio(float $var)
    {
        $this->dividendLFYRatio = $var;

        return $this;
    }

}

