<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetSecuritySnapshot.proto

namespace Futu\Qot_GetSecuritySnapshot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *期货类型额外数据
 *
 * Generated from protobuf message <code>Qot_GetSecuritySnapshot.FutureSnapshotExData</code>
 */
class FutureSnapshotExData extends \Google\Protobuf\Internal\Message
{
    /**
     *昨结
     *
     * Generated from protobuf field <code>double lastSettlePrice = 1;</code>
     */
    protected $lastSettlePrice = 0.0;
    /**
     *持仓量
     *
     * Generated from protobuf field <code>int32 position = 2;</code>
     */
    protected $position = 0;
    /**
     *日增仓
     *
     * Generated from protobuf field <code>int32 positionChange = 3;</code>
     */
    protected $positionChange = 0;
    /**
     *最后交易日，只有非主连期货合约才有该字段
     *
     * Generated from protobuf field <code>string lastTradeTime = 4;</code>
     */
    protected $lastTradeTime = '';
    /**
     *最后交易日时间戳，只有非主连期货合约才有该字段
     *
     * Generated from protobuf field <code>double lastTradeTimestamp = 5;</code>
     */
    protected $lastTradeTimestamp = 0.0;
    /**
     *是否主连合约
     *
     * Generated from protobuf field <code>bool isMainContract = 6;</code>
     */
    protected $isMainContract = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $lastSettlePrice
     *          昨结
     *     @type int $position
     *          持仓量
     *     @type int $positionChange
     *          日增仓
     *     @type string $lastTradeTime
     *          最后交易日，只有非主连期货合约才有该字段
     *     @type float $lastTradeTimestamp
     *          最后交易日时间戳，只有非主连期货合约才有该字段
     *     @type bool $isMainContract
     *          是否主连合约
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetSecuritySnapshot\pb\QotGetSecuritySnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     *昨结
     *
     * Generated from protobuf field <code>double lastSettlePrice = 1;</code>
     * @return float
     */
    public function getLastSettlePrice()
    {
        return $this->lastSettlePrice;
    }

    /**
     *昨结
     *
     * Generated from protobuf field <code>double lastSettlePrice = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLastSettlePrice(float $var)
    {
        $this->lastSettlePrice = $var;

        return $this;
    }

    /**
     *持仓量
     *
     * Generated from protobuf field <code>int32 position = 2;</code>
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     *持仓量
     *
     * Generated from protobuf field <code>int32 position = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPosition(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->position = $var;

        return $this;
    }

    /**
     *日增仓
     *
     * Generated from protobuf field <code>int32 positionChange = 3;</code>
     * @return int
     */
    public function getPositionChange()
    {
        return $this->positionChange;
    }

    /**
     *日增仓
     *
     * Generated from protobuf field <code>int32 positionChange = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPositionChange(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->positionChange = $var;

        return $this;
    }

    /**
     *最后交易日，只有非主连期货合约才有该字段
     *
     * Generated from protobuf field <code>string lastTradeTime = 4;</code>
     * @return string
     */
    public function getLastTradeTime()
    {
        return $this->lastTradeTime;
    }

    /**
     *最后交易日，只有非主连期货合约才有该字段
     *
     * Generated from protobuf field <code>string lastTradeTime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLastTradeTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->lastTradeTime = $var;

        return $this;
    }

    /**
     *最后交易日时间戳，只有非主连期货合约才有该字段
     *
     * Generated from protobuf field <code>double lastTradeTimestamp = 5;</code>
     * @return float
     */
    public function getLastTradeTimestamp()
    {
        return $this->lastTradeTimestamp;
    }

    /**
     *最后交易日时间戳，只有非主连期货合约才有该字段
     *
     * Generated from protobuf field <code>double lastTradeTimestamp = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setLastTradeTimestamp(float $var)
    {
        $this->lastTradeTimestamp = $var;

        return $this;
    }

    /**
     *是否主连合约
     *
     * Generated from protobuf field <code>bool isMainContract = 6;</code>
     * @return bool
     */
    public function getIsMainContract()
    {
        return $this->isMainContract;
    }

    /**
     *是否主连合约
     *
     * Generated from protobuf field <code>bool isMainContract = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMainContract(bool $var)
    {
        $this->isMainContract = $var;

        return $this;
    }

}

