<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetSecuritySnapshot.proto

namespace Futu\Qot_GetSecuritySnapshot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *基金类型额外数据
 *
 * Generated from protobuf message <code>Qot_GetSecuritySnapshot.TrustSnapshotExData</code>
 */
class TrustSnapshotExData extends \Google\Protobuf\Internal\Message
{
    /**
     *股息率（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendYield = 1;</code>
     */
    protected $dividendYield = 0.0;
    /**
     *资产规模（单位：元）
     *
     * Generated from protobuf field <code>double aum = 2;</code>
     */
    protected $aum = 0.0;
    /**
     *总发行量
     *
     * Generated from protobuf field <code>int64 outstandingUnits = 3;</code>
     */
    protected $outstandingUnits = 0;
    /**
     *单位净值
     *
     * Generated from protobuf field <code>double netAssetValue = 4;</code>
     */
    protected $netAssetValue = 0.0;
    /**
     *溢价（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double premium = 5;</code>
     */
    protected $premium = 0.0;
    /**
     *Qot_Common.AssetClass，资产类别
     *
     * Generated from protobuf field <code>int32 assetClass = 6;</code>
     */
    protected $assetClass = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $dividendYield
     *          股息率（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *     @type float $aum
     *          资产规模（单位：元）
     *     @type int|string $outstandingUnits
     *          总发行量
     *     @type float $netAssetValue
     *          单位净值
     *     @type float $premium
     *          溢价（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *     @type int $assetClass
     *          Qot_Common.AssetClass，资产类别
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetSecuritySnapshot\pb\QotGetSecuritySnapshot::initOnce();
        parent::__construct($data);
    }

    /**
     *股息率（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendYield = 1;</code>
     * @return float
     */
    public function getDividendYield()
    {
        return $this->dividendYield;
    }

    /**
     *股息率（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double dividendYield = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDividendYield(float $var)
    {
        $this->dividendYield = $var;

        return $this;
    }

    /**
     *资产规模（单位：元）
     *
     * Generated from protobuf field <code>double aum = 2;</code>
     * @return float
     */
    public function getAum()
    {
        return $this->aum;
    }

    /**
     *资产规模（单位：元）
     *
     * Generated from protobuf field <code>double aum = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setAum(float $var)
    {
        $this->aum = $var;

        return $this;
    }

    /**
     *总发行量
     *
     * Generated from protobuf field <code>int64 outstandingUnits = 3;</code>
     * @return int|string
     */
    public function getOutstandingUnits()
    {
        return $this->outstandingUnits;
    }

    /**
     *总发行量
     *
     * Generated from protobuf field <code>int64 outstandingUnits = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOutstandingUnits(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->outstandingUnits = $var;

        return $this;
    }

    /**
     *单位净值
     *
     * Generated from protobuf field <code>double netAssetValue = 4;</code>
     * @return float
     */
    public function getNetAssetValue()
    {
        return $this->netAssetValue;
    }

    /**
     *单位净值
     *
     * Generated from protobuf field <code>double netAssetValue = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setNetAssetValue(float $var)
    {
        $this->netAssetValue = $var;

        return $this;
    }

    /**
     *溢价（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double premium = 5;</code>
     * @return float
     */
    public function getPremium()
    {
        return $this->premium;
    }

    /**
     *溢价（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double premium = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setPremium(float $var)
    {
        $this->premium = $var;

        return $this;
    }

    /**
     *Qot_Common.AssetClass，资产类别
     *
     * Generated from protobuf field <code>int32 assetClass = 6;</code>
     * @return int
     */
    public function getAssetClass()
    {
        return $this->assetClass;
    }

    /**
     *Qot_Common.AssetClass，资产类别
     *
     * Generated from protobuf field <code>int32 assetClass = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setAssetClass(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->assetClass = $var;

        return $this;
    }

}

