<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_UpdateOrderBook.proto

namespace Futu\Qot_UpdateOrderBook\pb;

class QotUpdateOrderBook
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEA\x03\x0A\x19Qot_UpdateOrderBook.proto\x12\x13Qot_UpdateOrderBook\"\x8F\x02\x0A\x03S2C\x12&\x0A\x08security\x18\x01 \x01(\x0B2\x14.Qot_Common.Security\x12\x0C\x0A\x04name\x18\x08 \x01(\x09\x12/\x0A\x10orderBookAskList\x18\x02 \x03(\x0B2\x15.Qot_Common.OrderBook\x12/\x0A\x10orderBookBidList\x18\x03 \x03(\x0B2\x15.Qot_Common.OrderBook\x12\x16\x0A\x0EsvrRecvTimeBid\x18\x04 \x01(\x09\x12\x1F\x0A\x17svrRecvTimeBidTimestamp\x18\x05 \x01(\x01\x12\x16\x0A\x0EsvrRecvTimeAsk\x18\x06 \x01(\x09\x12\x1F\x0A\x17svrRecvTimeAskTimestamp\x18\x07 \x01(\x01\"c\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12%\x0A\x03s2c\x18\x04 \x01(\x0B2\x18.Qot_UpdateOrderBook.S2CB9\xCA\x02\x18Futu\\Qot_UpdateOrderBook\xE2\x02\x1BFutu\\Qot_UpdateOrderBook\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

