<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetUserSecurityGroup.proto

namespace Futu\Qot_GetUserSecurityGroup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetUserSecurityGroup.GroupData</code>
 */
class GroupData extends \Google\Protobuf\Internal\Message
{
    /**
     * 自选股分组名字
     *
     * Generated from protobuf field <code>string groupName = 1;</code>
     */
    protected $groupName = '';
    /**
     * GroupType,自选股分组类型。
     *
     * Generated from protobuf field <code>int32 groupType = 2;</code>
     */
    protected $groupType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $groupName
     *           自选股分组名字
     *     @type int $groupType
     *           GroupType,自选股分组类型。
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetUserSecurityGroup\pb\QotGetUserSecurityGroup::initOnce();
        parent::__construct($data);
    }

    /**
     * 自选股分组名字
     *
     * Generated from protobuf field <code>string groupName = 1;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->groupName;
    }

    /**
     * 自选股分组名字
     *
     * Generated from protobuf field <code>string groupName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->groupName = $var;

        return $this;
    }

    /**
     * GroupType,自选股分组类型。
     *
     * Generated from protobuf field <code>int32 groupType = 2;</code>
     * @return int
     */
    public function getGroupType()
    {
        return $this->groupType;
    }

    /**
     * GroupType,自选股分组类型。
     *
     * Generated from protobuf field <code>int32 groupType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGroupType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->groupType = $var;

        return $this;
    }

}

