<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetUserSecurityGroup.proto

namespace Futu\Qot_GetUserSecurityGroup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetUserSecurityGroup.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     * 自选股分组列表
     *
     * Generated from protobuf field <code>repeated .Qot_GetUserSecurityGroup.GroupData groupList = 1;</code>
     */
    private $groupList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_GetUserSecurityGroup\GroupData[] $groupList
     *           自选股分组列表
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetUserSecurityGroup\pb\QotGetUserSecurityGroup::initOnce();
        parent::__construct($data);
    }

    /**
     * 自选股分组列表
     *
     * Generated from protobuf field <code>repeated .Qot_GetUserSecurityGroup.GroupData groupList = 1;</code>
     * @return RepeatedField<\Futu\Qot_GetUserSecurityGroup\GroupData>
     */
    public function getGroupList()
    {
        return $this->groupList;
    }

    /**
     * 自选股分组列表
     *
     * Generated from protobuf field <code>repeated .Qot_GetUserSecurityGroup.GroupData groupList = 1;</code>
     * @param \Futu\Qot_GetUserSecurityGroup\GroupData[] $var
     * @return $this
     */
    public function setGroupList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_GetUserSecurityGroup\GroupData::class);
        $this->groupList = $arr;

        return $this;
    }

}

