<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Notify.proto

namespace Futu\Notify;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Notify.ConnectStatus</code>
 */
class ConnectStatus extends \Google\Protobuf\Internal\Message
{
    /**
     *是否登陆行情服务器
     *
     * Generated from protobuf field <code>bool qotLogined = 1;</code>
     */
    protected $qotLogined = false;
    /**
     *是否登陆交易服务器
     *
     * Generated from protobuf field <code>bool trdLogined = 2;</code>
     */
    protected $trdLogined = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $qotLogined
     *          是否登陆行情服务器
     *     @type bool $trdLogined
     *          是否登陆交易服务器
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Notify\pb\Notify::initOnce();
        parent::__construct($data);
    }

    /**
     *是否登陆行情服务器
     *
     * Generated from protobuf field <code>bool qotLogined = 1;</code>
     * @return bool
     */
    public function getQotLogined()
    {
        return $this->qotLogined;
    }

    /**
     *是否登陆行情服务器
     *
     * Generated from protobuf field <code>bool qotLogined = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setQotLogined(bool $var)
    {
        $this->qotLogined = $var;

        return $this;
    }

    /**
     *是否登陆交易服务器
     *
     * Generated from protobuf field <code>bool trdLogined = 2;</code>
     * @return bool
     */
    public function getTrdLogined()
    {
        return $this->trdLogined;
    }

    /**
     *是否登陆交易服务器
     *
     * Generated from protobuf field <code>bool trdLogined = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setTrdLogined(bool $var)
    {
        $this->trdLogined = $var;

        return $this;
    }

}

