<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Notify.proto

namespace Futu\Notify;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Notify.GtwEvent</code>
 */
class GtwEvent extends \Google\Protobuf\Internal\Message
{
    /**
     *GtwEventType,事件类型
     *
     * Generated from protobuf field <code>int32 eventType = 1;</code>
     */
    protected $eventType = 0;
    /**
     *事件描述
     *
     * Generated from protobuf field <code>string desc = 2;</code>
     */
    protected $desc = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $eventType
     *          GtwEventType,事件类型
     *     @type string $desc
     *          事件描述
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Notify\pb\Notify::initOnce();
        parent::__construct($data);
    }

    /**
     *GtwEventType,事件类型
     *
     * Generated from protobuf field <code>int32 eventType = 1;</code>
     * @return int
     */
    public function getEventType()
    {
        return $this->eventType;
    }

    /**
     *GtwEventType,事件类型
     *
     * Generated from protobuf field <code>int32 eventType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEventType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->eventType = $var;

        return $this;
    }

    /**
     *事件描述
     *
     * Generated from protobuf field <code>string desc = 2;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     *事件描述
     *
     * Generated from protobuf field <code>string desc = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->desc = $var;

        return $this;
    }

}

