<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Notify.proto

namespace Futu\Notify;

use UnexpectedValueException;

/**
 * Protobuf type <code>Notify.NotifyType</code>
 */
class NotifyType
{
    /**
     *无
     *
     * Generated from protobuf enum <code>NotifyType_None = 0;</code>
     */
    const NotifyType_None = 0;
    /**
     *OpenD运行事件通知
     *
     * Generated from protobuf enum <code>NotifyType_GtwEvent = 1;</code>
     */
    const NotifyType_GtwEvent = 1;
    /**
     *程序状态
     *
     * Generated from protobuf enum <code>NotifyType_ProgramStatus = 2;</code>
     */
    const NotifyType_ProgramStatus = 2;
    /**
     *连接状态
     *
     * Generated from protobuf enum <code>NotifyType_ConnStatus = 3;</code>
     */
    const NotifyType_ConnStatus = 3;
    /**
     *行情权限
     *
     * Generated from protobuf enum <code>NotifyType_QotRight = 4;</code>
     */
    const NotifyType_QotRight = 4;
    /**
     *用户等级，已在2.10版本之后废弃
     *
     * Generated from protobuf enum <code>NotifyType_APILevel = 5;</code>
     */
    const NotifyType_APILevel = 5;
    /**
     *API额度
     *
     * Generated from protobuf enum <code>NotifyType_APIQuota = 6;</code>
     */
    const NotifyType_APIQuota = 6;
    /**
     * 已使用额度
     *
     * Generated from protobuf enum <code>NotifyType_UsedQuota = 7;</code>
     */
    const NotifyType_UsedQuota = 7;

    private static $valueToName = [
        self::NotifyType_None => 'NotifyType_None',
        self::NotifyType_GtwEvent => 'NotifyType_GtwEvent',
        self::NotifyType_ProgramStatus => 'NotifyType_ProgramStatus',
        self::NotifyType_ConnStatus => 'NotifyType_ConnStatus',
        self::NotifyType_QotRight => 'NotifyType_QotRight',
        self::NotifyType_APILevel => 'NotifyType_APILevel',
        self::NotifyType_APIQuota => 'NotifyType_APIQuota',
        self::NotifyType_UsedQuota => 'NotifyType_UsedQuota',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

