<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Notify.proto

namespace Futu\Notify;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Notify.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *通知类型
     *
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    protected $type = 0;
    /**
     *事件通息
     *
     * Generated from protobuf field <code>.Notify.GtwEvent event = 2;</code>
     */
    protected $event = null;
    /**
     *程序状态
     *
     * Generated from protobuf field <code>.Notify.ProgramStatus programStatus = 3;</code>
     */
    protected $programStatus = null;
    /**
     *连接状态
     *
     * Generated from protobuf field <code>.Notify.ConnectStatus connectStatus = 4;</code>
     */
    protected $connectStatus = null;
    /**
     *行情权限
     *
     * Generated from protobuf field <code>.Notify.QotRight qotRight = 5;</code>
     */
    protected $qotRight = null;
    /**
     *用户等级，已在2.10版本之后废弃
     *
     * Generated from protobuf field <code>.Notify.APILevel apiLevel = 6;</code>
     */
    protected $apiLevel = null;
    /**
     *API额度
     *
     * Generated from protobuf field <code>.Notify.APIQuota apiQuota = 7;</code>
     */
    protected $apiQuota = null;
    /**
     * 已使用额度
     *
     * Generated from protobuf field <code>.Notify.UsedQuota usedQuota = 8;</code>
     */
    protected $usedQuota = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *          通知类型
     *     @type \Futu\Notify\GtwEvent $event
     *          事件通息
     *     @type \Futu\Notify\ProgramStatus $programStatus
     *          程序状态
     *     @type \Futu\Notify\ConnectStatus $connectStatus
     *          连接状态
     *     @type \Futu\Notify\QotRight $qotRight
     *          行情权限
     *     @type \Futu\Notify\APILevel $apiLevel
     *          用户等级，已在2.10版本之后废弃
     *     @type \Futu\Notify\APIQuota $apiQuota
     *          API额度
     *     @type \Futu\Notify\UsedQuota $usedQuota
     *           已使用额度
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Notify\pb\Notify::initOnce();
        parent::__construct($data);
    }

    /**
     *通知类型
     *
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *通知类型
     *
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     *事件通息
     *
     * Generated from protobuf field <code>.Notify.GtwEvent event = 2;</code>
     * @return \Futu\Notify\GtwEvent|null
     */
    public function getEvent()
    {
        return $this->event;
    }

    public function hasEvent()
    {
        return isset($this->event);
    }

    public function clearEvent()
    {
        unset($this->event);
    }

    /**
     *事件通息
     *
     * Generated from protobuf field <code>.Notify.GtwEvent event = 2;</code>
     * @param \Futu\Notify\GtwEvent $var
     * @return $this
     */
    public function setEvent(\Futu\Notify\GtwEvent|null $var)
    {
        $this->event = $var;

        return $this;
    }

    /**
     *程序状态
     *
     * Generated from protobuf field <code>.Notify.ProgramStatus programStatus = 3;</code>
     * @return \Futu\Notify\ProgramStatus|null
     */
    public function getProgramStatus()
    {
        return $this->programStatus;
    }

    public function hasProgramStatus()
    {
        return isset($this->programStatus);
    }

    public function clearProgramStatus()
    {
        unset($this->programStatus);
    }

    /**
     *程序状态
     *
     * Generated from protobuf field <code>.Notify.ProgramStatus programStatus = 3;</code>
     * @param \Futu\Notify\ProgramStatus $var
     * @return $this
     */
    public function setProgramStatus(\Futu\Notify\ProgramStatus|null $var)
    {
        $this->programStatus = $var;

        return $this;
    }

    /**
     *连接状态
     *
     * Generated from protobuf field <code>.Notify.ConnectStatus connectStatus = 4;</code>
     * @return \Futu\Notify\ConnectStatus|null
     */
    public function getConnectStatus()
    {
        return $this->connectStatus;
    }

    public function hasConnectStatus()
    {
        return isset($this->connectStatus);
    }

    public function clearConnectStatus()
    {
        unset($this->connectStatus);
    }

    /**
     *连接状态
     *
     * Generated from protobuf field <code>.Notify.ConnectStatus connectStatus = 4;</code>
     * @param \Futu\Notify\ConnectStatus $var
     * @return $this
     */
    public function setConnectStatus(\Futu\Notify\ConnectStatus|null $var)
    {
        $this->connectStatus = $var;

        return $this;
    }

    /**
     *行情权限
     *
     * Generated from protobuf field <code>.Notify.QotRight qotRight = 5;</code>
     * @return \Futu\Notify\QotRight|null
     */
    public function getQotRight()
    {
        return $this->qotRight;
    }

    public function hasQotRight()
    {
        return isset($this->qotRight);
    }

    public function clearQotRight()
    {
        unset($this->qotRight);
    }

    /**
     *行情权限
     *
     * Generated from protobuf field <code>.Notify.QotRight qotRight = 5;</code>
     * @param \Futu\Notify\QotRight $var
     * @return $this
     */
    public function setQotRight(\Futu\Notify\QotRight|null $var)
    {
        $this->qotRight = $var;

        return $this;
    }

    /**
     *用户等级，已在2.10版本之后废弃
     *
     * Generated from protobuf field <code>.Notify.APILevel apiLevel = 6;</code>
     * @return \Futu\Notify\APILevel|null
     */
    public function getApiLevel()
    {
        return $this->apiLevel;
    }

    public function hasApiLevel()
    {
        return isset($this->apiLevel);
    }

    public function clearApiLevel()
    {
        unset($this->apiLevel);
    }

    /**
     *用户等级，已在2.10版本之后废弃
     *
     * Generated from protobuf field <code>.Notify.APILevel apiLevel = 6;</code>
     * @param \Futu\Notify\APILevel $var
     * @return $this
     */
    public function setApiLevel(\Futu\Notify\APILevel|null $var)
    {
        $this->apiLevel = $var;

        return $this;
    }

    /**
     *API额度
     *
     * Generated from protobuf field <code>.Notify.APIQuota apiQuota = 7;</code>
     * @return \Futu\Notify\APIQuota|null
     */
    public function getApiQuota()
    {
        return $this->apiQuota;
    }

    public function hasApiQuota()
    {
        return isset($this->apiQuota);
    }

    public function clearApiQuota()
    {
        unset($this->apiQuota);
    }

    /**
     *API额度
     *
     * Generated from protobuf field <code>.Notify.APIQuota apiQuota = 7;</code>
     * @param \Futu\Notify\APIQuota $var
     * @return $this
     */
    public function setApiQuota(\Futu\Notify\APIQuota|null $var)
    {
        $this->apiQuota = $var;

        return $this;
    }

    /**
     * 已使用额度
     *
     * Generated from protobuf field <code>.Notify.UsedQuota usedQuota = 8;</code>
     * @return \Futu\Notify\UsedQuota|null
     */
    public function getUsedQuota()
    {
        return $this->usedQuota;
    }

    public function hasUsedQuota()
    {
        return isset($this->usedQuota);
    }

    public function clearUsedQuota()
    {
        unset($this->usedQuota);
    }

    /**
     * 已使用额度
     *
     * Generated from protobuf field <code>.Notify.UsedQuota usedQuota = 8;</code>
     * @param \Futu\Notify\UsedQuota $var
     * @return $this
     */
    public function setUsedQuota(\Futu\Notify\UsedQuota|null $var)
    {
        $this->usedQuota = $var;

        return $this;
    }

}

