<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetFunds.proto

namespace Futu\Trd_GetFunds;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_GetFunds.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     */
    protected $header = null;
    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 2;</code>
     */
    protected $refreshCache = false;
    /**
     *正常情况下，服务器有更新就会立即推送到OpenD，OpenD缓存着数据，API请求过来，返回同步的缓存数据，一般不需要指定刷新缓存，保证快速返回且减少对服务器的压力
     *如果遇到丢包等情况，可能出现缓存数据与服务器不一致，用户如果发现数据更新有异样，可指定刷新缓存，解决数据同步的问题。
     *
     * Generated from protobuf field <code>int32 currency = 3;</code>
     */
    protected $currency = 0;
    /**
     *账户资产类型，JP信用/衍生品账户必填，参考 Trd_Common.TrdAssetCategory
     *
     * Generated from protobuf field <code>int32 assetCategory = 4;</code>
     */
    protected $assetCategory = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Trd_Common\TrdHeader $header
     *          交易公共参数头
     *     @type bool $refreshCache
     *          立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *     @type int $currency
     *          正常情况下，服务器有更新就会立即推送到OpenD，OpenD缓存着数据，API请求过来，返回同步的缓存数据，一般不需要指定刷新缓存，保证快速返回且减少对服务器的压力
     *          如果遇到丢包等情况，可能出现缓存数据与服务器不一致，用户如果发现数据更新有异样，可指定刷新缓存，解决数据同步的问题。
     *     @type int $assetCategory
     *          账户资产类型，JP信用/衍生品账户必填，参考 Trd_Common.TrdAssetCategory
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_GetFunds\pb\TrdGetFunds::initOnce();
        parent::__construct($data);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @return \Futu\Trd_Common\TrdHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @param \Futu\Trd_Common\TrdHeader $var
     * @return $this
     */
    public function setHeader(\Futu\Trd_Common\TrdHeader|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 2;</code>
     * @return bool
     */
    public function getRefreshCache()
    {
        return $this->refreshCache;
    }

    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setRefreshCache(bool $var)
    {
        $this->refreshCache = $var;

        return $this;
    }

    /**
     *正常情况下，服务器有更新就会立即推送到OpenD，OpenD缓存着数据，API请求过来，返回同步的缓存数据，一般不需要指定刷新缓存，保证快速返回且减少对服务器的压力
     *如果遇到丢包等情况，可能出现缓存数据与服务器不一致，用户如果发现数据更新有异样，可指定刷新缓存，解决数据同步的问题。
     *
     * Generated from protobuf field <code>int32 currency = 3;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     *正常情况下，服务器有更新就会立即推送到OpenD，OpenD缓存着数据，API请求过来，返回同步的缓存数据，一般不需要指定刷新缓存，保证快速返回且减少对服务器的压力
     *如果遇到丢包等情况，可能出现缓存数据与服务器不一致，用户如果发现数据更新有异样，可指定刷新缓存，解决数据同步的问题。
     *
     * Generated from protobuf field <code>int32 currency = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->currency = $var;

        return $this;
    }

    /**
     *账户资产类型，JP信用/衍生品账户必填，参考 Trd_Common.TrdAssetCategory
     *
     * Generated from protobuf field <code>int32 assetCategory = 4;</code>
     * @return int
     */
    public function getAssetCategory()
    {
        return $this->assetCategory;
    }

    /**
     *账户资产类型，JP信用/衍生品账户必填，参考 Trd_Common.TrdAssetCategory
     *
     * Generated from protobuf field <code>int32 assetCategory = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAssetCategory(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->assetCategory = $var;

        return $this;
    }

}

