<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetMarketState.proto

namespace Futu\Qot_GetMarketState;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetMarketState.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     * 市场状态信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetMarketState.MarketInfo marketInfoList = 1;</code>
     */
    private $marketInfoList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_GetMarketState\MarketInfo[] $marketInfoList
     *           市场状态信息
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetMarketState\pb\QotGetMarketState::initOnce();
        parent::__construct($data);
    }

    /**
     * 市场状态信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetMarketState.MarketInfo marketInfoList = 1;</code>
     * @return RepeatedField<\Futu\Qot_GetMarketState\MarketInfo>
     */
    public function getMarketInfoList()
    {
        return $this->marketInfoList;
    }

    /**
     * 市场状态信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetMarketState.MarketInfo marketInfoList = 1;</code>
     * @param \Futu\Qot_GetMarketState\MarketInfo[] $var
     * @return $this
     */
    public function setMarketInfoList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_GetMarketState\MarketInfo::class);
        $this->marketInfoList = $arr;

        return $this;
    }

}

