<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetOptionChain.proto

namespace Futu\Qot_GetOptionChain;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetOptionChain.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *期权标的股，目前仅支持传入港美正股以及恒指国指
     *
     * Generated from protobuf field <code>.Qot_Common.Security owner = 1;</code>
     */
    protected $owner = null;
    /**
     *Qot_Common.IndexOptionType，指数期权的类型，仅用于恒指国指
     *
     * Generated from protobuf field <code>int32 indexOptionType = 6;</code>
     */
    protected $indexOptionType = 0;
    /**
     *Qot_Common.OptionType，期权类型，可选字段，不指定则表示都返回
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     */
    protected $type = 0;
    /**
     *OptionCondType，价内价外，可选字段，不指定则表示都返回
     *
     * Generated from protobuf field <code>int32 condition = 3;</code>
     */
    protected $condition = 0;
    /**
     *期权到期日开始时间
     *
     * Generated from protobuf field <code>string beginTime = 4;</code>
     */
    protected $beginTime = '';
    /**
     *期权到期日结束时间，时间跨度最多一个月
     *
     * Generated from protobuf field <code>string endTime = 5;</code>
     */
    protected $endTime = '';
    /**
     *数据字段筛选
     *
     * Generated from protobuf field <code>.Qot_GetOptionChain.DataFilter dataFilter = 7;</code>
     */
    protected $dataFilter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $owner
     *          期权标的股，目前仅支持传入港美正股以及恒指国指
     *     @type int $indexOptionType
     *          Qot_Common.IndexOptionType，指数期权的类型，仅用于恒指国指
     *     @type int $type
     *          Qot_Common.OptionType，期权类型，可选字段，不指定则表示都返回
     *     @type int $condition
     *          OptionCondType，价内价外，可选字段，不指定则表示都返回
     *     @type string $beginTime
     *          期权到期日开始时间
     *     @type string $endTime
     *          期权到期日结束时间，时间跨度最多一个月
     *     @type \Futu\Qot_GetOptionChain\DataFilter $dataFilter
     *          数据字段筛选
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetOptionChain\pb\QotGetOptionChain::initOnce();
        parent::__construct($data);
    }

    /**
     *期权标的股，目前仅支持传入港美正股以及恒指国指
     *
     * Generated from protobuf field <code>.Qot_Common.Security owner = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getOwner()
    {
        return $this->owner;
    }

    public function hasOwner()
    {
        return isset($this->owner);
    }

    public function clearOwner()
    {
        unset($this->owner);
    }

    /**
     *期权标的股，目前仅支持传入港美正股以及恒指国指
     *
     * Generated from protobuf field <code>.Qot_Common.Security owner = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setOwner(\Futu\Qot_Common\Security|null $var)
    {
        $this->owner = $var;

        return $this;
    }

    /**
     *Qot_Common.IndexOptionType，指数期权的类型，仅用于恒指国指
     *
     * Generated from protobuf field <code>int32 indexOptionType = 6;</code>
     * @return int
     */
    public function getIndexOptionType()
    {
        return $this->indexOptionType;
    }

    /**
     *Qot_Common.IndexOptionType，指数期权的类型，仅用于恒指国指
     *
     * Generated from protobuf field <code>int32 indexOptionType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setIndexOptionType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->indexOptionType = $var;

        return $this;
    }

    /**
     *Qot_Common.OptionType，期权类型，可选字段，不指定则表示都返回
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *Qot_Common.OptionType，期权类型，可选字段，不指定则表示都返回
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     *OptionCondType，价内价外，可选字段，不指定则表示都返回
     *
     * Generated from protobuf field <code>int32 condition = 3;</code>
     * @return int
     */
    public function getCondition()
    {
        return $this->condition;
    }

    /**
     *OptionCondType，价内价外，可选字段，不指定则表示都返回
     *
     * Generated from protobuf field <code>int32 condition = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCondition(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->condition = $var;

        return $this;
    }

    /**
     *期权到期日开始时间
     *
     * Generated from protobuf field <code>string beginTime = 4;</code>
     * @return string
     */
    public function getBeginTime()
    {
        return $this->beginTime;
    }

    /**
     *期权到期日开始时间
     *
     * Generated from protobuf field <code>string beginTime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBeginTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->beginTime = $var;

        return $this;
    }

    /**
     *期权到期日结束时间，时间跨度最多一个月
     *
     * Generated from protobuf field <code>string endTime = 5;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     *期权到期日结束时间，时间跨度最多一个月
     *
     * Generated from protobuf field <code>string endTime = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endTime = $var;

        return $this;
    }

    /**
     *数据字段筛选
     *
     * Generated from protobuf field <code>.Qot_GetOptionChain.DataFilter dataFilter = 7;</code>
     * @return \Futu\Qot_GetOptionChain\DataFilter|null
     */
    public function getDataFilter()
    {
        return $this->dataFilter;
    }

    public function hasDataFilter()
    {
        return isset($this->dataFilter);
    }

    public function clearDataFilter()
    {
        unset($this->dataFilter);
    }

    /**
     *数据字段筛选
     *
     * Generated from protobuf field <code>.Qot_GetOptionChain.DataFilter dataFilter = 7;</code>
     * @param \Futu\Qot_GetOptionChain\DataFilter $var
     * @return $this
     */
    public function setDataFilter(\Futu\Qot_GetOptionChain\DataFilter|null $var)
    {
        $this->dataFilter = $var;

        return $this;
    }

}

