<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetOptionChain.proto

namespace Futu\Qot_GetOptionChain;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetOptionChain.OptionChain</code>
 */
class OptionChain extends \Google\Protobuf\Internal\Message
{
    /**
     *行权日
     *
     * Generated from protobuf field <code>string strikeTime = 1;</code>
     */
    protected $strikeTime = '';
    /**
     *期权信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetOptionChain.OptionItem option = 2;</code>
     */
    private $option;
    /**
     *行权日时间戳
     *
     * Generated from protobuf field <code>double strikeTimestamp = 3;</code>
     */
    protected $strikeTimestamp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $strikeTime
     *          行权日
     *     @type \Futu\Qot_GetOptionChain\OptionItem[] $option
     *          期权信息
     *     @type float $strikeTimestamp
     *          行权日时间戳
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetOptionChain\pb\QotGetOptionChain::initOnce();
        parent::__construct($data);
    }

    /**
     *行权日
     *
     * Generated from protobuf field <code>string strikeTime = 1;</code>
     * @return string
     */
    public function getStrikeTime()
    {
        return $this->strikeTime;
    }

    /**
     *行权日
     *
     * Generated from protobuf field <code>string strikeTime = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStrikeTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->strikeTime = $var;

        return $this;
    }

    /**
     *期权信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetOptionChain.OptionItem option = 2;</code>
     * @return RepeatedField<\Futu\Qot_GetOptionChain\OptionItem>
     */
    public function getOption()
    {
        return $this->option;
    }

    /**
     *期权信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetOptionChain.OptionItem option = 2;</code>
     * @param \Futu\Qot_GetOptionChain\OptionItem[] $var
     * @return $this
     */
    public function setOption(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_GetOptionChain\OptionItem::class);
        $this->option = $arr;

        return $this;
    }

    /**
     *行权日时间戳
     *
     * Generated from protobuf field <code>double strikeTimestamp = 3;</code>
     * @return float
     */
    public function getStrikeTimestamp()
    {
        return $this->strikeTimestamp;
    }

    /**
     *行权日时间戳
     *
     * Generated from protobuf field <code>double strikeTimestamp = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setStrikeTimestamp(float $var)
    {
        $this->strikeTimestamp = $var;

        return $this;
    }

}

