<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use UnexpectedValueException;

/**
 * 资产类别
 *
 * Protobuf type <code>Qot_Common.AssetClass</code>
 */
class AssetClass
{
    /**
     *未知
     *
     * Generated from protobuf enum <code>AssetClass_Unknow = 0;</code>
     */
    const AssetClass_Unknow = 0;
    /**
     *股票
     *
     * Generated from protobuf enum <code>AssetClass_Stock = 1;</code>
     */
    const AssetClass_Stock = 1;
    /**
     *债券
     *
     * Generated from protobuf enum <code>AssetClass_Bond = 2;</code>
     */
    const AssetClass_Bond = 2;
    /**
     *商品
     *
     * Generated from protobuf enum <code>AssetClass_Commodity = 3;</code>
     */
    const AssetClass_Commodity = 3;
    /**
     *货币市场
     *
     * Generated from protobuf enum <code>AssetClass_CurrencyMarket = 4;</code>
     */
    const AssetClass_CurrencyMarket = 4;
    /**
     *期货
     *
     * Generated from protobuf enum <code>AssetClass_Future = 5;</code>
     */
    const AssetClass_Future = 5;
    /**
     *掉期
     *
     * Generated from protobuf enum <code>AssetClass_Swap = 6;</code>
     */
    const AssetClass_Swap = 6;

    private static $valueToName = [
        self::AssetClass_Unknow => 'AssetClass_Unknow',
        self::AssetClass_Stock => 'AssetClass_Stock',
        self::AssetClass_Bond => 'AssetClass_Bond',
        self::AssetClass_Commodity => 'AssetClass_Commodity',
        self::AssetClass_CurrencyMarket => 'AssetClass_CurrencyMarket',
        self::AssetClass_Future => 'AssetClass_Future',
        self::AssetClass_Swap => 'AssetClass_Swap',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

