<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use UnexpectedValueException;

/**
 * 所属交易所
 *
 * Protobuf type <code>Qot_Common.ExchType</code>
 */
class ExchType
{
    /**
     *未知
     *
     * Generated from protobuf enum <code>ExchType_Unknown = 0;</code>
     */
    const ExchType_Unknown = 0;
    /**
     * 港交所·主板
     *
     * Generated from protobuf enum <code>ExchType_HK_MainBoard = 1;</code>
     */
    const ExchType_HK_MainBoard = 1;
    /**
     *港交所·创业板
     *
     * Generated from protobuf enum <code>ExchType_HK_GEMBoard = 2;</code>
     */
    const ExchType_HK_GEMBoard = 2;
    /**
     *港交所
     *
     * Generated from protobuf enum <code>ExchType_HK_HKEX = 3;</code>
     */
    const ExchType_HK_HKEX = 3;
    /**
     *纽交所
     *
     * Generated from protobuf enum <code>ExchType_US_NYSE = 4;</code>
     */
    const ExchType_US_NYSE = 4;
    /**
     *纳斯达克
     *
     * Generated from protobuf enum <code>ExchType_US_Nasdaq = 5;</code>
     */
    const ExchType_US_Nasdaq = 5;
    /**
     *OTC 市场
     *
     * Generated from protobuf enum <code>ExchType_US_Pink = 6;</code>
     */
    const ExchType_US_Pink = 6;
    /**
     *美交所 
     *
     * Generated from protobuf enum <code>ExchType_US_AMEX = 7;</code>
     */
    const ExchType_US_AMEX = 7;
    /**
     *美国（仅美股期权适用）
     *
     * Generated from protobuf enum <code>ExchType_US_Option = 8;</code>
     */
    const ExchType_US_Option = 8;
    /**
     *NYMEX 
     *
     * Generated from protobuf enum <code>ExchType_US_NYMEX = 9;</code>
     */
    const ExchType_US_NYMEX = 9;
    /**
     *COMEX
     *
     * Generated from protobuf enum <code>ExchType_US_COMEX = 10;</code>
     */
    const ExchType_US_COMEX = 10;
    /**
     *CBOT
     *
     * Generated from protobuf enum <code>ExchType_US_CBOT = 11;</code>
     */
    const ExchType_US_CBOT = 11;
    /**
     *CME
     *
     * Generated from protobuf enum <code>ExchType_US_CME = 12;</code>
     */
    const ExchType_US_CME = 12;
    /**
     *CBOE
     *
     * Generated from protobuf enum <code>ExchType_US_CBOE = 13;</code>
     */
    const ExchType_US_CBOE = 13;
    /**
     *上交所  
     *
     * Generated from protobuf enum <code>ExchType_CN_SH = 14;</code>
     */
    const ExchType_CN_SH = 14;
    /**
     *深交所
     *
     * Generated from protobuf enum <code>ExchType_CN_SZ = 15;</code>
     */
    const ExchType_CN_SZ = 15;
    /**
     *科创板
     *
     * Generated from protobuf enum <code>ExchType_CN_STIB = 16;</code>
     */
    const ExchType_CN_STIB = 16;
    /**
     *新交所
     *
     * Generated from protobuf enum <code>ExchType_SG_SGX = 17;</code>
     */
    const ExchType_SG_SGX = 17;
    /**
     *大阪交易所 
     *
     * Generated from protobuf enum <code>ExchType_JP_OSE = 18;</code>
     */
    const ExchType_JP_OSE = 18;

    private static $valueToName = [
        self::ExchType_Unknown => 'ExchType_Unknown',
        self::ExchType_HK_MainBoard => 'ExchType_HK_MainBoard',
        self::ExchType_HK_GEMBoard => 'ExchType_HK_GEMBoard',
        self::ExchType_HK_HKEX => 'ExchType_HK_HKEX',
        self::ExchType_US_NYSE => 'ExchType_US_NYSE',
        self::ExchType_US_Nasdaq => 'ExchType_US_Nasdaq',
        self::ExchType_US_Pink => 'ExchType_US_Pink',
        self::ExchType_US_AMEX => 'ExchType_US_AMEX',
        self::ExchType_US_Option => 'ExchType_US_Option',
        self::ExchType_US_NYMEX => 'ExchType_US_NYMEX',
        self::ExchType_US_COMEX => 'ExchType_US_COMEX',
        self::ExchType_US_CBOT => 'ExchType_US_CBOT',
        self::ExchType_US_CME => 'ExchType_US_CME',
        self::ExchType_US_CBOE => 'ExchType_US_CBOE',
        self::ExchType_CN_SH => 'ExchType_CN_SH',
        self::ExchType_CN_SZ => 'ExchType_CN_SZ',
        self::ExchType_CN_STIB => 'ExchType_CN_STIB',
        self::ExchType_SG_SGX => 'ExchType_SG_SGX',
        self::ExchType_JP_OSE => 'ExchType_JP_OSE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

