<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_Common.FutureBasicQotExData</code>
 */
class FutureBasicQotExData extends \Google\Protobuf\Internal\Message
{
    /**
     *昨结
     *
     * Generated from protobuf field <code>double lastSettlePrice = 1;</code>
     */
    protected $lastSettlePrice = 0.0;
    /**
     *持仓量
     *
     * Generated from protobuf field <code>int32 position = 2;</code>
     */
    protected $position = 0;
    /**
     *日增仓
     *
     * Generated from protobuf field <code>int32 positionChange = 3;</code>
     */
    protected $positionChange = 0;
    /**
     *距离到期日天数
     *
     * Generated from protobuf field <code>int32 expiryDateDistance = 4;</code>
     */
    protected $expiryDateDistance = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $lastSettlePrice
     *          昨结
     *     @type int $position
     *          持仓量
     *     @type int $positionChange
     *          日增仓
     *     @type int $expiryDateDistance
     *          距离到期日天数
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *昨结
     *
     * Generated from protobuf field <code>double lastSettlePrice = 1;</code>
     * @return float
     */
    public function getLastSettlePrice()
    {
        return $this->lastSettlePrice;
    }

    /**
     *昨结
     *
     * Generated from protobuf field <code>double lastSettlePrice = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLastSettlePrice(float $var)
    {
        $this->lastSettlePrice = $var;

        return $this;
    }

    /**
     *持仓量
     *
     * Generated from protobuf field <code>int32 position = 2;</code>
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     *持仓量
     *
     * Generated from protobuf field <code>int32 position = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPosition(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->position = $var;

        return $this;
    }

    /**
     *日增仓
     *
     * Generated from protobuf field <code>int32 positionChange = 3;</code>
     * @return int
     */
    public function getPositionChange()
    {
        return $this->positionChange;
    }

    /**
     *日增仓
     *
     * Generated from protobuf field <code>int32 positionChange = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPositionChange(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->positionChange = $var;

        return $this;
    }

    /**
     *距离到期日天数
     *
     * Generated from protobuf field <code>int32 expiryDateDistance = 4;</code>
     * @return int
     */
    public function getExpiryDateDistance()
    {
        return $this->expiryDateDistance;
    }

    /**
     *距离到期日天数
     *
     * Generated from protobuf field <code>int32 expiryDateDistance = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setExpiryDateDistance(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->expiryDateDistance = $var;

        return $this;
    }

}

