<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use UnexpectedValueException;

/**
 * 标准期权链类型
 *
 * Protobuf type <code>Qot_Common.OptionStandardType</code>
 */
class OptionStandardType
{
    /**
     *未知
     *
     * Generated from protobuf enum <code>OptionStandardType_Unknown = 0;</code>
     */
    const OptionStandardType_Unknown = 0;
    /**
     * 标准
     *
     * Generated from protobuf enum <code>OptionStandardType_Standard = 1;</code>
     */
    const OptionStandardType_Standard = 1;
    /**
     * 非标准
     *
     * Generated from protobuf enum <code>OptionStandardType_NonStandard = 2;</code>
     */
    const OptionStandardType_NonStandard = 2;

    private static $valueToName = [
        self::OptionStandardType_Unknown => 'OptionStandardType_Unknown',
        self::OptionStandardType_Standard => 'OptionStandardType_Standard',
        self::OptionStandardType_NonStandard => 'OptionStandardType_NonStandard',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

