<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_Common.OrderBookDetail</code>
 */
class OrderBookDetail extends \Google\Protobuf\Internal\Message
{
    /**
     *交易所订单ID，与交易接口返回的订单ID并不一样
     *
     * Generated from protobuf field <code>int64 orderID = 1;</code>
     */
    protected $orderID = 0;
    /**
     *订单股数
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     */
    protected $volume = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $orderID
     *          交易所订单ID，与交易接口返回的订单ID并不一样
     *     @type int|string $volume
     *          订单股数
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *交易所订单ID，与交易接口返回的订单ID并不一样
     *
     * Generated from protobuf field <code>int64 orderID = 1;</code>
     * @return int|string
     */
    public function getOrderID()
    {
        return $this->orderID;
    }

    /**
     *交易所订单ID，与交易接口返回的订单ID并不一样
     *
     * Generated from protobuf field <code>int64 orderID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->orderID = $var;

        return $this;
    }

    /**
     *订单股数
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     *订单股数
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

}

