<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_Common.OrderBook</code>
 */
class OrderBook extends \Google\Protobuf\Internal\Message
{
    /**
     *委托价格
     *
     * Generated from protobuf field <code>double price = 1;</code>
     */
    protected $price = 0.0;
    /**
     *委托数量
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     */
    protected $volume = 0;
    /**
     *委托订单个数
     *
     * Generated from protobuf field <code>int32 orederCount = 3;</code>
     */
    protected $orederCount = 0;
    /**
     *订单信息，SF行情特有
     *
     * Generated from protobuf field <code>repeated .Qot_Common.OrderBookDetail detailList = 4;</code>
     */
    private $detailList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $price
     *          委托价格
     *     @type int|string $volume
     *          委托数量
     *     @type int $orederCount
     *          委托订单个数
     *     @type \Futu\Qot_Common\OrderBookDetail[] $detailList
     *          订单信息，SF行情特有
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *委托价格
     *
     * Generated from protobuf field <code>double price = 1;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     *委托价格
     *
     * Generated from protobuf field <code>double price = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice(float $var)
    {
        $this->price = $var;

        return $this;
    }

    /**
     *委托数量
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     *委托数量
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     *委托订单个数
     *
     * Generated from protobuf field <code>int32 orederCount = 3;</code>
     * @return int
     */
    public function getOrederCount()
    {
        return $this->orederCount;
    }

    /**
     *委托订单个数
     *
     * Generated from protobuf field <code>int32 orederCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOrederCount(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->orederCount = $var;

        return $this;
    }

    /**
     *订单信息，SF行情特有
     *
     * Generated from protobuf field <code>repeated .Qot_Common.OrderBookDetail detailList = 4;</code>
     * @return RepeatedField<\Futu\Qot_Common\OrderBookDetail>
     */
    public function getDetailList()
    {
        return $this->detailList;
    }

    /**
     *订单信息，SF行情特有
     *
     * Generated from protobuf field <code>repeated .Qot_Common.OrderBookDetail detailList = 4;</code>
     * @param \Futu\Qot_Common\OrderBookDetail[] $var
     * @return $this
     */
    public function setDetailList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\OrderBookDetail::class);
        $this->detailList = $arr;

        return $this;
    }

}

