<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *美股支持盘前盘后数据
 *科创板仅支持盘后数据：成交量，成交额
 *
 * Generated from protobuf message <code>Qot_Common.PreAfterMarketData</code>
 */
class PreAfterMarketData extends \Google\Protobuf\Internal\Message
{
    /**
     * 盘前或盘后 - 价格
     *
     * Generated from protobuf field <code>double price = 1;</code>
     */
    protected $price = 0.0;
    /**
     * 盘前或盘后 - 最高价
     *
     * Generated from protobuf field <code>double highPrice = 2;</code>
     */
    protected $highPrice = 0.0;
    /**
     * 盘前或盘后 - 最低价
     *
     * Generated from protobuf field <code>double lowPrice = 3;</code>
     */
    protected $lowPrice = 0.0;
    /**
     * 盘前或盘后 - 成交量
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     */
    protected $volume = 0;
    /**
     * 盘前或盘后 - 成交额
     *
     * Generated from protobuf field <code>double turnover = 5;</code>
     */
    protected $turnover = 0.0;
    /**
     * 盘前或盘后 - 涨跌额
     *
     * Generated from protobuf field <code>double changeVal = 6;</code>
     */
    protected $changeVal = 0.0;
    /**
     * 盘前或盘后 - 涨跌幅（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double changeRate = 7;</code>
     */
    protected $changeRate = 0.0;
    /**
     * 盘前或盘后 - 振幅（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double amplitude = 8;</code>
     */
    protected $amplitude = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $price
     *           盘前或盘后 - 价格
     *     @type float $highPrice
     *           盘前或盘后 - 最高价
     *     @type float $lowPrice
     *           盘前或盘后 - 最低价
     *     @type int|string $volume
     *           盘前或盘后 - 成交量
     *     @type float $turnover
     *           盘前或盘后 - 成交额
     *     @type float $changeVal
     *           盘前或盘后 - 涨跌额
     *     @type float $changeRate
     *           盘前或盘后 - 涨跌幅（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *     @type float $amplitude
     *           盘前或盘后 - 振幅（该字段为百分比字段，默认不展示%，如20实际对应20%）
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * 盘前或盘后 - 价格
     *
     * Generated from protobuf field <code>double price = 1;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * 盘前或盘后 - 价格
     *
     * Generated from protobuf field <code>double price = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice(float $var)
    {
        $this->price = $var;

        return $this;
    }

    /**
     * 盘前或盘后 - 最高价
     *
     * Generated from protobuf field <code>double highPrice = 2;</code>
     * @return float
     */
    public function getHighPrice()
    {
        return $this->highPrice;
    }

    /**
     * 盘前或盘后 - 最高价
     *
     * Generated from protobuf field <code>double highPrice = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setHighPrice(float $var)
    {
        $this->highPrice = $var;

        return $this;
    }

    /**
     * 盘前或盘后 - 最低价
     *
     * Generated from protobuf field <code>double lowPrice = 3;</code>
     * @return float
     */
    public function getLowPrice()
    {
        return $this->lowPrice;
    }

    /**
     * 盘前或盘后 - 最低价
     *
     * Generated from protobuf field <code>double lowPrice = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLowPrice(float $var)
    {
        $this->lowPrice = $var;

        return $this;
    }

    /**
     * 盘前或盘后 - 成交量
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * 盘前或盘后 - 成交量
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * 盘前或盘后 - 成交额
     *
     * Generated from protobuf field <code>double turnover = 5;</code>
     * @return float
     */
    public function getTurnover()
    {
        return $this->turnover;
    }

    /**
     * 盘前或盘后 - 成交额
     *
     * Generated from protobuf field <code>double turnover = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setTurnover(float $var)
    {
        $this->turnover = $var;

        return $this;
    }

    /**
     * 盘前或盘后 - 涨跌额
     *
     * Generated from protobuf field <code>double changeVal = 6;</code>
     * @return float
     */
    public function getChangeVal()
    {
        return $this->changeVal;
    }

    /**
     * 盘前或盘后 - 涨跌额
     *
     * Generated from protobuf field <code>double changeVal = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setChangeVal(float $var)
    {
        $this->changeVal = $var;

        return $this;
    }

    /**
     * 盘前或盘后 - 涨跌幅（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double changeRate = 7;</code>
     * @return float
     */
    public function getChangeRate()
    {
        return $this->changeRate;
    }

    /**
     * 盘前或盘后 - 涨跌幅（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double changeRate = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setChangeRate(float $var)
    {
        $this->changeRate = $var;

        return $this;
    }

    /**
     * 盘前或盘后 - 振幅（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double amplitude = 8;</code>
     * @return float
     */
    public function getAmplitude()
    {
        return $this->amplitude;
    }

    /**
     * 盘前或盘后 - 振幅（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double amplitude = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setAmplitude(float $var)
    {
        $this->amplitude = $var;

        return $this;
    }

}

