<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use UnexpectedValueException;

/**
 * 提醒类型
 *
 * Protobuf type <code>Qot_Common.PriceReminderType</code>
 */
class PriceReminderType
{
    /**
     * 未知
     *
     * Generated from protobuf enum <code>PriceReminderType_Unknown = 0;</code>
     */
    const PriceReminderType_Unknown = 0;
    /**
     * 价格涨到
     *
     * Generated from protobuf enum <code>PriceReminderType_PriceUp = 1;</code>
     */
    const PriceReminderType_PriceUp = 1;
    /**
     * 价格跌到
     *
     * Generated from protobuf enum <code>PriceReminderType_PriceDown = 2;</code>
     */
    const PriceReminderType_PriceDown = 2;
    /**
     * 日涨幅超（该字段为百分比字段，设置时填 20 表示 20%）
     *
     * Generated from protobuf enum <code>PriceReminderType_ChangeRateUp = 3;</code>
     */
    const PriceReminderType_ChangeRateUp = 3;
    /**
     * 日跌幅超（该字段为百分比字段，设置时填 20 表示 20%）
     *
     * Generated from protobuf enum <code>PriceReminderType_ChangeRateDown = 4;</code>
     */
    const PriceReminderType_ChangeRateDown = 4;
    /**
     * 5 分钟涨幅超（该字段为百分比字段，设置时填 20 表示 20%）
     *
     * Generated from protobuf enum <code>PriceReminderType_5MinChangeRateUp = 5;</code>
     */
    const PriceReminderType_5MinChangeRateUp = 5;
    /**
     * 5 分钟跌幅超（该字段为百分比字段，设置时填 20 表示 20%）
     *
     * Generated from protobuf enum <code>PriceReminderType_5MinChangeRateDown = 6;</code>
     */
    const PriceReminderType_5MinChangeRateDown = 6;
    /**
     * 成交量超过
     *
     * Generated from protobuf enum <code>PriceReminderType_VolumeUp = 7;</code>
     */
    const PriceReminderType_VolumeUp = 7;
    /**
     * 成交额超过
     *
     * Generated from protobuf enum <code>PriceReminderType_TurnoverUp = 8;</code>
     */
    const PriceReminderType_TurnoverUp = 8;
    /**
     * 换手率超过（该字段为百分比字段，设置时填 20 表示 20%）
     *
     * Generated from protobuf enum <code>PriceReminderType_TurnoverRateUp = 9;</code>
     */
    const PriceReminderType_TurnoverRateUp = 9;
    /**
     * 买一价高于
     *
     * Generated from protobuf enum <code>PriceReminderType_BidPriceUp = 10;</code>
     */
    const PriceReminderType_BidPriceUp = 10;
    /**
     * 卖一价低于
     *
     * Generated from protobuf enum <code>PriceReminderType_AskPriceDown = 11;</code>
     */
    const PriceReminderType_AskPriceDown = 11;
    /**
     * 买一量高于    
     *
     * Generated from protobuf enum <code>PriceReminderType_BidVolUp = 12;</code>
     */
    const PriceReminderType_BidVolUp = 12;
    /**
     * 卖一量高于
     *
     * Generated from protobuf enum <code>PriceReminderType_AskVolUp = 13;</code>
     */
    const PriceReminderType_AskVolUp = 13;
    /**
     * 3 分钟涨幅超（该字段为百分比字段，设置时填 20 表示 20%）
     *
     * Generated from protobuf enum <code>PriceReminderType_3MinChangeRateUp = 14;</code>
     */
    const PriceReminderType_3MinChangeRateUp = 14;
    /**
     * 3 分钟跌幅超（该字段为百分比字段，设置时填 20 表示 20%）
     *
     * Generated from protobuf enum <code>PriceReminderType_3MinChangeRateDown = 15;</code>
     */
    const PriceReminderType_3MinChangeRateDown = 15;

    private static $valueToName = [
        self::PriceReminderType_Unknown => 'PriceReminderType_Unknown',
        self::PriceReminderType_PriceUp => 'PriceReminderType_PriceUp',
        self::PriceReminderType_PriceDown => 'PriceReminderType_PriceDown',
        self::PriceReminderType_ChangeRateUp => 'PriceReminderType_ChangeRateUp',
        self::PriceReminderType_ChangeRateDown => 'PriceReminderType_ChangeRateDown',
        self::PriceReminderType_5MinChangeRateUp => 'PriceReminderType_5MinChangeRateUp',
        self::PriceReminderType_5MinChangeRateDown => 'PriceReminderType_5MinChangeRateDown',
        self::PriceReminderType_VolumeUp => 'PriceReminderType_VolumeUp',
        self::PriceReminderType_TurnoverUp => 'PriceReminderType_TurnoverUp',
        self::PriceReminderType_TurnoverRateUp => 'PriceReminderType_TurnoverRateUp',
        self::PriceReminderType_BidPriceUp => 'PriceReminderType_BidPriceUp',
        self::PriceReminderType_AskPriceDown => 'PriceReminderType_AskPriceDown',
        self::PriceReminderType_BidVolUp => 'PriceReminderType_BidVolUp',
        self::PriceReminderType_AskVolUp => 'PriceReminderType_AskVolUp',
        self::PriceReminderType_3MinChangeRateUp => 'PriceReminderType_3MinChangeRateUp',
        self::PriceReminderType_3MinChangeRateDown => 'PriceReminderType_3MinChangeRateDown',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

