<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use UnexpectedValueException;

/**
 * 提醒频率
 *
 * Protobuf type <code>Qot_Common.PriceReminderFreq</code>
 */
class PriceReminderFreq
{
    /**
     * 未知
     *
     * Generated from protobuf enum <code>PriceReminderFreq_Unknown = 0;</code>
     */
    const PriceReminderFreq_Unknown = 0;
    /**
     * 持续提醒
     *
     * Generated from protobuf enum <code>PriceReminderFreq_Always = 1;</code>
     */
    const PriceReminderFreq_Always = 1;
    /**
     * 每日一次
     *
     * Generated from protobuf enum <code>PriceReminderFreq_OnceADay = 2;</code>
     */
    const PriceReminderFreq_OnceADay = 2;
    /**
     * 仅提醒一次
     *
     * Generated from protobuf enum <code>PriceReminderFreq_OnlyOnce = 3;</code>
     */
    const PriceReminderFreq_OnlyOnce = 3;

    private static $valueToName = [
        self::PriceReminderFreq_Unknown => 'PriceReminderFreq_Unknown',
        self::PriceReminderFreq_Always => 'PriceReminderFreq_Always',
        self::PriceReminderFreq_OnceADay => 'PriceReminderFreq_OnceADay',
        self::PriceReminderFreq_OnlyOnce => 'PriceReminderFreq_OnlyOnce',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

