<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *两个字段确定一支股票
 *
 * Generated from protobuf message <code>Qot_Common.Security</code>
 */
class Security extends \Google\Protobuf\Internal\Message
{
    /**
     *QotMarket,股票市场
     *
     * Generated from protobuf field <code>int32 market = 1;</code>
     */
    protected $market = 0;
    /**
     *股票代码
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $market
     *          QotMarket,股票市场
     *     @type string $code
     *          股票代码
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *QotMarket,股票市场
     *
     * Generated from protobuf field <code>int32 market = 1;</code>
     * @return int
     */
    public function getMarket()
    {
        return $this->market;
    }

    /**
     *QotMarket,股票市场
     *
     * Generated from protobuf field <code>int32 market = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMarket(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->market = $var;

        return $this;
    }

    /**
     *股票代码
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *股票代码
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->code = $var;

        return $this;
    }

}

