<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_Common.SecurityStaticBasic</code>
 */
class SecurityStaticBasic extends \Google\Protobuf\Internal\Message
{
    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;
    /**
     *股票ID
     *
     * Generated from protobuf field <code>int64 id = 2;</code>
     */
    protected $id = 0;
    /**
     *每手数量,期权以及期货类型表示合约乘数
     *
     * Generated from protobuf field <code>int32 lotSize = 3;</code>
     */
    protected $lotSize = 0;
    /**
     *Qot_Common.SecurityType,股票类型
     *
     * Generated from protobuf field <code>int32 secType = 4;</code>
     */
    protected $secType = 0;
    /**
     *股票名字
     *
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     *上市时间字符串
     *
     * Generated from protobuf field <code>string listTime = 6;</code>
     */
    protected $listTime = '';
    /**
     *是否退市
     *
     * Generated from protobuf field <code>bool delisting = 7;</code>
     */
    protected $delisting = false;
    /**
     *上市时间戳
     *
     * Generated from protobuf field <code>double listTimestamp = 8;</code>
     */
    protected $listTimestamp = 0.0;
    /**
     *Qot_Common.ExchType,所属交易所
     *
     * Generated from protobuf field <code>int32 exchType = 9;</code>
     */
    protected $exchType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *          股票
     *     @type int|string $id
     *          股票ID
     *     @type int $lotSize
     *          每手数量,期权以及期货类型表示合约乘数
     *     @type int $secType
     *          Qot_Common.SecurityType,股票类型
     *     @type string $name
     *          股票名字
     *     @type string $listTime
     *          上市时间字符串
     *     @type bool $delisting
     *          是否退市
     *     @type float $listTimestamp
     *          上市时间戳
     *     @type int $exchType
     *          Qot_Common.ExchType,所属交易所
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     *股票ID
     *
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *股票ID
     *
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     *每手数量,期权以及期货类型表示合约乘数
     *
     * Generated from protobuf field <code>int32 lotSize = 3;</code>
     * @return int
     */
    public function getLotSize()
    {
        return $this->lotSize;
    }

    /**
     *每手数量,期权以及期货类型表示合约乘数
     *
     * Generated from protobuf field <code>int32 lotSize = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLotSize(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->lotSize = $var;

        return $this;
    }

    /**
     *Qot_Common.SecurityType,股票类型
     *
     * Generated from protobuf field <code>int32 secType = 4;</code>
     * @return int
     */
    public function getSecType()
    {
        return $this->secType;
    }

    /**
     *Qot_Common.SecurityType,股票类型
     *
     * Generated from protobuf field <code>int32 secType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSecType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->secType = $var;

        return $this;
    }

    /**
     *股票名字
     *
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *股票名字
     *
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     *上市时间字符串
     *
     * Generated from protobuf field <code>string listTime = 6;</code>
     * @return string
     */
    public function getListTime()
    {
        return $this->listTime;
    }

    /**
     *上市时间字符串
     *
     * Generated from protobuf field <code>string listTime = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setListTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->listTime = $var;

        return $this;
    }

    /**
     *是否退市
     *
     * Generated from protobuf field <code>bool delisting = 7;</code>
     * @return bool
     */
    public function getDelisting()
    {
        return $this->delisting;
    }

    /**
     *是否退市
     *
     * Generated from protobuf field <code>bool delisting = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setDelisting(bool $var)
    {
        $this->delisting = $var;

        return $this;
    }

    /**
     *上市时间戳
     *
     * Generated from protobuf field <code>double listTimestamp = 8;</code>
     * @return float
     */
    public function getListTimestamp()
    {
        return $this->listTimestamp;
    }

    /**
     *上市时间戳
     *
     * Generated from protobuf field <code>double listTimestamp = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setListTimestamp(float $var)
    {
        $this->listTimestamp = $var;

        return $this;
    }

    /**
     *Qot_Common.ExchType,所属交易所
     *
     * Generated from protobuf field <code>int32 exchType = 9;</code>
     * @return int
     */
    public function getExchType()
    {
        return $this->exchType;
    }

    /**
     *Qot_Common.ExchType,所属交易所
     *
     * Generated from protobuf field <code>int32 exchType = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setExchType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->exchType = $var;

        return $this;
    }

}

