<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *持股变动
 *
 * Generated from protobuf message <code>Qot_Common.ShareHoldingChange</code>
 */
class ShareHoldingChange extends \Google\Protobuf\Internal\Message
{
    /**
     *持有者名称（机构名称 或 基金名称 或 高管姓名）
     *
     * Generated from protobuf field <code>string holderName = 1;</code>
     */
    protected $holderName = '';
    /**
     *当前持股数量
     *
     * Generated from protobuf field <code>double holdingQty = 2;</code>
     */
    protected $holdingQty = 0.0;
    /**
     *当前持股百分比（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double holdingRatio = 3;</code>
     */
    protected $holdingRatio = 0.0;
    /**
     *较上一次变动数量
     *
     * Generated from protobuf field <code>double changeQty = 4;</code>
     */
    protected $changeQty = 0.0;
    /**
     *较上一次变动百分比（该字段为百分比字段，默认不展示%，如20实际对应20%。是相对于自身的比例，而不是总的。如总股本1万股，持有100股，持股百分比是1%，卖掉50股，变动比例是50%，而不是0.5%）
     *
     * Generated from protobuf field <code>double changeRatio = 5;</code>
     */
    protected $changeRatio = 0.0;
    /**
     *发布时间(YYYY-MM-DD HH:MM:SS字符串)
     *
     * Generated from protobuf field <code>string time = 6;</code>
     */
    protected $time = '';
    /**
     *时间戳
     *
     * Generated from protobuf field <code>double timestamp = 7;</code>
     */
    protected $timestamp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $holderName
     *          持有者名称（机构名称 或 基金名称 或 高管姓名）
     *     @type float $holdingQty
     *          当前持股数量
     *     @type float $holdingRatio
     *          当前持股百分比（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *     @type float $changeQty
     *          较上一次变动数量
     *     @type float $changeRatio
     *          较上一次变动百分比（该字段为百分比字段，默认不展示%，如20实际对应20%。是相对于自身的比例，而不是总的。如总股本1万股，持有100股，持股百分比是1%，卖掉50股，变动比例是50%，而不是0.5%）
     *     @type string $time
     *          发布时间(YYYY-MM-DD HH:MM:SS字符串)
     *     @type float $timestamp
     *          时间戳
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *持有者名称（机构名称 或 基金名称 或 高管姓名）
     *
     * Generated from protobuf field <code>string holderName = 1;</code>
     * @return string
     */
    public function getHolderName()
    {
        return $this->holderName;
    }

    /**
     *持有者名称（机构名称 或 基金名称 或 高管姓名）
     *
     * Generated from protobuf field <code>string holderName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHolderName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->holderName = $var;

        return $this;
    }

    /**
     *当前持股数量
     *
     * Generated from protobuf field <code>double holdingQty = 2;</code>
     * @return float
     */
    public function getHoldingQty()
    {
        return $this->holdingQty;
    }

    /**
     *当前持股数量
     *
     * Generated from protobuf field <code>double holdingQty = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setHoldingQty(float $var)
    {
        $this->holdingQty = $var;

        return $this;
    }

    /**
     *当前持股百分比（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double holdingRatio = 3;</code>
     * @return float
     */
    public function getHoldingRatio()
    {
        return $this->holdingRatio;
    }

    /**
     *当前持股百分比（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double holdingRatio = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setHoldingRatio(float $var)
    {
        $this->holdingRatio = $var;

        return $this;
    }

    /**
     *较上一次变动数量
     *
     * Generated from protobuf field <code>double changeQty = 4;</code>
     * @return float
     */
    public function getChangeQty()
    {
        return $this->changeQty;
    }

    /**
     *较上一次变动数量
     *
     * Generated from protobuf field <code>double changeQty = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setChangeQty(float $var)
    {
        $this->changeQty = $var;

        return $this;
    }

    /**
     *较上一次变动百分比（该字段为百分比字段，默认不展示%，如20实际对应20%。是相对于自身的比例，而不是总的。如总股本1万股，持有100股，持股百分比是1%，卖掉50股，变动比例是50%，而不是0.5%）
     *
     * Generated from protobuf field <code>double changeRatio = 5;</code>
     * @return float
     */
    public function getChangeRatio()
    {
        return $this->changeRatio;
    }

    /**
     *较上一次变动百分比（该字段为百分比字段，默认不展示%，如20实际对应20%。是相对于自身的比例，而不是总的。如总股本1万股，持有100股，持股百分比是1%，卖掉50股，变动比例是50%，而不是0.5%）
     *
     * Generated from protobuf field <code>double changeRatio = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setChangeRatio(float $var)
    {
        $this->changeRatio = $var;

        return $this;
    }

    /**
     *发布时间(YYYY-MM-DD HH:MM:SS字符串)
     *
     * Generated from protobuf field <code>string time = 6;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *发布时间(YYYY-MM-DD HH:MM:SS字符串)
     *
     * Generated from protobuf field <code>string time = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->time = $var;

        return $this;
    }

    /**
     *时间戳
     *
     * Generated from protobuf field <code>double timestamp = 7;</code>
     * @return float
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     *时间戳
     *
     * Generated from protobuf field <code>double timestamp = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setTimestamp(float $var)
    {
        $this->timestamp = $var;

        return $this;
    }

}

