<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_Common.SubInfo</code>
 */
class SubInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *Qot_Common.SubType,订阅类型
     *
     * Generated from protobuf field <code>int32 subType = 1;</code>
     */
    protected $subType = 0;
    /**
     *订阅该类型行情的股票
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Security securityList = 2;</code>
     */
    private $securityList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $subType
     *          Qot_Common.SubType,订阅类型
     *     @type \Futu\Qot_Common\Security[] $securityList
     *          订阅该类型行情的股票
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *Qot_Common.SubType,订阅类型
     *
     * Generated from protobuf field <code>int32 subType = 1;</code>
     * @return int
     */
    public function getSubType()
    {
        return $this->subType;
    }

    /**
     *Qot_Common.SubType,订阅类型
     *
     * Generated from protobuf field <code>int32 subType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSubType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->subType = $var;

        return $this;
    }

    /**
     *订阅该类型行情的股票
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Security securityList = 2;</code>
     * @return RepeatedField<\Futu\Qot_Common\Security>
     */
    public function getSecurityList()
    {
        return $this->securityList;
    }

    /**
     *订阅该类型行情的股票
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Security securityList = 2;</code>
     * @param \Futu\Qot_Common\Security[] $var
     * @return $this
     */
    public function setSecurityList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\Security::class);
        $this->securityList = $arr;

        return $this;
    }

}

