<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_Common.proto

namespace Futu\Qot_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_Common.WarrantBasicQotExData</code>
 */
class WarrantBasicQotExData extends \Google\Protobuf\Internal\Message
{
    /**
     *对冲值,仅认购认沽支持该字段
     *
     * Generated from protobuf field <code>double delta = 1;</code>
     */
    protected $delta = 0.0;
    /**
     *引申波幅,仅认购认沽支持该字段
     *
     * Generated from protobuf field <code>double impliedVolatility = 2;</code>
     */
    protected $impliedVolatility = 0.0;
    /**
     *溢价（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double premium = 3;</code>
     */
    protected $premium = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $delta
     *          对冲值,仅认购认沽支持该字段
     *     @type float $impliedVolatility
     *          引申波幅,仅认购认沽支持该字段
     *     @type float $premium
     *          溢价（该字段为百分比字段，默认不展示%，如20实际对应20%）
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *对冲值,仅认购认沽支持该字段
     *
     * Generated from protobuf field <code>double delta = 1;</code>
     * @return float
     */
    public function getDelta()
    {
        return $this->delta;
    }

    /**
     *对冲值,仅认购认沽支持该字段
     *
     * Generated from protobuf field <code>double delta = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDelta(float $var)
    {
        $this->delta = $var;

        return $this;
    }

    /**
     *引申波幅,仅认购认沽支持该字段
     *
     * Generated from protobuf field <code>double impliedVolatility = 2;</code>
     * @return float
     */
    public function getImpliedVolatility()
    {
        return $this->impliedVolatility;
    }

    /**
     *引申波幅,仅认购认沽支持该字段
     *
     * Generated from protobuf field <code>double impliedVolatility = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setImpliedVolatility(float $var)
    {
        $this->impliedVolatility = $var;

        return $this;
    }

    /**
     *溢价（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double premium = 3;</code>
     * @return float
     */
    public function getPremium()
    {
        return $this->premium;
    }

    /**
     *溢价（该字段为百分比字段，默认不展示%，如20实际对应20%）
     *
     * Generated from protobuf field <code>double premium = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPremium(float $var)
    {
        $this->premium = $var;

        return $this;
    }

}

