<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_UnlockTrade.proto

namespace Futu\Trd_UnlockTrade\pb;

class TrdUnlockTrade
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB6\x02\x0A\x15Trd_UnlockTrade.proto\x12\x0FTrd_UnlockTrade\";\x0A\x03C2S\x12\x0E\x0A\x06unlock\x18\x01 \x01(\x08\x12\x0E\x0A\x06pwdMD5\x18\x02 \x01(\x09\x12\x14\x0A\x0CsecurityFirm\x18\x03 \x01(\x05\"\x05\x0A\x03S2C\",\x0A\x07Request\x12!\x0A\x03c2s\x18\x01 \x01(\x0B2\x14.Trd_UnlockTrade.C2S\"_\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12!\x0A\x03s2c\x18\x04 \x01(\x0B2\x14.Trd_UnlockTrade.S2CB1\xCA\x02\x14Futu\\Trd_UnlockTrade\xE2\x02\x17Futu\\Trd_UnlockTrade\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

