<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetKL.proto

namespace Futu\Qot_GetKL\pb;

class QotGetKL
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x90\x03\x0A\x0FQot_GetKL.proto\x12\x09Qot_GetKL\"`\x0A\x03C2S\x12\x11\x0A\x09rehabType\x18\x01 \x01(\x05\x12\x0E\x0A\x06klType\x18\x02 \x01(\x05\x12&\x0A\x08security\x18\x03 \x01(\x0B2\x14.Qot_Common.Security\x12\x0E\x0A\x06reqNum\x18\x04 \x01(\x05\"^\x0A\x03S2C\x12&\x0A\x08security\x18\x01 \x01(\x0B2\x14.Qot_Common.Security\x12\x0C\x0A\x04name\x18\x03 \x01(\x09\x12!\x0A\x06klList\x18\x02 \x03(\x0B2\x11.Qot_Common.KLine\"&\x0A\x07Request\x12\x1B\x0A\x03c2s\x18\x01 \x01(\x0B2\x0E.Qot_GetKL.C2S\"Y\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12\x1B\x0A\x03s2c\x18\x04 \x01(\x0B2\x0E.Qot_GetKL.S2CB%\xCA\x02\x0EFutu\\Qot_GetKL\xE2\x02\x11Futu\\Qot_GetKL\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

