<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetHistoryOrderFillList.proto

namespace Futu\Trd_GetHistoryOrderFillList\pb;

class TrdGetHistoryOrderFillList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xFF\x03\x0A!Trd_GetHistoryOrderFillList.proto\x12\x1BTrd_GetHistoryOrderFillList\"g\x0A\x03C2S\x12%\x0A\x06header\x18\x01 \x01(\x0B2\x15.Trd_Common.TrdHeader\x129\x0A\x10filterConditions\x18\x02 \x01(\x0B2\x1F.Trd_Common.TrdFilterConditions\"Z\x0A\x03S2C\x12%\x0A\x06header\x18\x01 \x01(\x0B2\x15.Trd_Common.TrdHeader\x12,\x0A\x0DorderFillList\x18\x02 \x03(\x0B2\x15.Trd_Common.OrderFill\"8\x0A\x07Request\x12-\x0A\x03c2s\x18\x01 \x01(\x0B2 .Trd_GetHistoryOrderFillList.C2S\"k\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12-\x0A\x03s2c\x18\x04 \x01(\x0B2 .Trd_GetHistoryOrderFillList.S2CBI\xCA\x02 Futu\\Trd_GetHistoryOrderFillList\xE2\x02#Futu\\Trd_GetHistoryOrderFillList\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

