<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetTicker.proto

namespace Futu\Qot_GetTicker;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetTicker.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;
    /**
     *最多返回的逐笔个数,实际返回数量不一定会返回这么多,最多返回1000个
     *
     * Generated from protobuf field <code>int32 maxRetNum = 2;</code>
     */
    protected $maxRetNum = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *          股票
     *     @type int $maxRetNum
     *          最多返回的逐笔个数,实际返回数量不一定会返回这么多,最多返回1000个
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetTicker\pb\QotGetTicker::initOnce();
        parent::__construct($data);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     *最多返回的逐笔个数,实际返回数量不一定会返回这么多,最多返回1000个
     *
     * Generated from protobuf field <code>int32 maxRetNum = 2;</code>
     * @return int
     */
    public function getMaxRetNum()
    {
        return $this->maxRetNum;
    }

    /**
     *最多返回的逐笔个数,实际返回数量不一定会返回这么多,最多返回1000个
     *
     * Generated from protobuf field <code>int32 maxRetNum = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRetNum(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->maxRetNum = $var;

        return $this;
    }

}

