<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_StockFilter.proto

namespace Futu\Qot_StockFilter;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * 累积属性筛选
 *
 * Generated from protobuf message <code>Qot_StockFilter.AccumulateFilter</code>
 */
class AccumulateFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * AccumulateField 累积属性
     *
     * Generated from protobuf field <code>int32 fieldName = 1;</code>
     */
    protected $fieldName = 0;
    /**
     * 区间下限（闭区间），不传代表下限为 -∞
     *
     * Generated from protobuf field <code>double filterMin = 2;</code>
     */
    protected $filterMin = 0.0;
    /**
     * 区间上限（闭区间），不传代表上限为 +∞
     *
     * Generated from protobuf field <code>double filterMax = 3;</code>
     */
    protected $filterMax = 0.0;
    /**
     * 该字段是否不需要筛选，True：不筛选，False：筛选。不传默认不筛选
     *
     * Generated from protobuf field <code>bool isNoFilter = 4;</code>
     */
    protected $isNoFilter = false;
    /**
     * SortDir 排序方向，默认不排序。
     *
     * Generated from protobuf field <code>int32 sortDir = 5;</code>
     */
    protected $sortDir = 0;
    /**
     * 近几日，累积时间
     *
     * Generated from protobuf field <code>int32 days = 6;</code>
     */
    protected $days = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $fieldName
     *           AccumulateField 累积属性
     *     @type float $filterMin
     *           区间下限（闭区间），不传代表下限为 -∞
     *     @type float $filterMax
     *           区间上限（闭区间），不传代表上限为 +∞
     *     @type bool $isNoFilter
     *           该字段是否不需要筛选，True：不筛选，False：筛选。不传默认不筛选
     *     @type int $sortDir
     *           SortDir 排序方向，默认不排序。
     *     @type int $days
     *           近几日，累积时间
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_StockFilter\pb\QotStockFilter::initOnce();
        parent::__construct($data);
    }

    /**
     * AccumulateField 累积属性
     *
     * Generated from protobuf field <code>int32 fieldName = 1;</code>
     * @return int
     */
    public function getFieldName()
    {
        return $this->fieldName;
    }

    /**
     * AccumulateField 累积属性
     *
     * Generated from protobuf field <code>int32 fieldName = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldName(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->fieldName = $var;

        return $this;
    }

    /**
     * 区间下限（闭区间），不传代表下限为 -∞
     *
     * Generated from protobuf field <code>double filterMin = 2;</code>
     * @return float
     */
    public function getFilterMin()
    {
        return $this->filterMin;
    }

    /**
     * 区间下限（闭区间），不传代表下限为 -∞
     *
     * Generated from protobuf field <code>double filterMin = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setFilterMin(float $var)
    {
        $this->filterMin = $var;

        return $this;
    }

    /**
     * 区间上限（闭区间），不传代表上限为 +∞
     *
     * Generated from protobuf field <code>double filterMax = 3;</code>
     * @return float
     */
    public function getFilterMax()
    {
        return $this->filterMax;
    }

    /**
     * 区间上限（闭区间），不传代表上限为 +∞
     *
     * Generated from protobuf field <code>double filterMax = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setFilterMax(float $var)
    {
        $this->filterMax = $var;

        return $this;
    }

    /**
     * 该字段是否不需要筛选，True：不筛选，False：筛选。不传默认不筛选
     *
     * Generated from protobuf field <code>bool isNoFilter = 4;</code>
     * @return bool
     */
    public function getIsNoFilter()
    {
        return $this->isNoFilter;
    }

    /**
     * 该字段是否不需要筛选，True：不筛选，False：筛选。不传默认不筛选
     *
     * Generated from protobuf field <code>bool isNoFilter = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNoFilter(bool $var)
    {
        $this->isNoFilter = $var;

        return $this;
    }

    /**
     * SortDir 排序方向，默认不排序。
     *
     * Generated from protobuf field <code>int32 sortDir = 5;</code>
     * @return int
     */
    public function getSortDir()
    {
        return $this->sortDir;
    }

    /**
     * SortDir 排序方向，默认不排序。
     *
     * Generated from protobuf field <code>int32 sortDir = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSortDir(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->sortDir = $var;

        return $this;
    }

    /**
     * 近几日，累积时间
     *
     * Generated from protobuf field <code>int32 days = 6;</code>
     * @return int
     */
    public function getDays()
    {
        return $this->days;
    }

    /**
     * 近几日，累积时间
     *
     * Generated from protobuf field <code>int32 days = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDays(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->days = $var;

        return $this;
    }

}

