<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_StockFilter.proto

namespace Futu\Qot_StockFilter;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * 简单属性数据
 *
 * Generated from protobuf message <code>Qot_StockFilter.BaseData</code>
 */
class BaseData extends \Google\Protobuf\Internal\Message
{
    /**
     * StockField 简单属性
     *
     * Generated from protobuf field <code>int32 fieldName = 1;</code>
     */
    protected $fieldName = 0;
    /**
     * Generated from protobuf field <code>double value = 2;</code>
     */
    protected $value = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $fieldName
     *           StockField 简单属性
     *     @type float $value
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_StockFilter\pb\QotStockFilter::initOnce();
        parent::__construct($data);
    }

    /**
     * StockField 简单属性
     *
     * Generated from protobuf field <code>int32 fieldName = 1;</code>
     * @return int
     */
    public function getFieldName()
    {
        return $this->fieldName;
    }

    /**
     * StockField 简单属性
     *
     * Generated from protobuf field <code>int32 fieldName = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldName(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->fieldName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double value = 2;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>double value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setValue(float $var)
    {
        $this->value = $var;

        return $this;
    }

}

