<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_StockFilter.proto

namespace Futu\Qot_StockFilter;

use UnexpectedValueException;

/**
 * 自定义技术指标属性
 *
 * Protobuf type <code>Qot_StockFilter.CustomIndicatorField</code>
 */
class CustomIndicatorField
{
    /**
     * 未知
     *
     * Generated from protobuf enum <code>CustomIndicatorField_Unknown = 0;</code>
     */
    const CustomIndicatorField_Unknown = 0;
    /**
     * 最新价格
     *
     * Generated from protobuf enum <code>CustomIndicatorField_Price = 1;</code>
     */
    const CustomIndicatorField_Price = 1;
    /**
     * 5日简单均线（不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MA5 = 2;</code>
     */
    const CustomIndicatorField_MA5 = 2;
    /**
     * 10日简单均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MA10 = 3;</code>
     */
    const CustomIndicatorField_MA10 = 3;
    /**
     * 20日简单均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MA20 = 4;</code>
     */
    const CustomIndicatorField_MA20 = 4;
    /**
     * 30日简单均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MA30 = 5;</code>
     */
    const CustomIndicatorField_MA30 = 5;
    /**
     * 60日简单均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MA60 = 6;</code>
     */
    const CustomIndicatorField_MA60 = 6;
    /**
     * 120日简单均线（不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MA120 = 7;</code>
     */
    const CustomIndicatorField_MA120 = 7;
    /**
     * 250日简单均线（不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MA250 = 8;</code>
     */
    const CustomIndicatorField_MA250 = 8;
    /**
     * RSI 指标参数的默认值为12
     *
     * Generated from protobuf enum <code>CustomIndicatorField_RSI = 9;</code>
     */
    const CustomIndicatorField_RSI = 9;
    /**
     * 5日指数移动均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_EMA5 = 10;</code>
     */
    const CustomIndicatorField_EMA5 = 10;
    /**
     * 10日指数移动均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_EMA10 = 11;</code>
     */
    const CustomIndicatorField_EMA10 = 11;
    /**
     * 20日指数移动均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_EMA20 = 12;</code>
     */
    const CustomIndicatorField_EMA20 = 12;
    /**
     * 30日指数移动均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_EMA30 = 13;</code>
     */
    const CustomIndicatorField_EMA30 = 13;
    /**
     * 60日指数移动均线 （不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_EMA60 = 14;</code>
     */
    const CustomIndicatorField_EMA60 = 14;
    /**
     * 120日指数移动均线（不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_EMA120 = 15;</code>
     */
    const CustomIndicatorField_EMA120 = 15;
    /**
     * 250日指数移动均线（不建议使用）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_EMA250 = 16;</code>
     */
    const CustomIndicatorField_EMA250 = 16;
    /**
     * 自定义数值（stock_field1 不支持此字段）
     *
     * Generated from protobuf enum <code>CustomIndicatorField_Value = 17;</code>
     */
    const CustomIndicatorField_Value = 17;
    /**
     * 简单均线
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MA = 30;</code>
     */
    const CustomIndicatorField_MA = 30;
    /**
     * 指数移动均线
     *
     * Generated from protobuf enum <code>CustomIndicatorField_EMA = 40;</code>
     */
    const CustomIndicatorField_EMA = 40;
    /**
     * KDJ 指标的 K 值。指标参数需要根据 KDJ 进行传参。不传则默认为 [9,3,3]
     *
     * Generated from protobuf enum <code>CustomIndicatorField_KDJ_K = 50;</code>
     */
    const CustomIndicatorField_KDJ_K = 50;
    /**
     * KDJ 指标的 D 值。指标参数需要根据 KDJ 进行传参。不传则默认为 [9,3,3]
     *
     * Generated from protobuf enum <code>CustomIndicatorField_KDJ_D = 51;</code>
     */
    const CustomIndicatorField_KDJ_D = 51;
    /**
     * KDJ 指标的 J 值。指标参数需要根据 KDJ 进行传参。不传则默认为 [9,3,3]	
     *
     * Generated from protobuf enum <code>CustomIndicatorField_KDJ_J = 52;</code>
     */
    const CustomIndicatorField_KDJ_J = 52;
    /**
     * MACD 指标的 DIFF 值。指标参数需要根据 MACD 进行传参。不传则默认为 [12,26,9]
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MACD_DIFF = 60;</code>
     */
    const CustomIndicatorField_MACD_DIFF = 60;
    /**
     * MACD 指标的 DEA 值。指标参数需要根据 MACD 进行传参。不传则默认为 [12,26,9]
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MACD_DEA = 61;</code>
     */
    const CustomIndicatorField_MACD_DEA = 61;
    /**
     * MACD 指标的 MACD 值。指标参数需要根据 MACD 进行传参。不传则默认为 [12,26,9]
     *
     * Generated from protobuf enum <code>CustomIndicatorField_MACD = 62;</code>
     */
    const CustomIndicatorField_MACD = 62;
    /**
     * BOLL 指标的 UPPER 值。指标参数需要根据 BOLL 进行传参。不传则默认为 [20,2]
     *
     * Generated from protobuf enum <code>CustomIndicatorField_BOLL_UPPER = 70;</code>
     */
    const CustomIndicatorField_BOLL_UPPER = 70;
    /**
     * BOLL 指标的 MIDDLER 值。指标参数需要根据 BOLL 进行传参。不传则默认为 [20,2]
     *
     * Generated from protobuf enum <code>CustomIndicatorField_BOLL_MIDDLER = 71;</code>
     */
    const CustomIndicatorField_BOLL_MIDDLER = 71;
    /**
     * BOLL 指标的 LOWER 值。指标参数需要根据 BOLL 进行传参。不传则默认为 [20,2]
     *
     * Generated from protobuf enum <code>CustomIndicatorField_BOLL_LOWER = 72;</code>
     */
    const CustomIndicatorField_BOLL_LOWER = 72;

    private static $valueToName = [
        self::CustomIndicatorField_Unknown => 'CustomIndicatorField_Unknown',
        self::CustomIndicatorField_Price => 'CustomIndicatorField_Price',
        self::CustomIndicatorField_MA5 => 'CustomIndicatorField_MA5',
        self::CustomIndicatorField_MA10 => 'CustomIndicatorField_MA10',
        self::CustomIndicatorField_MA20 => 'CustomIndicatorField_MA20',
        self::CustomIndicatorField_MA30 => 'CustomIndicatorField_MA30',
        self::CustomIndicatorField_MA60 => 'CustomIndicatorField_MA60',
        self::CustomIndicatorField_MA120 => 'CustomIndicatorField_MA120',
        self::CustomIndicatorField_MA250 => 'CustomIndicatorField_MA250',
        self::CustomIndicatorField_RSI => 'CustomIndicatorField_RSI',
        self::CustomIndicatorField_EMA5 => 'CustomIndicatorField_EMA5',
        self::CustomIndicatorField_EMA10 => 'CustomIndicatorField_EMA10',
        self::CustomIndicatorField_EMA20 => 'CustomIndicatorField_EMA20',
        self::CustomIndicatorField_EMA30 => 'CustomIndicatorField_EMA30',
        self::CustomIndicatorField_EMA60 => 'CustomIndicatorField_EMA60',
        self::CustomIndicatorField_EMA120 => 'CustomIndicatorField_EMA120',
        self::CustomIndicatorField_EMA250 => 'CustomIndicatorField_EMA250',
        self::CustomIndicatorField_Value => 'CustomIndicatorField_Value',
        self::CustomIndicatorField_MA => 'CustomIndicatorField_MA',
        self::CustomIndicatorField_EMA => 'CustomIndicatorField_EMA',
        self::CustomIndicatorField_KDJ_K => 'CustomIndicatorField_KDJ_K',
        self::CustomIndicatorField_KDJ_D => 'CustomIndicatorField_KDJ_D',
        self::CustomIndicatorField_KDJ_J => 'CustomIndicatorField_KDJ_J',
        self::CustomIndicatorField_MACD_DIFF => 'CustomIndicatorField_MACD_DIFF',
        self::CustomIndicatorField_MACD_DEA => 'CustomIndicatorField_MACD_DEA',
        self::CustomIndicatorField_MACD => 'CustomIndicatorField_MACD',
        self::CustomIndicatorField_BOLL_UPPER => 'CustomIndicatorField_BOLL_UPPER',
        self::CustomIndicatorField_BOLL_MIDDLER => 'CustomIndicatorField_BOLL_MIDDLER',
        self::CustomIndicatorField_BOLL_LOWER => 'CustomIndicatorField_BOLL_LOWER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

