<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_StockFilter.proto

namespace Futu\Qot_StockFilter;

use UnexpectedValueException;

/**
 * 财务时间周期
 *
 * Protobuf type <code>Qot_StockFilter.FinancialQuarter</code>
 */
class FinancialQuarter
{
    /**
     * 未知
     *
     * Generated from protobuf enum <code>FinancialQuarter_Unknown = 0;</code>
     */
    const FinancialQuarter_Unknown = 0;
    /**
     * 年报
     *
     * Generated from protobuf enum <code>FinancialQuarter_Annual = 1;</code>
     */
    const FinancialQuarter_Annual = 1;
    /**
     * 一季报
     *
     * Generated from protobuf enum <code>FinancialQuarter_FirstQuarter = 2;</code>
     */
    const FinancialQuarter_FirstQuarter = 2;
    /**
     * 中报
     *
     * Generated from protobuf enum <code>FinancialQuarter_Interim = 3;</code>
     */
    const FinancialQuarter_Interim = 3;
    /**
     * 三季报
     *
     * Generated from protobuf enum <code>FinancialQuarter_ThirdQuarter = 4;</code>
     */
    const FinancialQuarter_ThirdQuarter = 4;
    /**
     * 最近季报
     *
     * Generated from protobuf enum <code>FinancialQuarter_MostRecentQuarter = 5;</code>
     */
    const FinancialQuarter_MostRecentQuarter = 5;

    private static $valueToName = [
        self::FinancialQuarter_Unknown => 'FinancialQuarter_Unknown',
        self::FinancialQuarter_Annual => 'FinancialQuarter_Annual',
        self::FinancialQuarter_FirstQuarter => 'FinancialQuarter_FirstQuarter',
        self::FinancialQuarter_Interim => 'FinancialQuarter_Interim',
        self::FinancialQuarter_ThirdQuarter => 'FinancialQuarter_ThirdQuarter',
        self::FinancialQuarter_MostRecentQuarter => 'FinancialQuarter_MostRecentQuarter',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

