<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_StockFilter.proto

namespace Futu\Qot_StockFilter;

use UnexpectedValueException;

/**
 * 财务属性
 *
 * Protobuf type <code>Qot_StockFilter.FinancialField</code>
 */
class FinancialField
{
    /**
     * 基础财务属性
     *
     * Generated from protobuf enum <code>FinancialField_Unknown = 0;</code>
     */
    const FinancialField_Unknown = 0;
    /**
     * 净利润（精确到小数点后 3 位，超出部分会被舍弃）例如填写[100000000,2500000000]值区间
     *
     * Generated from protobuf enum <code>FinancialField_NetProfit = 1;</code>
     */
    const FinancialField_NetProfit = 1;
    /**
     * 净利润增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写[-10,300]值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_NetProfitGrowth = 2;</code>
     */
    const FinancialField_NetProfitGrowth = 2;
    /**
     * 营业收入（精确到小数点后 3 位，超出部分会被舍弃）例如填写[100000000,6400000000]值区间
     *
     * Generated from protobuf enum <code>FinancialField_SumOfBusiness = 3;</code>
     */
    const FinancialField_SumOfBusiness = 3;
    /**
     * 营收同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写[-5,200]值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_SumOfBusinessGrowth = 4;</code>
     */
    const FinancialField_SumOfBusinessGrowth = 4;
    /**
     * 净利率（精确到小数点后 3 位，超出部分会被舍弃）例如填写[10,113]值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_NetProfitRate = 5;</code>
     */
    const FinancialField_NetProfitRate = 5;
    /**
     * 毛利率（精确到小数点后 3 位，超出部分会被舍弃）例如填写[4,65]值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_GrossProfitRate = 6;</code>
     */
    const FinancialField_GrossProfitRate = 6;
    /**
     * 资产负债率（精确到小数点后 3 位，超出部分会被舍弃）例如填写[5,470]值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_DebtAssetsRate = 7;</code>
     */
    const FinancialField_DebtAssetsRate = 7;
    /**
     * 净资产收益率（精确到小数点后 3 位，超出部分会被舍弃）例如填写[20,230]值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_ReturnOnEquityRate = 8;</code>
     */
    const FinancialField_ReturnOnEquityRate = 8;
    /**
     * 盈利能力属性
     *
     * Generated from protobuf enum <code>FinancialField_ROIC = 9;</code>
     */
    const FinancialField_ROIC = 9;
    /**
     * 资产回报率 TTM（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。仅适用于年报。）
     *
     * Generated from protobuf enum <code>FinancialField_ROATTM = 10;</code>
     */
    const FinancialField_ROATTM = 10;
    /**
     * 息税前利润 TTM（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1000000000,1000000000] 值区间（单位：元。仅适用于年报。）
     *
     * Generated from protobuf enum <code>FinancialField_EBITTTM = 11;</code>
     */
    const FinancialField_EBITTTM = 11;
    /**
     * 税息折旧及摊销前利润（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1000000000,1000000000] 值区间（单位：元）
     *
     * Generated from protobuf enum <code>FinancialField_EBITDA = 12;</code>
     */
    const FinancialField_EBITDA = 12;
    /**
     * 营业利润率 TTM（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。仅适用于年报。）
     *
     * Generated from protobuf enum <code>FinancialField_OperatingMarginTTM = 13;</code>
     */
    const FinancialField_OperatingMarginTTM = 13;
    /**
     * EBIT利润率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_EBITMargin = 14;</code>
     */
    const FinancialField_EBITMargin = 14;
    /**
     * EBITDA利润率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_EBITDAMargin = 15;</code>
     */
    const FinancialField_EBITDAMargin = 15;
    /**
     * 财务成本率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_FinancialCostRate = 16;</code>
     */
    const FinancialField_FinancialCostRate = 16;
    /**
     * 营业利润 TTM（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1000000000,1000000000] 值区间 （单位：元。仅适用于年报。）
     *
     * Generated from protobuf enum <code>FinancialField_OperatingProfitTTM = 17;</code>
     */
    const FinancialField_OperatingProfitTTM = 17;
    /**
     * 归属于母公司的净利润（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1000000000,1000000000] 值区间 （单位：元。仅适用于年报。）
     *
     * Generated from protobuf enum <code>FinancialField_ShareholderNetProfitTTM = 18;</code>
     */
    const FinancialField_ShareholderNetProfitTTM = 18;
    /**
     * 盈利中的现金收入比例（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,60.0] 值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%。仅适用于年报。）
     *
     * Generated from protobuf enum <code>FinancialField_NetProfitCashCoverTTM = 19;</code>
     */
    const FinancialField_NetProfitCashCoverTTM = 19;
    /**
     * 偿债能力属性
     *
     * Generated from protobuf enum <code>FinancialField_CurrentRatio = 20;</code>
     */
    const FinancialField_CurrentRatio = 20;
    /**
     * 速动比率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [100,250] 值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）	
     *
     * Generated from protobuf enum <code>FinancialField_QuickRatio = 21;</code>
     */
    const FinancialField_QuickRatio = 21;
    /**
     * 清债能力属性
     *
     * Generated from protobuf enum <code>FinancialField_CurrentAssetRatio = 22;</code>
     */
    const FinancialField_CurrentAssetRatio = 22;
    /**
     * 流动负债率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [10,100] 值区间（该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_CurrentDebtRatio = 23;</code>
     */
    const FinancialField_CurrentDebtRatio = 23;
    /**
     * 权益乘数（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [100,180] 值区间
     *
     * Generated from protobuf enum <code>FinancialField_EquityMultiplier = 24;</code>
     */
    const FinancialField_EquityMultiplier = 24;
    /**
     * 产权比率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [50,100] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%） 
     *
     * Generated from protobuf enum <code>FinancialField_PropertyRatio = 25;</code>
     */
    const FinancialField_PropertyRatio = 25;
    /**
     * 现金和现金等价（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1000000000,1000000000] 值区间（单位：元）	
     *
     * Generated from protobuf enum <code>FinancialField_CashAndCashEquivalents = 26;</code>
     */
    const FinancialField_CashAndCashEquivalents = 26;
    /**
     * 运营能力属性
     *
     * Generated from protobuf enum <code>FinancialField_TotalAssetTurnover = 27;</code>
     */
    const FinancialField_TotalAssetTurnover = 27;
    /**
     * 固定资产周转率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [50,100] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_FixedAssetTurnover = 28;</code>
     */
    const FinancialField_FixedAssetTurnover = 28;
    /**
     * 存货周转率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [50,100] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_InventoryTurnover = 29;</code>
     */
    const FinancialField_InventoryTurnover = 29;
    /**
     * 经营活动现金流 TTM（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1000000000,1000000000] 值区间（单位：元。仅适用于年报。）
     *
     * Generated from protobuf enum <code>FinancialField_OperatingCashFlowTTM = 30;</code>
     */
    const FinancialField_OperatingCashFlowTTM = 30;
    /**
     * 应收账款净额（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1000000000,1000000000] 值区间 例如填写 [1000000000,1000000000] 值区间 （单位：元）	
     *
     * Generated from protobuf enum <code>FinancialField_AccountsReceivable = 31;</code>
     */
    const FinancialField_AccountsReceivable = 31;
    /**
     * 成长能力属性
     *
     * Generated from protobuf enum <code>FinancialField_EBITGrowthRate = 32;</code>
     */
    const FinancialField_EBITGrowthRate = 32;
    /**
     * 营业利润同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_OperatingProfitGrowthRate = 33;</code>
     */
    const FinancialField_OperatingProfitGrowthRate = 33;
    /**
     * 总资产同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_TotalAssetsGrowthRate = 34;</code>
     */
    const FinancialField_TotalAssetsGrowthRate = 34;
    /**
     * 归母净利润同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_ProfitToShareholdersGrowthRate = 35;</code>
     */
    const FinancialField_ProfitToShareholdersGrowthRate = 35;
    /**
     * 总利润同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_ProfitBeforeTaxGrowthRate = 36;</code>
     */
    const FinancialField_ProfitBeforeTaxGrowthRate = 36;
    /**
     * EPS同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_EPSGrowthRate = 37;</code>
     */
    const FinancialField_EPSGrowthRate = 37;
    /**
     * ROE同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_ROEGrowthRate = 38;</code>
     */
    const FinancialField_ROEGrowthRate = 38;
    /**
     * ROIC同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_ROICGrowthRate = 39;</code>
     */
    const FinancialField_ROICGrowthRate = 39;
    /**
     * 经营现金流同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_NOCFGrowthRate = 40;</code>
     */
    const FinancialField_NOCFGrowthRate = 40;
    /**
     * 每股经营现金流同比增长率（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [1.0,10.0] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%）
     *
     * Generated from protobuf enum <code>FinancialField_NOCFPerShareGrowthRate = 41;</code>
     */
    const FinancialField_NOCFPerShareGrowthRate = 41;
    /**
     * 现金流属性
     *
     * Generated from protobuf enum <code>FinancialField_OperatingRevenueCashCover = 42;</code>
     */
    const FinancialField_OperatingRevenueCashCover = 42;
    /**
     * 营业利润占比（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [10,100] 值区间 （该字段为百分比字段，默认不展示 %，如 20 实际对应 20%） 	
     *
     * Generated from protobuf enum <code>FinancialField_OperatingProfitToTotalProfit = 43;</code>
     */
    const FinancialField_OperatingProfitToTotalProfit = 43;
    /**
     * 市场表现属性
     *
     * Generated from protobuf enum <code>FinancialField_BasicEPS = 44;</code>
     */
    const FinancialField_BasicEPS = 44;
    /**
     * 稀释每股收益（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [0.1,10] 值区间 (单位：元)
     *
     * Generated from protobuf enum <code>FinancialField_DilutedEPS = 45;</code>
     */
    const FinancialField_DilutedEPS = 45;
    /**
     * 每股经营现金净流量（精确到小数点后 3 位，超出部分会被舍弃）例如填写 [0.1,10] 值区间 (单位：元)	
     *
     * Generated from protobuf enum <code>FinancialField_NOCFPerShare = 46;</code>
     */
    const FinancialField_NOCFPerShare = 46;

    private static $valueToName = [
        self::FinancialField_Unknown => 'FinancialField_Unknown',
        self::FinancialField_NetProfit => 'FinancialField_NetProfit',
        self::FinancialField_NetProfitGrowth => 'FinancialField_NetProfitGrowth',
        self::FinancialField_SumOfBusiness => 'FinancialField_SumOfBusiness',
        self::FinancialField_SumOfBusinessGrowth => 'FinancialField_SumOfBusinessGrowth',
        self::FinancialField_NetProfitRate => 'FinancialField_NetProfitRate',
        self::FinancialField_GrossProfitRate => 'FinancialField_GrossProfitRate',
        self::FinancialField_DebtAssetsRate => 'FinancialField_DebtAssetsRate',
        self::FinancialField_ReturnOnEquityRate => 'FinancialField_ReturnOnEquityRate',
        self::FinancialField_ROIC => 'FinancialField_ROIC',
        self::FinancialField_ROATTM => 'FinancialField_ROATTM',
        self::FinancialField_EBITTTM => 'FinancialField_EBITTTM',
        self::FinancialField_EBITDA => 'FinancialField_EBITDA',
        self::FinancialField_OperatingMarginTTM => 'FinancialField_OperatingMarginTTM',
        self::FinancialField_EBITMargin => 'FinancialField_EBITMargin',
        self::FinancialField_EBITDAMargin => 'FinancialField_EBITDAMargin',
        self::FinancialField_FinancialCostRate => 'FinancialField_FinancialCostRate',
        self::FinancialField_OperatingProfitTTM => 'FinancialField_OperatingProfitTTM',
        self::FinancialField_ShareholderNetProfitTTM => 'FinancialField_ShareholderNetProfitTTM',
        self::FinancialField_NetProfitCashCoverTTM => 'FinancialField_NetProfitCashCoverTTM',
        self::FinancialField_CurrentRatio => 'FinancialField_CurrentRatio',
        self::FinancialField_QuickRatio => 'FinancialField_QuickRatio',
        self::FinancialField_CurrentAssetRatio => 'FinancialField_CurrentAssetRatio',
        self::FinancialField_CurrentDebtRatio => 'FinancialField_CurrentDebtRatio',
        self::FinancialField_EquityMultiplier => 'FinancialField_EquityMultiplier',
        self::FinancialField_PropertyRatio => 'FinancialField_PropertyRatio',
        self::FinancialField_CashAndCashEquivalents => 'FinancialField_CashAndCashEquivalents',
        self::FinancialField_TotalAssetTurnover => 'FinancialField_TotalAssetTurnover',
        self::FinancialField_FixedAssetTurnover => 'FinancialField_FixedAssetTurnover',
        self::FinancialField_InventoryTurnover => 'FinancialField_InventoryTurnover',
        self::FinancialField_OperatingCashFlowTTM => 'FinancialField_OperatingCashFlowTTM',
        self::FinancialField_AccountsReceivable => 'FinancialField_AccountsReceivable',
        self::FinancialField_EBITGrowthRate => 'FinancialField_EBITGrowthRate',
        self::FinancialField_OperatingProfitGrowthRate => 'FinancialField_OperatingProfitGrowthRate',
        self::FinancialField_TotalAssetsGrowthRate => 'FinancialField_TotalAssetsGrowthRate',
        self::FinancialField_ProfitToShareholdersGrowthRate => 'FinancialField_ProfitToShareholdersGrowthRate',
        self::FinancialField_ProfitBeforeTaxGrowthRate => 'FinancialField_ProfitBeforeTaxGrowthRate',
        self::FinancialField_EPSGrowthRate => 'FinancialField_EPSGrowthRate',
        self::FinancialField_ROEGrowthRate => 'FinancialField_ROEGrowthRate',
        self::FinancialField_ROICGrowthRate => 'FinancialField_ROICGrowthRate',
        self::FinancialField_NOCFGrowthRate => 'FinancialField_NOCFGrowthRate',
        self::FinancialField_NOCFPerShareGrowthRate => 'FinancialField_NOCFPerShareGrowthRate',
        self::FinancialField_OperatingRevenueCashCover => 'FinancialField_OperatingRevenueCashCover',
        self::FinancialField_OperatingProfitToTotalProfit => 'FinancialField_OperatingProfitToTotalProfit',
        self::FinancialField_BasicEPS => 'FinancialField_BasicEPS',
        self::FinancialField_DilutedEPS => 'FinancialField_DilutedEPS',
        self::FinancialField_NOCFPerShare => 'FinancialField_NOCFPerShare',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

