<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_StockFilter.proto

namespace Futu\Qot_StockFilter;

use UnexpectedValueException;

/**
 * 形态技术指标属性
 *
 * Protobuf type <code>Qot_StockFilter.PatternField</code>
 */
class PatternField
{
    /**
     * 未知
     *
     * Generated from protobuf enum <code>PatternField_Unknown = 0;</code>
     */
    const PatternField_Unknown = 0;
    /**
     * MA多头排列（连续两天MA5>MA10>MA20>MA30>MA60，且当日收盘价大于前一天收盘价）
     *
     * Generated from protobuf enum <code>PatternField_MAAlignmentLong = 1;</code>
     */
    const PatternField_MAAlignmentLong = 1;
    /**
     * MA空头排列（连续两天MA5 <MA10 <MA20 <MA30 <MA60，且当日收盘价小于前一天收盘价）
     *
     * Generated from protobuf enum <code>PatternField_MAAlignmentShort = 2;</code>
     */
    const PatternField_MAAlignmentShort = 2;
    /**
     * EMA多头排列（连续两天EMA5>EMA10>EMA20>EMA30>EMA60，且当日收盘价大于前一天收盘价）
     *
     * Generated from protobuf enum <code>PatternField_EMAAlignmentLong = 3;</code>
     */
    const PatternField_EMAAlignmentLong = 3;
    /**
     * EMA空头排列（连续两天EMA5 <EMA10 <EMA20 <EMA30 <EMA60，且当日收盘价小于前一天收盘价）
     *
     * Generated from protobuf enum <code>PatternField_EMAAlignmentShort = 4;</code>
     */
    const PatternField_EMAAlignmentShort = 4;
    /**
     * RSI低位金叉（50以下，短线RSI上穿长线RSI（前一日短线RSI小于长线RSI，当日短线RSI大于长线RSI）） 
     *
     * Generated from protobuf enum <code>PatternField_RSIGoldCrossLow = 5;</code>
     */
    const PatternField_RSIGoldCrossLow = 5;
    /**
     * RSI高位死叉（50以上，短线RSI下穿长线RSI（前一日短线RSI大于长线RSI，当日短线RSI小于长线RSI）） 
     *
     * Generated from protobuf enum <code>PatternField_RSIDeathCrossHigh = 6;</code>
     */
    const PatternField_RSIDeathCrossHigh = 6;
    /**
     * RSI顶背离（相邻的两个K线波峰，后面的波峰对应的CLOSE>前面的波峰对应的CLOSE，后面波峰的RSI12值 <前面波峰的RSI12值）
     *
     * Generated from protobuf enum <code>PatternField_RSITopDivergence = 7;</code>
     */
    const PatternField_RSITopDivergence = 7;
    /**
     * RSI底背离（相邻的两个K线波谷，后面的波谷对应的CLOSE <前面的波谷对应的CLOSE，后面波谷的RSI12值>前面波谷的RSI12值） 
     *
     * Generated from protobuf enum <code>PatternField_RSIBottomDivergence = 8;</code>
     */
    const PatternField_RSIBottomDivergence = 8;
    /**
     * KDJ低位金叉（KDJ的值都小于或等于30，且前一日K,J值分别小于D值，当日K,J值分别大于D值）
     *
     * Generated from protobuf enum <code>PatternField_KDJGoldCrossLow = 9;</code>
     */
    const PatternField_KDJGoldCrossLow = 9;
    /**
     * KDJ高位死叉（KDJ的值都大于或等于70，且前一日K,J值分别大于D值，当日K,J值分别小于D值）
     *
     * Generated from protobuf enum <code>PatternField_KDJDeathCrossHigh = 10;</code>
     */
    const PatternField_KDJDeathCrossHigh = 10;
    /**
     * KDJ顶背离（相邻的两个K线波峰，后面的波峰对应的CLOSE>前面的波峰对应的CLOSE，后面波峰的J值 <前面波峰的J值）
     *
     * Generated from protobuf enum <code>PatternField_KDJTopDivergence = 11;</code>
     */
    const PatternField_KDJTopDivergence = 11;
    /**
     * KDJ底背离（相邻的两个K线波谷，后面的波谷对应的CLOSE <前面的波谷对应的CLOSE，后面波谷的J值>前面波谷的J值）
     *
     * Generated from protobuf enum <code>PatternField_KDJBottomDivergence = 12;</code>
     */
    const PatternField_KDJBottomDivergence = 12;
    /**
     * MACD低位金叉（DIFF上穿DEA（前一日DIFF小于DEA，当日DIFF大于DEA））
     *
     * Generated from protobuf enum <code>PatternField_MACDGoldCrossLow = 13;</code>
     */
    const PatternField_MACDGoldCrossLow = 13;
    /**
     * MACD高位死叉（DIFF下穿DEA（前一日DIFF大于DEA，当日DIFF小于DEA））
     *
     * Generated from protobuf enum <code>PatternField_MACDDeathCrossHigh = 14;</code>
     */
    const PatternField_MACDDeathCrossHigh = 14;
    /**
     * MACD顶背离（相邻的两个K线波峰，后面的波峰对应的CLOSE>前面的波峰对应的CLOSE，后面波峰的macd值 <前面波峰的macd值）
     *
     * Generated from protobuf enum <code>PatternField_MACDTopDivergence = 15;</code>
     */
    const PatternField_MACDTopDivergence = 15;
    /**
     * MACD底背离（相邻的两个K线波谷，后面的波谷对应的CLOSE <前面的波谷对应的CLOSE，后面波谷的macd值>前面波谷的macd值）
     *
     * Generated from protobuf enum <code>PatternField_MACDBottomDivergence = 16;</code>
     */
    const PatternField_MACDBottomDivergence = 16;
    /**
     * BOLL突破上轨（前一日股价低于上轨值，当日股价大于上轨值） 
     *
     * Generated from protobuf enum <code>PatternField_BOLLBreakUpper = 17;</code>
     */
    const PatternField_BOLLBreakUpper = 17;
    /**
     * BOLL突破下轨（前一日股价高于下轨值，当日股价小于下轨值）
     *
     * Generated from protobuf enum <code>PatternField_BOLLLower = 18;</code>
     */
    const PatternField_BOLLLower = 18;
    /**
     * BOLL向上破中轨（前一日股价低于中轨值，当日股价大于中轨值）
     *
     * Generated from protobuf enum <code>PatternField_BOLLCrossMiddleUp = 19;</code>
     */
    const PatternField_BOLLCrossMiddleUp = 19;
    /**
     * BOLL向下破中轨（前一日股价大于中轨值，当日股价小于中轨值）
     *
     * Generated from protobuf enum <code>PatternField_BOLLCrossMiddleDown = 20;</code>
     */
    const PatternField_BOLLCrossMiddleDown = 20;

    private static $valueToName = [
        self::PatternField_Unknown => 'PatternField_Unknown',
        self::PatternField_MAAlignmentLong => 'PatternField_MAAlignmentLong',
        self::PatternField_MAAlignmentShort => 'PatternField_MAAlignmentShort',
        self::PatternField_EMAAlignmentLong => 'PatternField_EMAAlignmentLong',
        self::PatternField_EMAAlignmentShort => 'PatternField_EMAAlignmentShort',
        self::PatternField_RSIGoldCrossLow => 'PatternField_RSIGoldCrossLow',
        self::PatternField_RSIDeathCrossHigh => 'PatternField_RSIDeathCrossHigh',
        self::PatternField_RSITopDivergence => 'PatternField_RSITopDivergence',
        self::PatternField_RSIBottomDivergence => 'PatternField_RSIBottomDivergence',
        self::PatternField_KDJGoldCrossLow => 'PatternField_KDJGoldCrossLow',
        self::PatternField_KDJDeathCrossHigh => 'PatternField_KDJDeathCrossHigh',
        self::PatternField_KDJTopDivergence => 'PatternField_KDJTopDivergence',
        self::PatternField_KDJBottomDivergence => 'PatternField_KDJBottomDivergence',
        self::PatternField_MACDGoldCrossLow => 'PatternField_MACDGoldCrossLow',
        self::PatternField_MACDDeathCrossHigh => 'PatternField_MACDDeathCrossHigh',
        self::PatternField_MACDTopDivergence => 'PatternField_MACDTopDivergence',
        self::PatternField_MACDBottomDivergence => 'PatternField_MACDBottomDivergence',
        self::PatternField_BOLLBreakUpper => 'PatternField_BOLLBreakUpper',
        self::PatternField_BOLLLower => 'PatternField_BOLLLower',
        self::PatternField_BOLLCrossMiddleUp => 'PatternField_BOLLCrossMiddleUp',
        self::PatternField_BOLLCrossMiddleDown => 'PatternField_BOLLCrossMiddleDown',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

