<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_StockFilter.proto

namespace Futu\Qot_StockFilter;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * 返回的股票数据
 *
 * Generated from protobuf message <code>Qot_StockFilter.StockData</code>
 */
class StockData extends \Google\Protobuf\Internal\Message
{
    /**
     * 股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;
    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * 筛选后的简单指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.BaseData baseDataList = 3;</code>
     */
    private $baseDataList;
    /**
     * 筛选后的累积指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.AccumulateData accumulateDataList = 4;</code>
     */
    private $accumulateDataList;
    /**
     * 筛选后的财务指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.FinancialData financialDataList = 5;</code>
     */
    private $financialDataList;
    /**
     * 自定义技术指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.CustomIndicatorData customIndicatorDataList = 6;</code>
     */
    private $customIndicatorDataList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *           股票
     *     @type string $name
     *           股票名称
     *     @type \Futu\Qot_StockFilter\BaseData[] $baseDataList
     *           筛选后的简单指标属性数据
     *     @type \Futu\Qot_StockFilter\AccumulateData[] $accumulateDataList
     *           筛选后的累积指标属性数据
     *     @type \Futu\Qot_StockFilter\FinancialData[] $financialDataList
     *           筛选后的财务指标属性数据
     *     @type \Futu\Qot_StockFilter\CustomIndicatorData[] $customIndicatorDataList
     *           自定义技术指标属性数据
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_StockFilter\pb\QotStockFilter::initOnce();
        parent::__construct($data);
    }

    /**
     * 股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     * 股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * 筛选后的简单指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.BaseData baseDataList = 3;</code>
     * @return RepeatedField<\Futu\Qot_StockFilter\BaseData>
     */
    public function getBaseDataList()
    {
        return $this->baseDataList;
    }

    /**
     * 筛选后的简单指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.BaseData baseDataList = 3;</code>
     * @param \Futu\Qot_StockFilter\BaseData[] $var
     * @return $this
     */
    public function setBaseDataList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_StockFilter\BaseData::class);
        $this->baseDataList = $arr;

        return $this;
    }

    /**
     * 筛选后的累积指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.AccumulateData accumulateDataList = 4;</code>
     * @return RepeatedField<\Futu\Qot_StockFilter\AccumulateData>
     */
    public function getAccumulateDataList()
    {
        return $this->accumulateDataList;
    }

    /**
     * 筛选后的累积指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.AccumulateData accumulateDataList = 4;</code>
     * @param \Futu\Qot_StockFilter\AccumulateData[] $var
     * @return $this
     */
    public function setAccumulateDataList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_StockFilter\AccumulateData::class);
        $this->accumulateDataList = $arr;

        return $this;
    }

    /**
     * 筛选后的财务指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.FinancialData financialDataList = 5;</code>
     * @return RepeatedField<\Futu\Qot_StockFilter\FinancialData>
     */
    public function getFinancialDataList()
    {
        return $this->financialDataList;
    }

    /**
     * 筛选后的财务指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.FinancialData financialDataList = 5;</code>
     * @param \Futu\Qot_StockFilter\FinancialData[] $var
     * @return $this
     */
    public function setFinancialDataList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_StockFilter\FinancialData::class);
        $this->financialDataList = $arr;

        return $this;
    }

    /**
     * 自定义技术指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.CustomIndicatorData customIndicatorDataList = 6;</code>
     * @return RepeatedField<\Futu\Qot_StockFilter\CustomIndicatorData>
     */
    public function getCustomIndicatorDataList()
    {
        return $this->customIndicatorDataList;
    }

    /**
     * 自定义技术指标属性数据
     *
     * Generated from protobuf field <code>repeated .Qot_StockFilter.CustomIndicatorData customIndicatorDataList = 6;</code>
     * @param \Futu\Qot_StockFilter\CustomIndicatorData[] $var
     * @return $this
     */
    public function setCustomIndicatorDataList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_StockFilter\CustomIndicatorData::class);
        $this->customIndicatorDataList = $arr;

        return $this;
    }

}

