<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetCapitalFlow.proto

namespace Futu\Qot_GetCapitalFlow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetCapitalFlow.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;
    /**
     * Qot_Common.PeriodType 周期类型
     *
     * Generated from protobuf field <code>int32 periodType = 2;</code>
     */
    protected $periodType = 0;
    /**
     * 开始时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>string beginTime = 3;</code>
     */
    protected $beginTime = '';
    /**
     * 结束时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>string endTime = 4;</code>
     */
    protected $endTime = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *          股票
     *     @type int $periodType
     *           Qot_Common.PeriodType 周期类型
     *     @type string $beginTime
     *           开始时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
     *     @type string $endTime
     *           结束时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetCapitalFlow\pb\QotGetCapitalFlow::initOnce();
        parent::__construct($data);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     * Qot_Common.PeriodType 周期类型
     *
     * Generated from protobuf field <code>int32 periodType = 2;</code>
     * @return int
     */
    public function getPeriodType()
    {
        return $this->periodType;
    }

    /**
     * Qot_Common.PeriodType 周期类型
     *
     * Generated from protobuf field <code>int32 periodType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPeriodType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->periodType = $var;

        return $this;
    }

    /**
     * 开始时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>string beginTime = 3;</code>
     * @return string
     */
    public function getBeginTime()
    {
        return $this->beginTime;
    }

    /**
     * 开始时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>string beginTime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBeginTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->beginTime = $var;

        return $this;
    }

    /**
     * 结束时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>string endTime = 4;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     * 结束时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>string endTime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endTime = $var;

        return $this;
    }

}

