<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetCapitalFlow.proto

namespace Futu\Qot_GetCapitalFlow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetCapitalFlow.CapitalFlowItem</code>
 */
class CapitalFlowItem extends \Google\Protobuf\Internal\Message
{
    /**
     * 整体净流入
     *
     * Generated from protobuf field <code>double inFlow = 1;</code>
     */
    protected $inFlow = 0.0;
    /**
     *开始时间字符串,以分钟为单位
     *
     * Generated from protobuf field <code>string time = 2;</code>
     */
    protected $time = '';
    /**
     *开始时间戳
     *
     * Generated from protobuf field <code>double timestamp = 3;</code>
     */
    protected $timestamp = 0.0;
    /**
     * 主力大单净流入，仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>double mainInFlow = 4;</code>
     */
    protected $mainInFlow = 0.0;
    /**
     * 特大单净流入
     *
     * Generated from protobuf field <code>double superInFlow = 5;</code>
     */
    protected $superInFlow = 0.0;
    /**
     * 大单净流入
     *
     * Generated from protobuf field <code>double bigInFlow = 6;</code>
     */
    protected $bigInFlow = 0.0;
    /**
     * 中单净流入
     *
     * Generated from protobuf field <code>double midInFlow = 7;</code>
     */
    protected $midInFlow = 0.0;
    /**
     * 小单净流入
     *
     * Generated from protobuf field <code>double smlInFlow = 8;</code>
     */
    protected $smlInFlow = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $inFlow
     *           整体净流入
     *     @type string $time
     *          开始时间字符串,以分钟为单位
     *     @type float $timestamp
     *          开始时间戳
     *     @type float $mainInFlow
     *           主力大单净流入，仅周期类型不为实时有效
     *     @type float $superInFlow
     *           特大单净流入
     *     @type float $bigInFlow
     *           大单净流入
     *     @type float $midInFlow
     *           中单净流入
     *     @type float $smlInFlow
     *           小单净流入
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetCapitalFlow\pb\QotGetCapitalFlow::initOnce();
        parent::__construct($data);
    }

    /**
     * 整体净流入
     *
     * Generated from protobuf field <code>double inFlow = 1;</code>
     * @return float
     */
    public function getInFlow()
    {
        return $this->inFlow;
    }

    /**
     * 整体净流入
     *
     * Generated from protobuf field <code>double inFlow = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setInFlow(float $var)
    {
        $this->inFlow = $var;

        return $this;
    }

    /**
     *开始时间字符串,以分钟为单位
     *
     * Generated from protobuf field <code>string time = 2;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *开始时间字符串,以分钟为单位
     *
     * Generated from protobuf field <code>string time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->time = $var;

        return $this;
    }

    /**
     *开始时间戳
     *
     * Generated from protobuf field <code>double timestamp = 3;</code>
     * @return float
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     *开始时间戳
     *
     * Generated from protobuf field <code>double timestamp = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTimestamp(float $var)
    {
        $this->timestamp = $var;

        return $this;
    }

    /**
     * 主力大单净流入，仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>double mainInFlow = 4;</code>
     * @return float
     */
    public function getMainInFlow()
    {
        return $this->mainInFlow;
    }

    /**
     * 主力大单净流入，仅周期类型不为实时有效
     *
     * Generated from protobuf field <code>double mainInFlow = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setMainInFlow(float $var)
    {
        $this->mainInFlow = $var;

        return $this;
    }

    /**
     * 特大单净流入
     *
     * Generated from protobuf field <code>double superInFlow = 5;</code>
     * @return float
     */
    public function getSuperInFlow()
    {
        return $this->superInFlow;
    }

    /**
     * 特大单净流入
     *
     * Generated from protobuf field <code>double superInFlow = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setSuperInFlow(float $var)
    {
        $this->superInFlow = $var;

        return $this;
    }

    /**
     * 大单净流入
     *
     * Generated from protobuf field <code>double bigInFlow = 6;</code>
     * @return float
     */
    public function getBigInFlow()
    {
        return $this->bigInFlow;
    }

    /**
     * 大单净流入
     *
     * Generated from protobuf field <code>double bigInFlow = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setBigInFlow(float $var)
    {
        $this->bigInFlow = $var;

        return $this;
    }

    /**
     * 中单净流入
     *
     * Generated from protobuf field <code>double midInFlow = 7;</code>
     * @return float
     */
    public function getMidInFlow()
    {
        return $this->midInFlow;
    }

    /**
     * 中单净流入
     *
     * Generated from protobuf field <code>double midInFlow = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setMidInFlow(float $var)
    {
        $this->midInFlow = $var;

        return $this;
    }

    /**
     * 小单净流入
     *
     * Generated from protobuf field <code>double smlInFlow = 8;</code>
     * @return float
     */
    public function getSmlInFlow()
    {
        return $this->smlInFlow;
    }

    /**
     * 小单净流入
     *
     * Generated from protobuf field <code>double smlInFlow = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setSmlInFlow(float $var)
    {
        $this->smlInFlow = $var;

        return $this;
    }

}

