<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetIpoList.proto

namespace Futu\Qot_GetIpoList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Ipo基本数据
 *
 * Generated from protobuf message <code>Qot_GetIpoList.BasicIpoData</code>
 */
class BasicIpoData extends \Google\Protobuf\Internal\Message
{
    /**
     * Qot_Common::QotMarket 股票市场，支持港股、美股和 A股。其中，A 股整体返回，不区分沪股和深股。
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;
    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * 上市日期字符串
     *
     * Generated from protobuf field <code>string listTime = 3;</code>
     */
    protected $listTime = '';
    /**
     * 上市日期时间戳
     *
     * Generated from protobuf field <code>double listTimestamp = 4;</code>
     */
    protected $listTimestamp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *           Qot_Common::QotMarket 股票市场，支持港股、美股和 A股。其中，A 股整体返回，不区分沪股和深股。
     *     @type string $name
     *           股票名称
     *     @type string $listTime
     *           上市日期字符串
     *     @type float $listTimestamp
     *           上市日期时间戳
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetIpoList\pb\QotGetIpoList::initOnce();
        parent::__construct($data);
    }

    /**
     * Qot_Common::QotMarket 股票市场，支持港股、美股和 A股。其中，A 股整体返回，不区分沪股和深股。
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     * Qot_Common::QotMarket 股票市场，支持港股、美股和 A股。其中，A 股整体返回，不区分沪股和深股。
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * 上市日期字符串
     *
     * Generated from protobuf field <code>string listTime = 3;</code>
     * @return string
     */
    public function getListTime()
    {
        return $this->listTime;
    }

    /**
     * 上市日期字符串
     *
     * Generated from protobuf field <code>string listTime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setListTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->listTime = $var;

        return $this;
    }

    /**
     * 上市日期时间戳
     *
     * Generated from protobuf field <code>double listTimestamp = 4;</code>
     * @return float
     */
    public function getListTimestamp()
    {
        return $this->listTimestamp;
    }

    /**
     * 上市日期时间戳
     *
     * Generated from protobuf field <code>double listTimestamp = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setListTimestamp(float $var)
    {
        $this->listTimestamp = $var;

        return $this;
    }

}

