<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetIpoList.proto

namespace Futu\Qot_GetIpoList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A股Ipo列表额外数据
 *
 * Generated from protobuf message <code>Qot_GetIpoList.CNIpoExData</code>
 */
class CNIpoExData extends \Google\Protobuf\Internal\Message
{
    /**
     * 申购代码
     *
     * Generated from protobuf field <code>string applyCode = 1;</code>
     */
    protected $applyCode = '';
    /**
     * 发行总数
     *
     * Generated from protobuf field <code>int64 issueSize = 2;</code>
     */
    protected $issueSize = 0;
    /**
     * 网上发行量
     *
     * Generated from protobuf field <code>int64 onlineIssueSize = 3;</code>
     */
    protected $onlineIssueSize = 0;
    /**
     * 申购上限
     *
     * Generated from protobuf field <code>int64 applyUpperLimit = 4;</code>
     */
    protected $applyUpperLimit = 0;
    /**
     * 顶格申购需配市值
     *
     * Generated from protobuf field <code>int64 applyLimitMarketValue = 5;</code>
     */
    protected $applyLimitMarketValue = 0;
    /**
     * 是否预估发行价
     *
     * Generated from protobuf field <code>bool isEstimateIpoPrice = 6;</code>
     */
    protected $isEstimateIpoPrice = false;
    /**
     * 发行价 预估值会因为募集资金、发行数量、发行费用等数据变动而变动，仅供参考。实际数据公布后会第一时间更新。
     *
     * Generated from protobuf field <code>double ipoPrice = 7;</code>
     */
    protected $ipoPrice = 0.0;
    /**
     * 行业市盈率
     *
     * Generated from protobuf field <code>double industryPeRate = 8;</code>
     */
    protected $industryPeRate = 0.0;
    /**
     * 是否预估中签率
     *
     * Generated from protobuf field <code>bool isEstimateWinningRatio = 9;</code>
     */
    protected $isEstimateWinningRatio = false;
    /**
     * 中签率 该字段为百分比字段，默认不展示%，如20实际对应20%。预估值会因为募集资金、发行数量、发行费用等数据变动而变动，仅供参考。实际数据公布后会第一时间更新。
     *
     * Generated from protobuf field <code>double winningRatio = 10;</code>
     */
    protected $winningRatio = 0.0;
    /**
     * 发行市盈率
     *
     * Generated from protobuf field <code>double issuePeRate = 11;</code>
     */
    protected $issuePeRate = 0.0;
    /**
     * 申购日期字符串
     *
     * Generated from protobuf field <code>string applyTime = 12;</code>
     */
    protected $applyTime = '';
    /**
     * 申购日期时间戳
     *
     * Generated from protobuf field <code>double applyTimestamp = 13;</code>
     */
    protected $applyTimestamp = 0.0;
    /**
     * 公布中签日期字符串
     *
     * Generated from protobuf field <code>string winningTime = 14;</code>
     */
    protected $winningTime = '';
    /**
     * 公布中签日期时间戳
     *
     * Generated from protobuf field <code>double winningTimestamp = 15;</code>
     */
    protected $winningTimestamp = 0.0;
    /**
     * 是否已经公布中签号
     *
     * Generated from protobuf field <code>bool isHasWon = 16;</code>
     */
    protected $isHasWon = false;
    /**
     * Qot_GetIpoList::WinningNumData 中签号数据，对应PC中"公布中签日期的已公布"
     *
     * Generated from protobuf field <code>repeated .Qot_GetIpoList.WinningNumData winningNumData = 17;</code>
     */
    private $winningNumData;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $applyCode
     *           申购代码
     *     @type int|string $issueSize
     *           发行总数
     *     @type int|string $onlineIssueSize
     *           网上发行量
     *     @type int|string $applyUpperLimit
     *           申购上限
     *     @type int|string $applyLimitMarketValue
     *           顶格申购需配市值
     *     @type bool $isEstimateIpoPrice
     *           是否预估发行价
     *     @type float $ipoPrice
     *           发行价 预估值会因为募集资金、发行数量、发行费用等数据变动而变动，仅供参考。实际数据公布后会第一时间更新。
     *     @type float $industryPeRate
     *           行业市盈率
     *     @type bool $isEstimateWinningRatio
     *           是否预估中签率
     *     @type float $winningRatio
     *           中签率 该字段为百分比字段，默认不展示%，如20实际对应20%。预估值会因为募集资金、发行数量、发行费用等数据变动而变动，仅供参考。实际数据公布后会第一时间更新。
     *     @type float $issuePeRate
     *           发行市盈率
     *     @type string $applyTime
     *           申购日期字符串
     *     @type float $applyTimestamp
     *           申购日期时间戳
     *     @type string $winningTime
     *           公布中签日期字符串
     *     @type float $winningTimestamp
     *           公布中签日期时间戳
     *     @type bool $isHasWon
     *           是否已经公布中签号
     *     @type \Futu\Qot_GetIpoList\WinningNumData[] $winningNumData
     *           Qot_GetIpoList::WinningNumData 中签号数据，对应PC中"公布中签日期的已公布"
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetIpoList\pb\QotGetIpoList::initOnce();
        parent::__construct($data);
    }

    /**
     * 申购代码
     *
     * Generated from protobuf field <code>string applyCode = 1;</code>
     * @return string
     */
    public function getApplyCode()
    {
        return $this->applyCode;
    }

    /**
     * 申购代码
     *
     * Generated from protobuf field <code>string applyCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApplyCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->applyCode = $var;

        return $this;
    }

    /**
     * 发行总数
     *
     * Generated from protobuf field <code>int64 issueSize = 2;</code>
     * @return int|string
     */
    public function getIssueSize()
    {
        return $this->issueSize;
    }

    /**
     * 发行总数
     *
     * Generated from protobuf field <code>int64 issueSize = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIssueSize(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->issueSize = $var;

        return $this;
    }

    /**
     * 网上发行量
     *
     * Generated from protobuf field <code>int64 onlineIssueSize = 3;</code>
     * @return int|string
     */
    public function getOnlineIssueSize()
    {
        return $this->onlineIssueSize;
    }

    /**
     * 网上发行量
     *
     * Generated from protobuf field <code>int64 onlineIssueSize = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOnlineIssueSize(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->onlineIssueSize = $var;

        return $this;
    }

    /**
     * 申购上限
     *
     * Generated from protobuf field <code>int64 applyUpperLimit = 4;</code>
     * @return int|string
     */
    public function getApplyUpperLimit()
    {
        return $this->applyUpperLimit;
    }

    /**
     * 申购上限
     *
     * Generated from protobuf field <code>int64 applyUpperLimit = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApplyUpperLimit(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->applyUpperLimit = $var;

        return $this;
    }

    /**
     * 顶格申购需配市值
     *
     * Generated from protobuf field <code>int64 applyLimitMarketValue = 5;</code>
     * @return int|string
     */
    public function getApplyLimitMarketValue()
    {
        return $this->applyLimitMarketValue;
    }

    /**
     * 顶格申购需配市值
     *
     * Generated from protobuf field <code>int64 applyLimitMarketValue = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApplyLimitMarketValue(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->applyLimitMarketValue = $var;

        return $this;
    }

    /**
     * 是否预估发行价
     *
     * Generated from protobuf field <code>bool isEstimateIpoPrice = 6;</code>
     * @return bool
     */
    public function getIsEstimateIpoPrice()
    {
        return $this->isEstimateIpoPrice;
    }

    /**
     * 是否预估发行价
     *
     * Generated from protobuf field <code>bool isEstimateIpoPrice = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEstimateIpoPrice(bool $var)
    {
        $this->isEstimateIpoPrice = $var;

        return $this;
    }

    /**
     * 发行价 预估值会因为募集资金、发行数量、发行费用等数据变动而变动，仅供参考。实际数据公布后会第一时间更新。
     *
     * Generated from protobuf field <code>double ipoPrice = 7;</code>
     * @return float
     */
    public function getIpoPrice()
    {
        return $this->ipoPrice;
    }

    /**
     * 发行价 预估值会因为募集资金、发行数量、发行费用等数据变动而变动，仅供参考。实际数据公布后会第一时间更新。
     *
     * Generated from protobuf field <code>double ipoPrice = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setIpoPrice(float $var)
    {
        $this->ipoPrice = $var;

        return $this;
    }

    /**
     * 行业市盈率
     *
     * Generated from protobuf field <code>double industryPeRate = 8;</code>
     * @return float
     */
    public function getIndustryPeRate()
    {
        return $this->industryPeRate;
    }

    /**
     * 行业市盈率
     *
     * Generated from protobuf field <code>double industryPeRate = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setIndustryPeRate(float $var)
    {
        $this->industryPeRate = $var;

        return $this;
    }

    /**
     * 是否预估中签率
     *
     * Generated from protobuf field <code>bool isEstimateWinningRatio = 9;</code>
     * @return bool
     */
    public function getIsEstimateWinningRatio()
    {
        return $this->isEstimateWinningRatio;
    }

    /**
     * 是否预估中签率
     *
     * Generated from protobuf field <code>bool isEstimateWinningRatio = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEstimateWinningRatio(bool $var)
    {
        $this->isEstimateWinningRatio = $var;

        return $this;
    }

    /**
     * 中签率 该字段为百分比字段，默认不展示%，如20实际对应20%。预估值会因为募集资金、发行数量、发行费用等数据变动而变动，仅供参考。实际数据公布后会第一时间更新。
     *
     * Generated from protobuf field <code>double winningRatio = 10;</code>
     * @return float
     */
    public function getWinningRatio()
    {
        return $this->winningRatio;
    }

    /**
     * 中签率 该字段为百分比字段，默认不展示%，如20实际对应20%。预估值会因为募集资金、发行数量、发行费用等数据变动而变动，仅供参考。实际数据公布后会第一时间更新。
     *
     * Generated from protobuf field <code>double winningRatio = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setWinningRatio(float $var)
    {
        $this->winningRatio = $var;

        return $this;
    }

    /**
     * 发行市盈率
     *
     * Generated from protobuf field <code>double issuePeRate = 11;</code>
     * @return float
     */
    public function getIssuePeRate()
    {
        return $this->issuePeRate;
    }

    /**
     * 发行市盈率
     *
     * Generated from protobuf field <code>double issuePeRate = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setIssuePeRate(float $var)
    {
        $this->issuePeRate = $var;

        return $this;
    }

    /**
     * 申购日期字符串
     *
     * Generated from protobuf field <code>string applyTime = 12;</code>
     * @return string
     */
    public function getApplyTime()
    {
        return $this->applyTime;
    }

    /**
     * 申购日期字符串
     *
     * Generated from protobuf field <code>string applyTime = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setApplyTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->applyTime = $var;

        return $this;
    }

    /**
     * 申购日期时间戳
     *
     * Generated from protobuf field <code>double applyTimestamp = 13;</code>
     * @return float
     */
    public function getApplyTimestamp()
    {
        return $this->applyTimestamp;
    }

    /**
     * 申购日期时间戳
     *
     * Generated from protobuf field <code>double applyTimestamp = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setApplyTimestamp(float $var)
    {
        $this->applyTimestamp = $var;

        return $this;
    }

    /**
     * 公布中签日期字符串
     *
     * Generated from protobuf field <code>string winningTime = 14;</code>
     * @return string
     */
    public function getWinningTime()
    {
        return $this->winningTime;
    }

    /**
     * 公布中签日期字符串
     *
     * Generated from protobuf field <code>string winningTime = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setWinningTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->winningTime = $var;

        return $this;
    }

    /**
     * 公布中签日期时间戳
     *
     * Generated from protobuf field <code>double winningTimestamp = 15;</code>
     * @return float
     */
    public function getWinningTimestamp()
    {
        return $this->winningTimestamp;
    }

    /**
     * 公布中签日期时间戳
     *
     * Generated from protobuf field <code>double winningTimestamp = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setWinningTimestamp(float $var)
    {
        $this->winningTimestamp = $var;

        return $this;
    }

    /**
     * 是否已经公布中签号
     *
     * Generated from protobuf field <code>bool isHasWon = 16;</code>
     * @return bool
     */
    public function getIsHasWon()
    {
        return $this->isHasWon;
    }

    /**
     * 是否已经公布中签号
     *
     * Generated from protobuf field <code>bool isHasWon = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsHasWon(bool $var)
    {
        $this->isHasWon = $var;

        return $this;
    }

    /**
     * Qot_GetIpoList::WinningNumData 中签号数据，对应PC中"公布中签日期的已公布"
     *
     * Generated from protobuf field <code>repeated .Qot_GetIpoList.WinningNumData winningNumData = 17;</code>
     * @return RepeatedField<\Futu\Qot_GetIpoList\WinningNumData>
     */
    public function getWinningNumData()
    {
        return $this->winningNumData;
    }

    /**
     * Qot_GetIpoList::WinningNumData 中签号数据，对应PC中"公布中签日期的已公布"
     *
     * Generated from protobuf field <code>repeated .Qot_GetIpoList.WinningNumData winningNumData = 17;</code>
     * @param \Futu\Qot_GetIpoList\WinningNumData[] $var
     * @return $this
     */
    public function setWinningNumData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_GetIpoList\WinningNumData::class);
        $this->winningNumData = $arr;

        return $this;
    }

}

