<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetIpoList.proto

namespace Futu\Qot_GetIpoList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * 港股Ipo列表额外数据
 *
 * Generated from protobuf message <code>Qot_GetIpoList.HKIpoExData</code>
 */
class HKIpoExData extends \Google\Protobuf\Internal\Message
{
    /**
     * 最低发售价
     *
     * Generated from protobuf field <code>double ipoPriceMin = 1;</code>
     */
    protected $ipoPriceMin = 0.0;
    /**
     * 最高发售价
     *
     * Generated from protobuf field <code>double ipoPriceMax = 2;</code>
     */
    protected $ipoPriceMax = 0.0;
    /**
     * 上市价
     *
     * Generated from protobuf field <code>double listPrice = 3;</code>
     */
    protected $listPrice = 0.0;
    /**
     * 每手股数
     *
     * Generated from protobuf field <code>int32 lotSize = 4;</code>
     */
    protected $lotSize = 0;
    /**
     * 入场费
     *
     * Generated from protobuf field <code>double entrancePrice = 5;</code>
     */
    protected $entrancePrice = 0.0;
    /**
     * 是否为认购状态，True-认购中，False-待上市
     *
     * Generated from protobuf field <code>bool isSubscribeStatus = 6;</code>
     */
    protected $isSubscribeStatus = false;
    /**
     * 截止认购日期字符串
     *
     * Generated from protobuf field <code>string applyEndTime = 7;</code>
     */
    protected $applyEndTime = '';
    /**
     * 截止认购日期时间戳 因需处理认购手续，富途认购截止时间会早于交易所公布的日期。
     *
     * Generated from protobuf field <code>double applyEndTimestamp = 8;</code>
     */
    protected $applyEndTimestamp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $ipoPriceMin
     *           最低发售价
     *     @type float $ipoPriceMax
     *           最高发售价
     *     @type float $listPrice
     *           上市价
     *     @type int $lotSize
     *           每手股数
     *     @type float $entrancePrice
     *           入场费
     *     @type bool $isSubscribeStatus
     *           是否为认购状态，True-认购中，False-待上市
     *     @type string $applyEndTime
     *           截止认购日期字符串
     *     @type float $applyEndTimestamp
     *           截止认购日期时间戳 因需处理认购手续，富途认购截止时间会早于交易所公布的日期。
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetIpoList\pb\QotGetIpoList::initOnce();
        parent::__construct($data);
    }

    /**
     * 最低发售价
     *
     * Generated from protobuf field <code>double ipoPriceMin = 1;</code>
     * @return float
     */
    public function getIpoPriceMin()
    {
        return $this->ipoPriceMin;
    }

    /**
     * 最低发售价
     *
     * Generated from protobuf field <code>double ipoPriceMin = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setIpoPriceMin(float $var)
    {
        $this->ipoPriceMin = $var;

        return $this;
    }

    /**
     * 最高发售价
     *
     * Generated from protobuf field <code>double ipoPriceMax = 2;</code>
     * @return float
     */
    public function getIpoPriceMax()
    {
        return $this->ipoPriceMax;
    }

    /**
     * 最高发售价
     *
     * Generated from protobuf field <code>double ipoPriceMax = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setIpoPriceMax(float $var)
    {
        $this->ipoPriceMax = $var;

        return $this;
    }

    /**
     * 上市价
     *
     * Generated from protobuf field <code>double listPrice = 3;</code>
     * @return float
     */
    public function getListPrice()
    {
        return $this->listPrice;
    }

    /**
     * 上市价
     *
     * Generated from protobuf field <code>double listPrice = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setListPrice(float $var)
    {
        $this->listPrice = $var;

        return $this;
    }

    /**
     * 每手股数
     *
     * Generated from protobuf field <code>int32 lotSize = 4;</code>
     * @return int
     */
    public function getLotSize()
    {
        return $this->lotSize;
    }

    /**
     * 每手股数
     *
     * Generated from protobuf field <code>int32 lotSize = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLotSize(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->lotSize = $var;

        return $this;
    }

    /**
     * 入场费
     *
     * Generated from protobuf field <code>double entrancePrice = 5;</code>
     * @return float
     */
    public function getEntrancePrice()
    {
        return $this->entrancePrice;
    }

    /**
     * 入场费
     *
     * Generated from protobuf field <code>double entrancePrice = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setEntrancePrice(float $var)
    {
        $this->entrancePrice = $var;

        return $this;
    }

    /**
     * 是否为认购状态，True-认购中，False-待上市
     *
     * Generated from protobuf field <code>bool isSubscribeStatus = 6;</code>
     * @return bool
     */
    public function getIsSubscribeStatus()
    {
        return $this->isSubscribeStatus;
    }

    /**
     * 是否为认购状态，True-认购中，False-待上市
     *
     * Generated from protobuf field <code>bool isSubscribeStatus = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSubscribeStatus(bool $var)
    {
        $this->isSubscribeStatus = $var;

        return $this;
    }

    /**
     * 截止认购日期字符串
     *
     * Generated from protobuf field <code>string applyEndTime = 7;</code>
     * @return string
     */
    public function getApplyEndTime()
    {
        return $this->applyEndTime;
    }

    /**
     * 截止认购日期字符串
     *
     * Generated from protobuf field <code>string applyEndTime = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setApplyEndTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->applyEndTime = $var;

        return $this;
    }

    /**
     * 截止认购日期时间戳 因需处理认购手续，富途认购截止时间会早于交易所公布的日期。
     *
     * Generated from protobuf field <code>double applyEndTimestamp = 8;</code>
     * @return float
     */
    public function getApplyEndTimestamp()
    {
        return $this->applyEndTimestamp;
    }

    /**
     * 截止认购日期时间戳 因需处理认购手续，富途认购截止时间会早于交易所公布的日期。
     *
     * Generated from protobuf field <code>double applyEndTimestamp = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setApplyEndTimestamp(float $var)
    {
        $this->applyEndTimestamp = $var;

        return $this;
    }

}

