<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetIpoList.proto

namespace Futu\Qot_GetIpoList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * 新股Ipo数据
 *
 * Generated from protobuf message <code>Qot_GetIpoList.IpoData</code>
 */
class IpoData extends \Google\Protobuf\Internal\Message
{
    /**
     * IPO基本数据	
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.BasicIpoData basic = 1;</code>
     */
    protected $basic = null;
    /**
     * A股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.CNIpoExData cnExData = 2;</code>
     */
    protected $cnExData = null;
    /**
     * 港股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.HKIpoExData hkExData = 3;</code>
     */
    protected $hkExData = null;
    /**
     * 美股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.USIpoExData usExData = 4;</code>
     */
    protected $usExData = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_GetIpoList\BasicIpoData $basic
     *           IPO基本数据	
     *     @type \Futu\Qot_GetIpoList\CNIpoExData $cnExData
     *           A股IPO额外数据
     *     @type \Futu\Qot_GetIpoList\HKIpoExData $hkExData
     *           港股IPO额外数据
     *     @type \Futu\Qot_GetIpoList\USIpoExData $usExData
     *           美股IPO额外数据
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetIpoList\pb\QotGetIpoList::initOnce();
        parent::__construct($data);
    }

    /**
     * IPO基本数据	
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.BasicIpoData basic = 1;</code>
     * @return \Futu\Qot_GetIpoList\BasicIpoData|null
     */
    public function getBasic()
    {
        return $this->basic;
    }

    public function hasBasic()
    {
        return isset($this->basic);
    }

    public function clearBasic()
    {
        unset($this->basic);
    }

    /**
     * IPO基本数据	
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.BasicIpoData basic = 1;</code>
     * @param \Futu\Qot_GetIpoList\BasicIpoData $var
     * @return $this
     */
    public function setBasic(\Futu\Qot_GetIpoList\BasicIpoData|null $var)
    {
        $this->basic = $var;

        return $this;
    }

    /**
     * A股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.CNIpoExData cnExData = 2;</code>
     * @return \Futu\Qot_GetIpoList\CNIpoExData|null
     */
    public function getCnExData()
    {
        return $this->cnExData;
    }

    public function hasCnExData()
    {
        return isset($this->cnExData);
    }

    public function clearCnExData()
    {
        unset($this->cnExData);
    }

    /**
     * A股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.CNIpoExData cnExData = 2;</code>
     * @param \Futu\Qot_GetIpoList\CNIpoExData $var
     * @return $this
     */
    public function setCnExData(\Futu\Qot_GetIpoList\CNIpoExData|null $var)
    {
        $this->cnExData = $var;

        return $this;
    }

    /**
     * 港股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.HKIpoExData hkExData = 3;</code>
     * @return \Futu\Qot_GetIpoList\HKIpoExData|null
     */
    public function getHkExData()
    {
        return $this->hkExData;
    }

    public function hasHkExData()
    {
        return isset($this->hkExData);
    }

    public function clearHkExData()
    {
        unset($this->hkExData);
    }

    /**
     * 港股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.HKIpoExData hkExData = 3;</code>
     * @param \Futu\Qot_GetIpoList\HKIpoExData $var
     * @return $this
     */
    public function setHkExData(\Futu\Qot_GetIpoList\HKIpoExData|null $var)
    {
        $this->hkExData = $var;

        return $this;
    }

    /**
     * 美股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.USIpoExData usExData = 4;</code>
     * @return \Futu\Qot_GetIpoList\USIpoExData|null
     */
    public function getUsExData()
    {
        return $this->usExData;
    }

    public function hasUsExData()
    {
        return isset($this->usExData);
    }

    public function clearUsExData()
    {
        unset($this->usExData);
    }

    /**
     * 美股IPO额外数据
     *
     * Generated from protobuf field <code>.Qot_GetIpoList.USIpoExData usExData = 4;</code>
     * @param \Futu\Qot_GetIpoList\USIpoExData $var
     * @return $this
     */
    public function setUsExData(\Futu\Qot_GetIpoList\USIpoExData|null $var)
    {
        $this->usExData = $var;

        return $this;
    }

}

