<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetIpoList.proto

namespace Futu\Qot_GetIpoList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetIpoList.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     * 新股IPO数据
     *
     * Generated from protobuf field <code>repeated .Qot_GetIpoList.IpoData ipoList = 1;</code>
     */
    private $ipoList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_GetIpoList\IpoData[] $ipoList
     *           新股IPO数据
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetIpoList\pb\QotGetIpoList::initOnce();
        parent::__construct($data);
    }

    /**
     * 新股IPO数据
     *
     * Generated from protobuf field <code>repeated .Qot_GetIpoList.IpoData ipoList = 1;</code>
     * @return RepeatedField<\Futu\Qot_GetIpoList\IpoData>
     */
    public function getIpoList()
    {
        return $this->ipoList;
    }

    /**
     * 新股IPO数据
     *
     * Generated from protobuf field <code>repeated .Qot_GetIpoList.IpoData ipoList = 1;</code>
     * @param \Futu\Qot_GetIpoList\IpoData[] $var
     * @return $this
     */
    public function setIpoList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_GetIpoList\IpoData::class);
        $this->ipoList = $arr;

        return $this;
    }

}

