<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetIpoList.proto

namespace Futu\Qot_GetIpoList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * 中签号数据
 *
 * Generated from protobuf message <code>Qot_GetIpoList.WinningNumData</code>
 */
class WinningNumData extends \Google\Protobuf\Internal\Message
{
    /**
     * 分组名
     *
     * Generated from protobuf field <code>string winningName = 1;</code>
     */
    protected $winningName = '';
    /**
     * 中签号信息
     *
     * Generated from protobuf field <code>string winningInfo = 2;</code>
     */
    protected $winningInfo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $winningName
     *           分组名
     *     @type string $winningInfo
     *           中签号信息
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetIpoList\pb\QotGetIpoList::initOnce();
        parent::__construct($data);
    }

    /**
     * 分组名
     *
     * Generated from protobuf field <code>string winningName = 1;</code>
     * @return string
     */
    public function getWinningName()
    {
        return $this->winningName;
    }

    /**
     * 分组名
     *
     * Generated from protobuf field <code>string winningName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWinningName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->winningName = $var;

        return $this;
    }

    /**
     * 中签号信息
     *
     * Generated from protobuf field <code>string winningInfo = 2;</code>
     * @return string
     */
    public function getWinningInfo()
    {
        return $this->winningInfo;
    }

    /**
     * 中签号信息
     *
     * Generated from protobuf field <code>string winningInfo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWinningInfo(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->winningInfo = $var;

        return $this;
    }

}

