<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_UpdateBasicQot.proto

namespace Futu\Qot_UpdateBasicQot\pb;

class QotUpdateBasicQot
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x86\x02\x0A\x18Qot_UpdateBasicQot.proto\x12\x12Qot_UpdateBasicQot\"1\x0A\x03S2C\x12*\x0A\x0CbasicQotList\x18\x01 \x03(\x0B2\x14.Qot_Common.BasicQot\"b\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12\$\x0A\x03s2c\x18\x04 \x01(\x0B2\x17.Qot_UpdateBasicQot.S2CB7\xCA\x02\x17Futu\\Qot_UpdateBasicQot\xE2\x02\x1AFutu\\Qot_UpdateBasicQot\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

