<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestHistoryKL.proto

namespace Futu\Qot_RequestHistoryKL;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_RequestHistoryKL.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *Qot_Common.RehabType,复权类型
     *
     * Generated from protobuf field <code>int32 rehabType = 1;</code>
     */
    protected $rehabType = 0;
    /**
     *Qot_Common.KLType,K线类型
     *
     * Generated from protobuf field <code>int32 klType = 2;</code>
     */
    protected $klType = 0;
    /**
     *股票市场以及股票代码
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 3;</code>
     */
    protected $security = null;
    /**
     *开始时间字符串
     *
     * Generated from protobuf field <code>string beginTime = 4;</code>
     */
    protected $beginTime = '';
    /**
     *结束时间字符串
     *
     * Generated from protobuf field <code>string endTime = 5;</code>
     */
    protected $endTime = '';
    /**
     *最多返回多少根K线，如果未指定表示不限制
     *
     * Generated from protobuf field <code>int32 maxAckKLNum = 6;</code>
     */
    protected $maxAckKLNum = 0;
    /**
     *指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
     *
     * Generated from protobuf field <code>int64 needKLFieldsFlag = 7;</code>
     */
    protected $needKLFieldsFlag = 0;
    /**
     *分页请求key
     *
     * Generated from protobuf field <code>bytes nextReqKey = 8;</code>
     */
    protected $nextReqKey = '';
    /**
     *是否获取美股盘前盘后数据，仅支持 60 分钟及以下级别
     *
     * Generated from protobuf field <code>bool extendedTime = 9;</code>
     */
    protected $extendedTime = false;
    /**
     *Qot_Common.Session, 美股盘前盘后数据，仅支持 60 分钟及以下级别
     *
     * Generated from protobuf field <code>int32 session = 10;</code>
     */
    protected $session = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $rehabType
     *          Qot_Common.RehabType,复权类型
     *     @type int $klType
     *          Qot_Common.KLType,K线类型
     *     @type \Futu\Qot_Common\Security $security
     *          股票市场以及股票代码
     *     @type string $beginTime
     *          开始时间字符串
     *     @type string $endTime
     *          结束时间字符串
     *     @type int $maxAckKLNum
     *          最多返回多少根K线，如果未指定表示不限制
     *     @type int|string $needKLFieldsFlag
     *          指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
     *     @type string $nextReqKey
     *          分页请求key
     *     @type bool $extendedTime
     *          是否获取美股盘前盘后数据，仅支持 60 分钟及以下级别
     *     @type int $session
     *          Qot_Common.Session, 美股盘前盘后数据，仅支持 60 分钟及以下级别
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_RequestHistoryKL\pb\QotRequestHistoryKL::initOnce();
        parent::__construct($data);
    }

    /**
     *Qot_Common.RehabType,复权类型
     *
     * Generated from protobuf field <code>int32 rehabType = 1;</code>
     * @return int
     */
    public function getRehabType()
    {
        return $this->rehabType;
    }

    /**
     *Qot_Common.RehabType,复权类型
     *
     * Generated from protobuf field <code>int32 rehabType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRehabType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->rehabType = $var;

        return $this;
    }

    /**
     *Qot_Common.KLType,K线类型
     *
     * Generated from protobuf field <code>int32 klType = 2;</code>
     * @return int
     */
    public function getKlType()
    {
        return $this->klType;
    }

    /**
     *Qot_Common.KLType,K线类型
     *
     * Generated from protobuf field <code>int32 klType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKlType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->klType = $var;

        return $this;
    }

    /**
     *股票市场以及股票代码
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 3;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     *股票市场以及股票代码
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 3;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     *开始时间字符串
     *
     * Generated from protobuf field <code>string beginTime = 4;</code>
     * @return string
     */
    public function getBeginTime()
    {
        return $this->beginTime;
    }

    /**
     *开始时间字符串
     *
     * Generated from protobuf field <code>string beginTime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBeginTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->beginTime = $var;

        return $this;
    }

    /**
     *结束时间字符串
     *
     * Generated from protobuf field <code>string endTime = 5;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     *结束时间字符串
     *
     * Generated from protobuf field <code>string endTime = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endTime = $var;

        return $this;
    }

    /**
     *最多返回多少根K线，如果未指定表示不限制
     *
     * Generated from protobuf field <code>int32 maxAckKLNum = 6;</code>
     * @return int
     */
    public function getMaxAckKLNum()
    {
        return $this->maxAckKLNum;
    }

    /**
     *最多返回多少根K线，如果未指定表示不限制
     *
     * Generated from protobuf field <code>int32 maxAckKLNum = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxAckKLNum(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->maxAckKLNum = $var;

        return $this;
    }

    /**
     *指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
     *
     * Generated from protobuf field <code>int64 needKLFieldsFlag = 7;</code>
     * @return int|string
     */
    public function getNeedKLFieldsFlag()
    {
        return $this->needKLFieldsFlag;
    }

    /**
     *指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
     *
     * Generated from protobuf field <code>int64 needKLFieldsFlag = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNeedKLFieldsFlag(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->needKLFieldsFlag = $var;

        return $this;
    }

    /**
     *分页请求key
     *
     * Generated from protobuf field <code>bytes nextReqKey = 8;</code>
     * @return string
     */
    public function getNextReqKey()
    {
        return $this->nextReqKey;
    }

    /**
     *分页请求key
     *
     * Generated from protobuf field <code>bytes nextReqKey = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNextReqKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->nextReqKey = $var;

        return $this;
    }

    /**
     *是否获取美股盘前盘后数据，仅支持 60 分钟及以下级别
     *
     * Generated from protobuf field <code>bool extendedTime = 9;</code>
     * @return bool
     */
    public function getExtendedTime()
    {
        return $this->extendedTime;
    }

    /**
     *是否获取美股盘前盘后数据，仅支持 60 分钟及以下级别
     *
     * Generated from protobuf field <code>bool extendedTime = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setExtendedTime(bool $var)
    {
        $this->extendedTime = $var;

        return $this;
    }

    /**
     *Qot_Common.Session, 美股盘前盘后数据，仅支持 60 分钟及以下级别
     *
     * Generated from protobuf field <code>int32 session = 10;</code>
     * @return int
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     *Qot_Common.Session, 美股盘前盘后数据，仅支持 60 分钟及以下级别
     *
     * Generated from protobuf field <code>int32 session = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setSession(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->session = $var;

        return $this;
    }

}

