<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestHistoryKL.proto

namespace Futu\Qot_RequestHistoryKL;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_RequestHistoryKL.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;
    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 4;</code>
     */
    protected $name = '';
    /**
     *K线数据
     *
     * Generated from protobuf field <code>repeated .Qot_Common.KLine klList = 2;</code>
     */
    private $klList;
    /**
     *分页请求key。一次请求没有返回所有数据时，下次请求带上这个key，会接着请求
     *
     * Generated from protobuf field <code>bytes nextReqKey = 3;</code>
     */
    protected $nextReqKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *     @type string $name
     *           股票名称
     *     @type \Futu\Qot_Common\KLine[] $klList
     *          K线数据
     *     @type string $nextReqKey
     *          分页请求key。一次请求没有返回所有数据时，下次请求带上这个key，会接着请求
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_RequestHistoryKL\pb\QotRequestHistoryKL::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     *K线数据
     *
     * Generated from protobuf field <code>repeated .Qot_Common.KLine klList = 2;</code>
     * @return RepeatedField<\Futu\Qot_Common\KLine>
     */
    public function getKlList()
    {
        return $this->klList;
    }

    /**
     *K线数据
     *
     * Generated from protobuf field <code>repeated .Qot_Common.KLine klList = 2;</code>
     * @param \Futu\Qot_Common\KLine[] $var
     * @return $this
     */
    public function setKlList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\KLine::class);
        $this->klList = $arr;

        return $this;
    }

    /**
     *分页请求key。一次请求没有返回所有数据时，下次请求带上这个key，会接着请求
     *
     * Generated from protobuf field <code>bytes nextReqKey = 3;</code>
     * @return string
     */
    public function getNextReqKey()
    {
        return $this->nextReqKey;
    }

    /**
     *分页请求key。一次请求没有返回所有数据时，下次请求带上这个key，会接着请求
     *
     * Generated from protobuf field <code>bytes nextReqKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNextReqKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->nextReqKey = $var;

        return $this;
    }

}

