<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_UpdateTicker.proto

namespace Futu\Qot_UpdateTicker\pb;

class QotUpdateTicker
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAE\x02\x0A\x16Qot_UpdateTicker.proto\x12\x10Qot_UpdateTicker\"c\x0A\x03S2C\x12&\x0A\x08security\x18\x01 \x01(\x0B2\x14.Qot_Common.Security\x12\x0C\x0A\x04name\x18\x03 \x01(\x09\x12&\x0A\x0AtickerList\x18\x02 \x03(\x0B2\x12.Qot_Common.Ticker\"`\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12\"\x0A\x03s2c\x18\x04 \x01(\x0B2\x15.Qot_UpdateTicker.S2CB3\xCA\x02\x15Futu\\Qot_UpdateTicker\xE2\x02\x18Futu\\Qot_UpdateTicker\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

