<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InitConnect.proto

namespace Futu\InitConnect;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>InitConnect.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *客户端版本号，clientVer = "."以前的数 * 100 + "."以后的，举例：1.1版本的clientVer为1 * 100 + 1 = 101，2.21版本为2 * 100 + 21 = 221
     *
     * Generated from protobuf field <code>int32 clientVer = 1;</code>
     */
    protected $clientVer = 0;
    /**
     *客户端唯一标识，无生具体生成规则，客户端自己保证唯一性即可
     *
     * Generated from protobuf field <code>string clientID = 2;</code>
     */
    protected $clientID = '';
    /**
     *此连接是否接收市场状态、交易需要重新解锁等等事件通知，true代表接收，FutuOpenD就会向此连接推送这些通知，反之false代表不接收不推送
     *
     * Generated from protobuf field <code>bool recvNotify = 3;</code>
     */
    protected $recvNotify = false;
    /**
     *如果通信要加密，首先得在FutuOpenD和客户端都配置RSA密钥，不配置始终不加密
     *如果配置了RSA密钥且指定的加密算法不为PacketEncAlgo_None则加密(即便这里不设置，配置了RSA密钥，也会采用默认加密方式)，默认采用FTAES_ECB算法
     *
     * Generated from protobuf field <code>int32 packetEncAlgo = 4;</code>
     */
    protected $packetEncAlgo = 0;
    /**
     *指定这条连接上的推送协议格式，若不指定则使用push_proto_type配置项
     *
     * Generated from protobuf field <code>int32 pushProtoFmt = 5;</code>
     */
    protected $pushProtoFmt = 0;
    /**
     *接口编程语言，用于统计语言偏好
     *
     * Generated from protobuf field <code>string programmingLanguage = 6;</code>
     */
    protected $programmingLanguage = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $clientVer
     *          客户端版本号，clientVer = "."以前的数 * 100 + "."以后的，举例：1.1版本的clientVer为1 * 100 + 1 = 101，2.21版本为2 * 100 + 21 = 221
     *     @type string $clientID
     *          客户端唯一标识，无生具体生成规则，客户端自己保证唯一性即可
     *     @type bool $recvNotify
     *          此连接是否接收市场状态、交易需要重新解锁等等事件通知，true代表接收，FutuOpenD就会向此连接推送这些通知，反之false代表不接收不推送
     *     @type int $packetEncAlgo
     *          如果通信要加密，首先得在FutuOpenD和客户端都配置RSA密钥，不配置始终不加密
     *          如果配置了RSA密钥且指定的加密算法不为PacketEncAlgo_None则加密(即便这里不设置，配置了RSA密钥，也会采用默认加密方式)，默认采用FTAES_ECB算法
     *     @type int $pushProtoFmt
     *          指定这条连接上的推送协议格式，若不指定则使用push_proto_type配置项
     *     @type string $programmingLanguage
     *          接口编程语言，用于统计语言偏好
     * }
     */
    public function __construct($data = NULL) {
        \Futu\InitConnect\pb\InitConnect::initOnce();
        parent::__construct($data);
    }

    /**
     *客户端版本号，clientVer = "."以前的数 * 100 + "."以后的，举例：1.1版本的clientVer为1 * 100 + 1 = 101，2.21版本为2 * 100 + 21 = 221
     *
     * Generated from protobuf field <code>int32 clientVer = 1;</code>
     * @return int
     */
    public function getClientVer()
    {
        return $this->clientVer;
    }

    /**
     *客户端版本号，clientVer = "."以前的数 * 100 + "."以后的，举例：1.1版本的clientVer为1 * 100 + 1 = 101，2.21版本为2 * 100 + 21 = 221
     *
     * Generated from protobuf field <code>int32 clientVer = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClientVer(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->clientVer = $var;

        return $this;
    }

    /**
     *客户端唯一标识，无生具体生成规则，客户端自己保证唯一性即可
     *
     * Generated from protobuf field <code>string clientID = 2;</code>
     * @return string
     */
    public function getClientID()
    {
        return $this->clientID;
    }

    /**
     *客户端唯一标识，无生具体生成规则，客户端自己保证唯一性即可
     *
     * Generated from protobuf field <code>string clientID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientID(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->clientID = $var;

        return $this;
    }

    /**
     *此连接是否接收市场状态、交易需要重新解锁等等事件通知，true代表接收，FutuOpenD就会向此连接推送这些通知，反之false代表不接收不推送
     *
     * Generated from protobuf field <code>bool recvNotify = 3;</code>
     * @return bool
     */
    public function getRecvNotify()
    {
        return $this->recvNotify;
    }

    /**
     *此连接是否接收市场状态、交易需要重新解锁等等事件通知，true代表接收，FutuOpenD就会向此连接推送这些通知，反之false代表不接收不推送
     *
     * Generated from protobuf field <code>bool recvNotify = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setRecvNotify(bool $var)
    {
        $this->recvNotify = $var;

        return $this;
    }

    /**
     *如果通信要加密，首先得在FutuOpenD和客户端都配置RSA密钥，不配置始终不加密
     *如果配置了RSA密钥且指定的加密算法不为PacketEncAlgo_None则加密(即便这里不设置，配置了RSA密钥，也会采用默认加密方式)，默认采用FTAES_ECB算法
     *
     * Generated from protobuf field <code>int32 packetEncAlgo = 4;</code>
     * @return int
     */
    public function getPacketEncAlgo()
    {
        return $this->packetEncAlgo;
    }

    /**
     *如果通信要加密，首先得在FutuOpenD和客户端都配置RSA密钥，不配置始终不加密
     *如果配置了RSA密钥且指定的加密算法不为PacketEncAlgo_None则加密(即便这里不设置，配置了RSA密钥，也会采用默认加密方式)，默认采用FTAES_ECB算法
     *
     * Generated from protobuf field <code>int32 packetEncAlgo = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPacketEncAlgo(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->packetEncAlgo = $var;

        return $this;
    }

    /**
     *指定这条连接上的推送协议格式，若不指定则使用push_proto_type配置项
     *
     * Generated from protobuf field <code>int32 pushProtoFmt = 5;</code>
     * @return int
     */
    public function getPushProtoFmt()
    {
        return $this->pushProtoFmt;
    }

    /**
     *指定这条连接上的推送协议格式，若不指定则使用push_proto_type配置项
     *
     * Generated from protobuf field <code>int32 pushProtoFmt = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPushProtoFmt(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->pushProtoFmt = $var;

        return $this;
    }

    /**
     *接口编程语言，用于统计语言偏好
     *
     * Generated from protobuf field <code>string programmingLanguage = 6;</code>
     * @return string
     */
    public function getProgrammingLanguage()
    {
        return $this->programmingLanguage;
    }

    /**
     *接口编程语言，用于统计语言偏好
     *
     * Generated from protobuf field <code>string programmingLanguage = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProgrammingLanguage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->programmingLanguage = $var;

        return $this;
    }

}

