<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InitConnect.proto

namespace Futu\InitConnect;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>InitConnect.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     *返回结果，参见Common.RetType的枚举定义
     *
     * Generated from protobuf field <code>int32 retType = 1;</code>
     */
    protected $retType = 0;
    /**
     *返回结果描述
     *
     * Generated from protobuf field <code>string retMsg = 2;</code>
     */
    protected $retMsg = '';
    /**
     *错误码，客户端一般通过retType和retMsg来判断结果和详情，errCode只做日志记录，仅在个别协议失败时对账用
     *
     * Generated from protobuf field <code>int32 errCode = 3;</code>
     */
    protected $errCode = 0;
    /**
     * Generated from protobuf field <code>.InitConnect.S2C s2c = 4;</code>
     */
    protected $s2c = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retType
     *          返回结果，参见Common.RetType的枚举定义
     *     @type string $retMsg
     *          返回结果描述
     *     @type int $errCode
     *          错误码，客户端一般通过retType和retMsg来判断结果和详情，errCode只做日志记录，仅在个别协议失败时对账用
     *     @type \Futu\InitConnect\S2C $s2c
     * }
     */
    public function __construct($data = NULL) {
        \Futu\InitConnect\pb\InitConnect::initOnce();
        parent::__construct($data);
    }

    /**
     *返回结果，参见Common.RetType的枚举定义
     *
     * Generated from protobuf field <code>int32 retType = 1;</code>
     * @return int
     */
    public function getRetType()
    {
        return $this->retType;
    }

    /**
     *返回结果，参见Common.RetType的枚举定义
     *
     * Generated from protobuf field <code>int32 retType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRetType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->retType = $var;

        return $this;
    }

    /**
     *返回结果描述
     *
     * Generated from protobuf field <code>string retMsg = 2;</code>
     * @return string
     */
    public function getRetMsg()
    {
        return $this->retMsg;
    }

    /**
     *返回结果描述
     *
     * Generated from protobuf field <code>string retMsg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRetMsg(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->retMsg = $var;

        return $this;
    }

    /**
     *错误码，客户端一般通过retType和retMsg来判断结果和详情，errCode只做日志记录，仅在个别协议失败时对账用
     *
     * Generated from protobuf field <code>int32 errCode = 3;</code>
     * @return int
     */
    public function getErrCode()
    {
        return $this->errCode;
    }

    /**
     *错误码，客户端一般通过retType和retMsg来判断结果和详情，errCode只做日志记录，仅在个别协议失败时对账用
     *
     * Generated from protobuf field <code>int32 errCode = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setErrCode(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->errCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.InitConnect.S2C s2c = 4;</code>
     * @return \Futu\InitConnect\S2C|null
     */
    public function getS2C()
    {
        return $this->s2c;
    }

    public function hasS2C()
    {
        return isset($this->s2c);
    }

    public function clearS2C()
    {
        unset($this->s2c);
    }

    /**
     * Generated from protobuf field <code>.InitConnect.S2C s2c = 4;</code>
     * @param \Futu\InitConnect\S2C $var
     * @return $this
     */
    public function setS2C(\Futu\InitConnect\S2C|null $var)
    {
        $this->s2c = $var;

        return $this;
    }

}

