<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InitConnect.proto

namespace Futu\InitConnect;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>InitConnect.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *FutuOpenD的版本号
     *
     * Generated from protobuf field <code>int32 serverVer = 1;</code>
     */
    protected $serverVer = 0;
    /**
     *FutuOpenD登陆的牛牛用户ID
     *
     * Generated from protobuf field <code>uint64 loginUserID = 2;</code>
     */
    protected $loginUserID = 0;
    /**
     *此连接的连接ID，连接的唯一标识
     *
     * Generated from protobuf field <code>uint64 connID = 3;</code>
     */
    protected $connID = 0;
    /**
     *此连接后续AES加密通信的Key，固定为16字节长字符串
     *
     * Generated from protobuf field <code>string connAESKey = 4;</code>
     */
    protected $connAESKey = '';
    /**
     *心跳保活间隔
     *
     * Generated from protobuf field <code>int32 keepAliveInterval = 5;</code>
     */
    protected $keepAliveInterval = 0;
    /**
     *AES加密通信CBC加密模式的iv，固定为16字节长字符串
     *
     * Generated from protobuf field <code>string aesCBCiv = 6;</code>
     */
    protected $aesCBCiv = '';
    /**
     *用户类型，牛牛用户或MooMoo用户
     *
     * Generated from protobuf field <code>int32 userAttribution = 7;</code>
     */
    protected $userAttribution = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $serverVer
     *          FutuOpenD的版本号
     *     @type int|string $loginUserID
     *          FutuOpenD登陆的牛牛用户ID
     *     @type int|string $connID
     *          此连接的连接ID，连接的唯一标识
     *     @type string $connAESKey
     *          此连接后续AES加密通信的Key，固定为16字节长字符串
     *     @type int $keepAliveInterval
     *          心跳保活间隔
     *     @type string $aesCBCiv
     *          AES加密通信CBC加密模式的iv，固定为16字节长字符串
     *     @type int $userAttribution
     *          用户类型，牛牛用户或MooMoo用户
     * }
     */
    public function __construct($data = NULL) {
        \Futu\InitConnect\pb\InitConnect::initOnce();
        parent::__construct($data);
    }

    /**
     *FutuOpenD的版本号
     *
     * Generated from protobuf field <code>int32 serverVer = 1;</code>
     * @return int
     */
    public function getServerVer()
    {
        return $this->serverVer;
    }

    /**
     *FutuOpenD的版本号
     *
     * Generated from protobuf field <code>int32 serverVer = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setServerVer(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->serverVer = $var;

        return $this;
    }

    /**
     *FutuOpenD登陆的牛牛用户ID
     *
     * Generated from protobuf field <code>uint64 loginUserID = 2;</code>
     * @return int|string
     */
    public function getLoginUserID()
    {
        return $this->loginUserID;
    }

    /**
     *FutuOpenD登陆的牛牛用户ID
     *
     * Generated from protobuf field <code>uint64 loginUserID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLoginUserID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->loginUserID = $var;

        return $this;
    }

    /**
     *此连接的连接ID，连接的唯一标识
     *
     * Generated from protobuf field <code>uint64 connID = 3;</code>
     * @return int|string
     */
    public function getConnID()
    {
        return $this->connID;
    }

    /**
     *此连接的连接ID，连接的唯一标识
     *
     * Generated from protobuf field <code>uint64 connID = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConnID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->connID = $var;

        return $this;
    }

    /**
     *此连接后续AES加密通信的Key，固定为16字节长字符串
     *
     * Generated from protobuf field <code>string connAESKey = 4;</code>
     * @return string
     */
    public function getConnAESKey()
    {
        return $this->connAESKey;
    }

    /**
     *此连接后续AES加密通信的Key，固定为16字节长字符串
     *
     * Generated from protobuf field <code>string connAESKey = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setConnAESKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->connAESKey = $var;

        return $this;
    }

    /**
     *心跳保活间隔
     *
     * Generated from protobuf field <code>int32 keepAliveInterval = 5;</code>
     * @return int
     */
    public function getKeepAliveInterval()
    {
        return $this->keepAliveInterval;
    }

    /**
     *心跳保活间隔
     *
     * Generated from protobuf field <code>int32 keepAliveInterval = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setKeepAliveInterval(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->keepAliveInterval = $var;

        return $this;
    }

    /**
     *AES加密通信CBC加密模式的iv，固定为16字节长字符串
     *
     * Generated from protobuf field <code>string aesCBCiv = 6;</code>
     * @return string
     */
    public function getAesCBCiv()
    {
        return $this->aesCBCiv;
    }

    /**
     *AES加密通信CBC加密模式的iv，固定为16字节长字符串
     *
     * Generated from protobuf field <code>string aesCBCiv = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAesCBCiv(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->aesCBCiv = $var;

        return $this;
    }

    /**
     *用户类型，牛牛用户或MooMoo用户
     *
     * Generated from protobuf field <code>int32 userAttribution = 7;</code>
     * @return int
     */
    public function getUserAttribution()
    {
        return $this->userAttribution;
    }

    /**
     *用户类型，牛牛用户或MooMoo用户
     *
     * Generated from protobuf field <code>int32 userAttribution = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setUserAttribution(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->userAttribution = $var;

        return $this;
    }

}

