<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetCapitalDistribution.proto

namespace Futu\Qot_GetCapitalDistribution;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetCapitalDistribution.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *          股票
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetCapitalDistribution\pb\QotGetCapitalDistribution::initOnce();
        parent::__construct($data);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

}

