<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetCapitalDistribution.proto

namespace Futu\Qot_GetCapitalDistribution;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetCapitalDistribution.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     * 流入资金额度，特大单
     *
     * Generated from protobuf field <code>double capitalInSuper = 9;</code>
     */
    protected $capitalInSuper = 0.0;
    /**
     * 流入资金额度，大单
     *
     * Generated from protobuf field <code>double capitalInBig = 1;</code>
     */
    protected $capitalInBig = 0.0;
    /**
     * 流入资金额度，中单
     *
     * Generated from protobuf field <code>double capitalInMid = 2;</code>
     */
    protected $capitalInMid = 0.0;
    /**
     * 流入资金额度，小单
     *
     * Generated from protobuf field <code>double capitalInSmall = 3;</code>
     */
    protected $capitalInSmall = 0.0;
    /**
     * 流出资金额度，特大单
     *
     * Generated from protobuf field <code>double capitalOutSuper = 10;</code>
     */
    protected $capitalOutSuper = 0.0;
    /**
     * 流出资金额度，大单
     *
     * Generated from protobuf field <code>double capitalOutBig = 4;</code>
     */
    protected $capitalOutBig = 0.0;
    /**
     * 流出资金额度，中单
     *
     * Generated from protobuf field <code>double capitalOutMid = 5;</code>
     */
    protected $capitalOutMid = 0.0;
    /**
     * 流出资金额度，小单
     *
     * Generated from protobuf field <code>double capitalOutSmall = 6;</code>
     */
    protected $capitalOutSmall = 0.0;
    /**
     * 更新时间字符串
     *
     * Generated from protobuf field <code>string updateTime = 7;</code>
     */
    protected $updateTime = '';
    /**
     * 更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 8;</code>
     */
    protected $updateTimestamp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $capitalInSuper
     *           流入资金额度，特大单
     *     @type float $capitalInBig
     *           流入资金额度，大单
     *     @type float $capitalInMid
     *           流入资金额度，中单
     *     @type float $capitalInSmall
     *           流入资金额度，小单
     *     @type float $capitalOutSuper
     *           流出资金额度，特大单
     *     @type float $capitalOutBig
     *           流出资金额度，大单
     *     @type float $capitalOutMid
     *           流出资金额度，中单
     *     @type float $capitalOutSmall
     *           流出资金额度，小单
     *     @type string $updateTime
     *           更新时间字符串
     *     @type float $updateTimestamp
     *           更新时间戳
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetCapitalDistribution\pb\QotGetCapitalDistribution::initOnce();
        parent::__construct($data);
    }

    /**
     * 流入资金额度，特大单
     *
     * Generated from protobuf field <code>double capitalInSuper = 9;</code>
     * @return float
     */
    public function getCapitalInSuper()
    {
        return $this->capitalInSuper;
    }

    /**
     * 流入资金额度，特大单
     *
     * Generated from protobuf field <code>double capitalInSuper = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setCapitalInSuper(float $var)
    {
        $this->capitalInSuper = $var;

        return $this;
    }

    /**
     * 流入资金额度，大单
     *
     * Generated from protobuf field <code>double capitalInBig = 1;</code>
     * @return float
     */
    public function getCapitalInBig()
    {
        return $this->capitalInBig;
    }

    /**
     * 流入资金额度，大单
     *
     * Generated from protobuf field <code>double capitalInBig = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setCapitalInBig(float $var)
    {
        $this->capitalInBig = $var;

        return $this;
    }

    /**
     * 流入资金额度，中单
     *
     * Generated from protobuf field <code>double capitalInMid = 2;</code>
     * @return float
     */
    public function getCapitalInMid()
    {
        return $this->capitalInMid;
    }

    /**
     * 流入资金额度，中单
     *
     * Generated from protobuf field <code>double capitalInMid = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setCapitalInMid(float $var)
    {
        $this->capitalInMid = $var;

        return $this;
    }

    /**
     * 流入资金额度，小单
     *
     * Generated from protobuf field <code>double capitalInSmall = 3;</code>
     * @return float
     */
    public function getCapitalInSmall()
    {
        return $this->capitalInSmall;
    }

    /**
     * 流入资金额度，小单
     *
     * Generated from protobuf field <code>double capitalInSmall = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setCapitalInSmall(float $var)
    {
        $this->capitalInSmall = $var;

        return $this;
    }

    /**
     * 流出资金额度，特大单
     *
     * Generated from protobuf field <code>double capitalOutSuper = 10;</code>
     * @return float
     */
    public function getCapitalOutSuper()
    {
        return $this->capitalOutSuper;
    }

    /**
     * 流出资金额度，特大单
     *
     * Generated from protobuf field <code>double capitalOutSuper = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setCapitalOutSuper(float $var)
    {
        $this->capitalOutSuper = $var;

        return $this;
    }

    /**
     * 流出资金额度，大单
     *
     * Generated from protobuf field <code>double capitalOutBig = 4;</code>
     * @return float
     */
    public function getCapitalOutBig()
    {
        return $this->capitalOutBig;
    }

    /**
     * 流出资金额度，大单
     *
     * Generated from protobuf field <code>double capitalOutBig = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setCapitalOutBig(float $var)
    {
        $this->capitalOutBig = $var;

        return $this;
    }

    /**
     * 流出资金额度，中单
     *
     * Generated from protobuf field <code>double capitalOutMid = 5;</code>
     * @return float
     */
    public function getCapitalOutMid()
    {
        return $this->capitalOutMid;
    }

    /**
     * 流出资金额度，中单
     *
     * Generated from protobuf field <code>double capitalOutMid = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setCapitalOutMid(float $var)
    {
        $this->capitalOutMid = $var;

        return $this;
    }

    /**
     * 流出资金额度，小单
     *
     * Generated from protobuf field <code>double capitalOutSmall = 6;</code>
     * @return float
     */
    public function getCapitalOutSmall()
    {
        return $this->capitalOutSmall;
    }

    /**
     * 流出资金额度，小单
     *
     * Generated from protobuf field <code>double capitalOutSmall = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setCapitalOutSmall(float $var)
    {
        $this->capitalOutSmall = $var;

        return $this;
    }

    /**
     * 更新时间字符串
     *
     * Generated from protobuf field <code>string updateTime = 7;</code>
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->updateTime;
    }

    /**
     * 更新时间字符串
     *
     * Generated from protobuf field <code>string updateTime = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->updateTime = $var;

        return $this;
    }

    /**
     * 更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 8;</code>
     * @return float
     */
    public function getUpdateTimestamp()
    {
        return $this->updateTimestamp;
    }

    /**
     * 更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setUpdateTimestamp(float $var)
    {
        $this->updateTimestamp = $var;

        return $this;
    }

}

