<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetOptionExpirationDate.proto

namespace Futu\Qot_GetOptionExpirationDate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetOptionExpirationDate.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *期权链行权日
     *
     * Generated from protobuf field <code>repeated .Qot_GetOptionExpirationDate.OptionExpirationDate dateList = 1;</code>
     */
    private $dateList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_GetOptionExpirationDate\OptionExpirationDate[] $dateList
     *          期权链行权日
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetOptionExpirationDate\pb\QotGetOptionExpirationDate::initOnce();
        parent::__construct($data);
    }

    /**
     *期权链行权日
     *
     * Generated from protobuf field <code>repeated .Qot_GetOptionExpirationDate.OptionExpirationDate dateList = 1;</code>
     * @return RepeatedField<\Futu\Qot_GetOptionExpirationDate\OptionExpirationDate>
     */
    public function getDateList()
    {
        return $this->dateList;
    }

    /**
     *期权链行权日
     *
     * Generated from protobuf field <code>repeated .Qot_GetOptionExpirationDate.OptionExpirationDate dateList = 1;</code>
     * @param \Futu\Qot_GetOptionExpirationDate\OptionExpirationDate[] $var
     * @return $this
     */
    public function setDateList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_GetOptionExpirationDate\OptionExpirationDate::class);
        $this->dateList = $arr;

        return $this;
    }

}

