<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetOwnerPlate.proto

namespace Futu\Qot_GetOwnerPlate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetOwnerPlate.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *所属板块信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetOwnerPlate.SecurityOwnerPlate ownerPlateList = 1;</code>
     */
    private $ownerPlateList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_GetOwnerPlate\SecurityOwnerPlate[] $ownerPlateList
     *          所属板块信息
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetOwnerPlate\pb\QotGetOwnerPlate::initOnce();
        parent::__construct($data);
    }

    /**
     *所属板块信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetOwnerPlate.SecurityOwnerPlate ownerPlateList = 1;</code>
     * @return RepeatedField<\Futu\Qot_GetOwnerPlate\SecurityOwnerPlate>
     */
    public function getOwnerPlateList()
    {
        return $this->ownerPlateList;
    }

    /**
     *所属板块信息
     *
     * Generated from protobuf field <code>repeated .Qot_GetOwnerPlate.SecurityOwnerPlate ownerPlateList = 1;</code>
     * @param \Futu\Qot_GetOwnerPlate\SecurityOwnerPlate[] $var
     * @return $this
     */
    public function setOwnerPlateList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_GetOwnerPlate\SecurityOwnerPlate::class);
        $this->ownerPlateList = $arr;

        return $this;
    }

}

