<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetOwnerPlate.proto

namespace Futu\Qot_GetOwnerPlate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetOwnerPlate.SecurityOwnerPlate</code>
 */
class SecurityOwnerPlate extends \Google\Protobuf\Internal\Message
{
    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;
    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     *所属板块
     *
     * Generated from protobuf field <code>repeated .Qot_Common.PlateInfo plateInfoList = 2;</code>
     */
    private $plateInfoList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *          股票
     *     @type string $name
     *           股票名称
     *     @type \Futu\Qot_Common\PlateInfo[] $plateInfoList
     *          所属板块
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetOwnerPlate\pb\QotGetOwnerPlate::initOnce();
        parent::__construct($data);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 股票名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     *所属板块
     *
     * Generated from protobuf field <code>repeated .Qot_Common.PlateInfo plateInfoList = 2;</code>
     * @return RepeatedField<\Futu\Qot_Common\PlateInfo>
     */
    public function getPlateInfoList()
    {
        return $this->plateInfoList;
    }

    /**
     *所属板块
     *
     * Generated from protobuf field <code>repeated .Qot_Common.PlateInfo plateInfoList = 2;</code>
     * @param \Futu\Qot_Common\PlateInfo[] $var
     * @return $this
     */
    public function setPlateInfoList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\PlateInfo::class);
        $this->plateInfoList = $arr;

        return $this;
    }

}

