<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetMaxTrdQtys.proto

namespace Futu\Trd_GetMaxTrdQtys;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_GetMaxTrdQtys.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     */
    protected $header = null;
    /**
     *订单类型, 参见Trd_Common.OrderType的枚举定义
     *
     * Generated from protobuf field <code>int32 orderType = 2;</code>
     */
    protected $orderType = 0;
    /**
     *代码，港股必须是5位数字，A股必须是6位数字，美股没限制
     *
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     *价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）。如果是竞价、市价单，请也填入一个当前价格，服务器才好计算
     *
     * Generated from protobuf field <code>double price = 4;</code>
     */
    protected $price = 0.0;
    /**
     *订单号，新下订单不需要，如果是修改订单就需要把原订单号带上才行，因为改单的最大买卖数量会包含原订单数量。
     *
     * Generated from protobuf field <code>uint64 orderID = 5;</code>
     */
    protected $orderID = 0;
    /**
     *为保证与下单的价格同步，也提供调整价格选项，以下2个为调整价格使用，对港、A股有意义，因为港股有价位，A股2位精度，美股可不传
     *
     * Generated from protobuf field <code>bool adjustPrice = 6;</code>
     */
    protected $adjustPrice = false;
    /**
     *调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
     *
     * Generated from protobuf field <code>double adjustSideAndLimit = 7;</code>
     */
    protected $adjustSideAndLimit = 0.0;
    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 8;</code>
     */
    protected $secMarket = 0;
    /**
     *表示服务器订单id，可以用来代替orderID，和orderID二选一
     *
     * Generated from protobuf field <code>string orderIDEx = 9;</code>
     */
    protected $orderIDEx = '';
    /**
     *美股订单时段, 参见Common.Session的枚举定义
     *
     * Generated from protobuf field <code>int32 session = 10;</code>
     */
    protected $session = 0;
    /**
     *持仓ID，JP券商查询平仓数量时使用
     *
     * Generated from protobuf field <code>uint64 positionID = 11;</code>
     */
    protected $positionID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Trd_Common\TrdHeader $header
     *          交易公共参数头
     *     @type int $orderType
     *          订单类型, 参见Trd_Common.OrderType的枚举定义
     *     @type string $code
     *          代码，港股必须是5位数字，A股必须是6位数字，美股没限制
     *     @type float $price
     *          价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）。如果是竞价、市价单，请也填入一个当前价格，服务器才好计算
     *     @type int|string $orderID
     *          订单号，新下订单不需要，如果是修改订单就需要把原订单号带上才行，因为改单的最大买卖数量会包含原订单数量。
     *     @type bool $adjustPrice
     *          为保证与下单的价格同步，也提供调整价格选项，以下2个为调整价格使用，对港、A股有意义，因为港股有价位，A股2位精度，美股可不传
     *     @type float $adjustSideAndLimit
     *          调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
     *     @type int $secMarket
     *          证券所属市场，参见TrdSecMarket的枚举定义
     *     @type string $orderIDEx
     *          表示服务器订单id，可以用来代替orderID，和orderID二选一
     *     @type int $session
     *          美股订单时段, 参见Common.Session的枚举定义
     *     @type int|string $positionID
     *          持仓ID，JP券商查询平仓数量时使用
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_GetMaxTrdQtys\pb\TrdGetMaxTrdQtys::initOnce();
        parent::__construct($data);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @return \Futu\Trd_Common\TrdHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @param \Futu\Trd_Common\TrdHeader $var
     * @return $this
     */
    public function setHeader(\Futu\Trd_Common\TrdHeader|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     *订单类型, 参见Trd_Common.OrderType的枚举定义
     *
     * Generated from protobuf field <code>int32 orderType = 2;</code>
     * @return int
     */
    public function getOrderType()
    {
        return $this->orderType;
    }

    /**
     *订单类型, 参见Trd_Common.OrderType的枚举定义
     *
     * Generated from protobuf field <code>int32 orderType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->orderType = $var;

        return $this;
    }

    /**
     *代码，港股必须是5位数字，A股必须是6位数字，美股没限制
     *
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *代码，港股必须是5位数字，A股必须是6位数字，美股没限制
     *
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->code = $var;

        return $this;
    }

    /**
     *价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）。如果是竞价、市价单，请也填入一个当前价格，服务器才好计算
     *
     * Generated from protobuf field <code>double price = 4;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     *价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）。如果是竞价、市价单，请也填入一个当前价格，服务器才好计算
     *
     * Generated from protobuf field <code>double price = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice(float $var)
    {
        $this->price = $var;

        return $this;
    }

    /**
     *订单号，新下订单不需要，如果是修改订单就需要把原订单号带上才行，因为改单的最大买卖数量会包含原订单数量。
     *
     * Generated from protobuf field <code>uint64 orderID = 5;</code>
     * @return int|string
     */
    public function getOrderID()
    {
        return $this->orderID;
    }

    /**
     *订单号，新下订单不需要，如果是修改订单就需要把原订单号带上才行，因为改单的最大买卖数量会包含原订单数量。
     *
     * Generated from protobuf field <code>uint64 orderID = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->orderID = $var;

        return $this;
    }

    /**
     *为保证与下单的价格同步，也提供调整价格选项，以下2个为调整价格使用，对港、A股有意义，因为港股有价位，A股2位精度，美股可不传
     *
     * Generated from protobuf field <code>bool adjustPrice = 6;</code>
     * @return bool
     */
    public function getAdjustPrice()
    {
        return $this->adjustPrice;
    }

    /**
     *为保证与下单的价格同步，也提供调整价格选项，以下2个为调整价格使用，对港、A股有意义，因为港股有价位，A股2位精度，美股可不传
     *
     * Generated from protobuf field <code>bool adjustPrice = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setAdjustPrice(bool $var)
    {
        $this->adjustPrice = $var;

        return $this;
    }

    /**
     *调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
     *
     * Generated from protobuf field <code>double adjustSideAndLimit = 7;</code>
     * @return float
     */
    public function getAdjustSideAndLimit()
    {
        return $this->adjustSideAndLimit;
    }

    /**
     *调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
     *
     * Generated from protobuf field <code>double adjustSideAndLimit = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setAdjustSideAndLimit(float $var)
    {
        $this->adjustSideAndLimit = $var;

        return $this;
    }

    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 8;</code>
     * @return int
     */
    public function getSecMarket()
    {
        return $this->secMarket;
    }

    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setSecMarket(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->secMarket = $var;

        return $this;
    }

    /**
     *表示服务器订单id，可以用来代替orderID，和orderID二选一
     *
     * Generated from protobuf field <code>string orderIDEx = 9;</code>
     * @return string
     */
    public function getOrderIDEx()
    {
        return $this->orderIDEx;
    }

    /**
     *表示服务器订单id，可以用来代替orderID，和orderID二选一
     *
     * Generated from protobuf field <code>string orderIDEx = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderIDEx(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->orderIDEx = $var;

        return $this;
    }

    /**
     *美股订单时段, 参见Common.Session的枚举定义
     *
     * Generated from protobuf field <code>int32 session = 10;</code>
     * @return int
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     *美股订单时段, 参见Common.Session的枚举定义
     *
     * Generated from protobuf field <code>int32 session = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setSession(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->session = $var;

        return $this;
    }

    /**
     *持仓ID，JP券商查询平仓数量时使用
     *
     * Generated from protobuf field <code>uint64 positionID = 11;</code>
     * @return int|string
     */
    public function getPositionID()
    {
        return $this->positionID;
    }

    /**
     *持仓ID，JP券商查询平仓数量时使用
     *
     * Generated from protobuf field <code>uint64 positionID = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->positionID = $var;

        return $this;
    }

}

