<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetMarginRatio.proto

namespace Futu\Trd_GetMarginRatio;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_GetMarginRatio.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     */
    protected $header = null;
    /**
     *账户资金
     *
     * Generated from protobuf field <code>repeated .Trd_GetMarginRatio.MarginRatioInfo marginRatioInfoList = 2;</code>
     */
    private $marginRatioInfoList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Trd_Common\TrdHeader $header
     *          交易公共参数头
     *     @type \Futu\Trd_GetMarginRatio\MarginRatioInfo[] $marginRatioInfoList
     *          账户资金
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_GetMarginRatio\pb\TrdGetMarginRatio::initOnce();
        parent::__construct($data);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @return \Futu\Trd_Common\TrdHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @param \Futu\Trd_Common\TrdHeader $var
     * @return $this
     */
    public function setHeader(\Futu\Trd_Common\TrdHeader|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     *账户资金
     *
     * Generated from protobuf field <code>repeated .Trd_GetMarginRatio.MarginRatioInfo marginRatioInfoList = 2;</code>
     * @return RepeatedField<\Futu\Trd_GetMarginRatio\MarginRatioInfo>
     */
    public function getMarginRatioInfoList()
    {
        return $this->marginRatioInfoList;
    }

    /**
     *账户资金
     *
     * Generated from protobuf field <code>repeated .Trd_GetMarginRatio.MarginRatioInfo marginRatioInfoList = 2;</code>
     * @param \Futu\Trd_GetMarginRatio\MarginRatioInfo[] $var
     * @return $this
     */
    public function setMarginRatioInfoList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Trd_GetMarginRatio\MarginRatioInfo::class);
        $this->marginRatioInfoList = $arr;

        return $this;
    }

}

