<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetOrderFillList.proto

namespace Futu\Trd_GetOrderFillList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_GetOrderFillList.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     */
    protected $header = null;
    /**
     *过滤条件
     *
     * Generated from protobuf field <code>.Trd_Common.TrdFilterConditions filterConditions = 2;</code>
     */
    protected $filterConditions = null;
    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 3;</code>
     */
    protected $refreshCache = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Trd_Common\TrdHeader $header
     *          交易公共参数头
     *     @type \Futu\Trd_Common\TrdFilterConditions $filterConditions
     *          过滤条件
     *     @type bool $refreshCache
     *          立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_GetOrderFillList\pb\TrdGetOrderFillList::initOnce();
        parent::__construct($data);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @return \Futu\Trd_Common\TrdHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @param \Futu\Trd_Common\TrdHeader $var
     * @return $this
     */
    public function setHeader(\Futu\Trd_Common\TrdHeader|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     *过滤条件
     *
     * Generated from protobuf field <code>.Trd_Common.TrdFilterConditions filterConditions = 2;</code>
     * @return \Futu\Trd_Common\TrdFilterConditions|null
     */
    public function getFilterConditions()
    {
        return $this->filterConditions;
    }

    public function hasFilterConditions()
    {
        return isset($this->filterConditions);
    }

    public function clearFilterConditions()
    {
        unset($this->filterConditions);
    }

    /**
     *过滤条件
     *
     * Generated from protobuf field <code>.Trd_Common.TrdFilterConditions filterConditions = 2;</code>
     * @param \Futu\Trd_Common\TrdFilterConditions $var
     * @return $this
     */
    public function setFilterConditions(\Futu\Trd_Common\TrdFilterConditions|null $var)
    {
        $this->filterConditions = $var;

        return $this;
    }

    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 3;</code>
     * @return bool
     */
    public function getRefreshCache()
    {
        return $this->refreshCache;
    }

    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setRefreshCache(bool $var)
    {
        $this->refreshCache = $var;

        return $this;
    }

}

