<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetKL.proto

namespace Futu\Qot_GetKL;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetKL.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *Qot_Common.RehabType,复权类型
     *
     * Generated from protobuf field <code>int32 rehabType = 1;</code>
     */
    protected $rehabType = 0;
    /**
     *Qot_Common.KLType,K线类型
     *
     * Generated from protobuf field <code>int32 klType = 2;</code>
     */
    protected $klType = 0;
    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 3;</code>
     */
    protected $security = null;
    /**
     *请求K线根数
     *
     * Generated from protobuf field <code>int32 reqNum = 4;</code>
     */
    protected $reqNum = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $rehabType
     *          Qot_Common.RehabType,复权类型
     *     @type int $klType
     *          Qot_Common.KLType,K线类型
     *     @type \Futu\Qot_Common\Security $security
     *          股票
     *     @type int $reqNum
     *          请求K线根数
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetKL\pb\QotGetKL::initOnce();
        parent::__construct($data);
    }

    /**
     *Qot_Common.RehabType,复权类型
     *
     * Generated from protobuf field <code>int32 rehabType = 1;</code>
     * @return int
     */
    public function getRehabType()
    {
        return $this->rehabType;
    }

    /**
     *Qot_Common.RehabType,复权类型
     *
     * Generated from protobuf field <code>int32 rehabType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRehabType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->rehabType = $var;

        return $this;
    }

    /**
     *Qot_Common.KLType,K线类型
     *
     * Generated from protobuf field <code>int32 klType = 2;</code>
     * @return int
     */
    public function getKlType()
    {
        return $this->klType;
    }

    /**
     *Qot_Common.KLType,K线类型
     *
     * Generated from protobuf field <code>int32 klType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKlType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->klType = $var;

        return $this;
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 3;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     *股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 3;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     *请求K线根数
     *
     * Generated from protobuf field <code>int32 reqNum = 4;</code>
     * @return int
     */
    public function getReqNum()
    {
        return $this->reqNum;
    }

    /**
     *请求K线根数
     *
     * Generated from protobuf field <code>int32 reqNum = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setReqNum(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->reqNum = $var;

        return $this;
    }

}

