<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *账户现金信息，目前仅用于期货账户
 *
 * Generated from protobuf message <code>Trd_Common.AccCashInfo</code>
 */
class AccCashInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 货币类型，取值参考 Currency
     *
     * Generated from protobuf field <code>int32 currency = 1;</code>
     */
    protected $currency = 0;
    /**
     * 现金结余
     *
     * Generated from protobuf field <code>double cash = 2;</code>
     */
    protected $cash = 0.0;
    /**
     * 现金可提金额
     *
     * Generated from protobuf field <code>double availableBalance = 3;</code>
     */
    protected $availableBalance = 0.0;
    /**
     * 现金购买力
     *
     * Generated from protobuf field <code>double netCashPower = 4;</code>
     */
    protected $netCashPower = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $currency
     *           货币类型，取值参考 Currency
     *     @type float $cash
     *           现金结余
     *     @type float $availableBalance
     *           现金可提金额
     *     @type float $netCashPower
     *           现金购买力
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * 货币类型，取值参考 Currency
     *
     * Generated from protobuf field <code>int32 currency = 1;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * 货币类型，取值参考 Currency
     *
     * Generated from protobuf field <code>int32 currency = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->currency = $var;

        return $this;
    }

    /**
     * 现金结余
     *
     * Generated from protobuf field <code>double cash = 2;</code>
     * @return float
     */
    public function getCash()
    {
        return $this->cash;
    }

    /**
     * 现金结余
     *
     * Generated from protobuf field <code>double cash = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setCash(float $var)
    {
        $this->cash = $var;

        return $this;
    }

    /**
     * 现金可提金额
     *
     * Generated from protobuf field <code>double availableBalance = 3;</code>
     * @return float
     */
    public function getAvailableBalance()
    {
        return $this->availableBalance;
    }

    /**
     * 现金可提金额
     *
     * Generated from protobuf field <code>double availableBalance = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAvailableBalance(float $var)
    {
        $this->availableBalance = $var;

        return $this;
    }

    /**
     * 现金购买力
     *
     * Generated from protobuf field <code>double netCashPower = 4;</code>
     * @return float
     */
    public function getNetCashPower()
    {
        return $this->netCashPower;
    }

    /**
     * 现金购买力
     *
     * Generated from protobuf field <code>double netCashPower = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setNetCashPower(float $var)
    {
        $this->netCashPower = $var;

        return $this;
    }

}

