<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use UnexpectedValueException;

/**
 *风险状态，共分 9 个等级，LEVEL1是最安全，LEVEL9是最危险
 *
 * Protobuf type <code>Trd_Common.CltRiskStatus</code>
 */
class CltRiskStatus
{
    /**
     *未知
     *
     * Generated from protobuf enum <code>CltRiskStatus_Unknown = 0;</code>
     */
    const CltRiskStatus_Unknown = 0;
    /**
     *非常安全
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level1 = 1;</code>
     */
    const CltRiskStatus_Level1 = 1;
    /**
     *安全
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level2 = 2;</code>
     */
    const CltRiskStatus_Level2 = 2;
    /**
     *较安全
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level3 = 3;</code>
     */
    const CltRiskStatus_Level3 = 3;
    /**
     *较低风险
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level4 = 4;</code>
     */
    const CltRiskStatus_Level4 = 4;
    /**
     *中等风险
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level5 = 5;</code>
     */
    const CltRiskStatus_Level5 = 5;
    /**
     *较高风险
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level6 = 6;</code>
     */
    const CltRiskStatus_Level6 = 6;
    /**
     *预警
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level7 = 7;</code>
     */
    const CltRiskStatus_Level7 = 7;
    /**
     *预警
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level8 = 8;</code>
     */
    const CltRiskStatus_Level8 = 8;
    /**
     *预警
     *
     * Generated from protobuf enum <code>CltRiskStatus_Level9 = 9;</code>
     */
    const CltRiskStatus_Level9 = 9;

    private static $valueToName = [
        self::CltRiskStatus_Unknown => 'CltRiskStatus_Unknown',
        self::CltRiskStatus_Level1 => 'CltRiskStatus_Level1',
        self::CltRiskStatus_Level2 => 'CltRiskStatus_Level2',
        self::CltRiskStatus_Level3 => 'CltRiskStatus_Level3',
        self::CltRiskStatus_Level4 => 'CltRiskStatus_Level4',
        self::CltRiskStatus_Level5 => 'CltRiskStatus_Level5',
        self::CltRiskStatus_Level6 => 'CltRiskStatus_Level6',
        self::CltRiskStatus_Level7 => 'CltRiskStatus_Level7',
        self::CltRiskStatus_Level8 => 'CltRiskStatus_Level8',
        self::CltRiskStatus_Level9 => 'CltRiskStatus_Level9',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

