<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use UnexpectedValueException;

/**
 *订单类型
 *
 * Protobuf type <code>Trd_Common.OrderType</code>
 */
class OrderType
{
    /**
     *未知类型
     *
     * Generated from protobuf enum <code>OrderType_Unknown = 0;</code>
     */
    const OrderType_Unknown = 0;
    /**
     *普通订单(港股的增强限价单、港股期权的限价单，A股限价委托、美股的限价单，港股期货的限价单，CME期货的限价单)。目前港股期权只能指定此订单类型。
     *
     * Generated from protobuf enum <code>OrderType_Normal = 1;</code>
     */
    const OrderType_Normal = 1;
    /**
     *市价订单(目前支持美股、港股正股、涡轮、牛熊、界内证)
     *
     * Generated from protobuf enum <code>OrderType_Market = 2;</code>
     */
    const OrderType_Market = 2;
    /**
     *绝对限价订单(目前仅港股)，只有价格完全匹配才成交，否则下单失败，比如你下价格为5元的买单，卖单价格必须也要是5元才能成交，低于5元也不能成交，下单失败。卖出同理
     *
     * Generated from protobuf enum <code>OrderType_AbsoluteLimit = 5;</code>
     */
    const OrderType_AbsoluteLimit = 5;
    /**
     *竞价订单(目前仅港股)，仅港股早盘竞价和收盘竞价有效，A股的早盘竞价订单类型不变还是OrderType_Normal
     *
     * Generated from protobuf enum <code>OrderType_Auction = 6;</code>
     */
    const OrderType_Auction = 6;
    /**
     *竞价限价订单(目前仅港股)，仅早盘竞价和收盘竞价有效，参与竞价，且要求满足指定价格才会成交
     *
     * Generated from protobuf enum <code>OrderType_AuctionLimit = 7;</code>
     */
    const OrderType_AuctionLimit = 7;
    /**
     *特别限价订单(目前仅港股)，成交规则同增强限价订单，且部分成交后，交易所自动撤销订单
     *
     * Generated from protobuf enum <code>OrderType_SpecialLimit = 8;</code>
     */
    const OrderType_SpecialLimit = 8;
    /**
     *特别限价且要求全部成交订单(目前仅港股)，要么全部成交，要么自动撤单
     *
     * Generated from protobuf enum <code>OrderType_SpecialLimit_All = 9;</code>
     */
    const OrderType_SpecialLimit_All = 9;
    /**
     * 止损市价单
     *
     * Generated from protobuf enum <code>OrderType_Stop = 10;</code>
     */
    const OrderType_Stop = 10;
    /**
     * 止损限价单
     *
     * Generated from protobuf enum <code>OrderType_StopLimit = 11;</code>
     */
    const OrderType_StopLimit = 11;
    /**
     * 触及市价单（止盈）
     *
     * Generated from protobuf enum <code>OrderType_MarketifTouched = 12;</code>
     */
    const OrderType_MarketifTouched = 12;
    /**
     * 触及限价单（止盈）
     *
     * Generated from protobuf enum <code>OrderType_LimitifTouched = 13;</code>
     */
    const OrderType_LimitifTouched = 13;
    /**
     * 跟踪止损市价单
     *
     * Generated from protobuf enum <code>OrderType_TrailingStop = 14;</code>
     */
    const OrderType_TrailingStop = 14;
    /**
     * 跟踪止损限价单
     *
     * Generated from protobuf enum <code>OrderType_TrailingStopLimit = 15;</code>
     */
    const OrderType_TrailingStopLimit = 15;
    /**
     * TWAP 市价单 
     *
     * Generated from protobuf enum <code>OrderType_TWAP_MARKET = 16;</code>
     */
    const OrderType_TWAP_MARKET = 16;
    /**
     * TWAP 限订单 
     *
     * Generated from protobuf enum <code>OrderType_TWAP_LIMIT = 17;</code>
     */
    const OrderType_TWAP_LIMIT = 17;
    /**
     * VWAP 市价单 
     *
     * Generated from protobuf enum <code>OrderType_VWAP_MARKET = 18;</code>
     */
    const OrderType_VWAP_MARKET = 18;
    /**
     * VWAP 限订单
     *
     * Generated from protobuf enum <code>OrderType_VWAP_LIMIT = 19;</code>
     */
    const OrderType_VWAP_LIMIT = 19;

    private static $valueToName = [
        self::OrderType_Unknown => 'OrderType_Unknown',
        self::OrderType_Normal => 'OrderType_Normal',
        self::OrderType_Market => 'OrderType_Market',
        self::OrderType_AbsoluteLimit => 'OrderType_AbsoluteLimit',
        self::OrderType_Auction => 'OrderType_Auction',
        self::OrderType_AuctionLimit => 'OrderType_AuctionLimit',
        self::OrderType_SpecialLimit => 'OrderType_SpecialLimit',
        self::OrderType_SpecialLimit_All => 'OrderType_SpecialLimit_All',
        self::OrderType_Stop => 'OrderType_Stop',
        self::OrderType_StopLimit => 'OrderType_StopLimit',
        self::OrderType_MarketifTouched => 'OrderType_MarketifTouched',
        self::OrderType_LimitifTouched => 'OrderType_LimitifTouched',
        self::OrderType_TrailingStop => 'OrderType_TrailingStop',
        self::OrderType_TrailingStopLimit => 'OrderType_TrailingStopLimit',
        self::OrderType_TWAP_MARKET => 'OrderType_TWAP_MARKET',
        self::OrderType_TWAP_LIMIT => 'OrderType_TWAP_LIMIT',
        self::OrderType_VWAP_MARKET => 'OrderType_VWAP_MARKET',
        self::OrderType_VWAP_LIMIT => 'OrderType_VWAP_LIMIT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

