<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *订单结构
 *
 * Generated from protobuf message <code>Trd_Common.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     *交易方向, 参见TrdSide的枚举定义
     *
     * Generated from protobuf field <code>int32 trdSide = 1;</code>
     */
    protected $trdSide = 0;
    /**
     *订单类型, 参见OrderType的枚举定义
     *
     * Generated from protobuf field <code>int32 orderType = 2;</code>
     */
    protected $orderType = 0;
    /**
     *订单状态, 参见OrderStatus的枚举定义
     *
     * Generated from protobuf field <code>int32 orderStatus = 3;</code>
     */
    protected $orderStatus = 0;
    /**
     *订单号
     *
     * Generated from protobuf field <code>uint64 orderID = 4;</code>
     */
    protected $orderID = 0;
    /**
     *扩展订单号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string orderIDEx = 5;</code>
     */
    protected $orderIDEx = '';
    /**
     *代码
     *
     * Generated from protobuf field <code>string code = 6;</code>
     */
    protected $code = '';
    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 7;</code>
     */
    protected $name = '';
    /**
     *订单数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double qty = 8;</code>
     */
    protected $qty = 0.0;
    /**
     *订单价格，3位精度
     *
     * Generated from protobuf field <code>double price = 9;</code>
     */
    protected $price = 0.0;
    /**
     *创建时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string createTime = 10;</code>
     */
    protected $createTime = '';
    /**
     *最后更新时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string updateTime = 11;</code>
     */
    protected $updateTime = '';
    /**
     *成交数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double fillQty = 12;</code>
     */
    protected $fillQty = 0.0;
    /**
     *成交均价，无精度限制
     *
     * Generated from protobuf field <code>double fillAvgPrice = 13;</code>
     */
    protected $fillAvgPrice = 0.0;
    /**
     *最后的错误描述，如果有错误，会有此描述最后一次错误的原因，无错误为空
     *
     * Generated from protobuf field <code>string lastErrMsg = 14;</code>
     */
    protected $lastErrMsg = '';
    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 15;</code>
     */
    protected $secMarket = 0;
    /**
     *创建时间戳
     *
     * Generated from protobuf field <code>double createTimestamp = 16;</code>
     */
    protected $createTimestamp = 0.0;
    /**
     *最后更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 17;</code>
     */
    protected $updateTimestamp = 0.0;
    /**
     *用户备注字符串，最大长度64字节
     *
     * Generated from protobuf field <code>string remark = 18;</code>
     */
    protected $remark = '';
    /**
     *订单期限，参考 TimeInForce 类的定义
     *
     * Generated from protobuf field <code>int32 timeInForce = 19;</code>
     */
    protected $timeInForce = 0;
    /**
     *是否允许美股订单盘前盘后成交
     *
     * Generated from protobuf field <code>bool fillOutsideRTH = 20;</code>
     */
    protected $fillOutsideRTH = false;
    /**
     *触发价格
     *
     * Generated from protobuf field <code>double auxPrice = 21;</code>
     */
    protected $auxPrice = 0.0;
    /**
     *跟踪类型, 参见Trd_Common.TrailType的枚举定义
     *
     * Generated from protobuf field <code>int32 trailType = 22;</code>
     */
    protected $trailType = 0;
    /**
     *跟踪金额/百分比
     *
     * Generated from protobuf field <code>double trailValue = 23;</code>
     */
    protected $trailValue = 0.0;
    /**
     *指定价差
     *
     * Generated from protobuf field <code>double trailSpread = 24;</code>
     */
    protected $trailSpread = 0.0;
    /**
     * 货币类型，取值参考 Currency
     *
     * Generated from protobuf field <code>int32 currency = 25;</code>
     */
    protected $currency = 0;
    /**
     *交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 trdMarket = 26;</code>
     */
    protected $trdMarket = 0;
    /**
     *美股订单时段, 参见Common.Session的枚举定义
     *
     * Generated from protobuf field <code>int32 session = 27;</code>
     */
    protected $session = 0;
    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 28;</code>
     */
    protected $jpAccType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $trdSide
     *          交易方向, 参见TrdSide的枚举定义
     *     @type int $orderType
     *          订单类型, 参见OrderType的枚举定义
     *     @type int $orderStatus
     *          订单状态, 参见OrderStatus的枚举定义
     *     @type int|string $orderID
     *          订单号
     *     @type string $orderIDEx
     *          扩展订单号(仅查问题时备用)
     *     @type string $code
     *          代码
     *     @type string $name
     *          名称
     *     @type float $qty
     *          订单数量，2位精度，期权单位是"张"
     *     @type float $price
     *          订单价格，3位精度
     *     @type string $createTime
     *          创建时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *     @type string $updateTime
     *          最后更新时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *     @type float $fillQty
     *          成交数量，2位精度，期权单位是"张"
     *     @type float $fillAvgPrice
     *          成交均价，无精度限制
     *     @type string $lastErrMsg
     *          最后的错误描述，如果有错误，会有此描述最后一次错误的原因，无错误为空
     *     @type int $secMarket
     *          证券所属市场，参见TrdSecMarket的枚举定义
     *     @type float $createTimestamp
     *          创建时间戳
     *     @type float $updateTimestamp
     *          最后更新时间戳
     *     @type string $remark
     *          用户备注字符串，最大长度64字节
     *     @type int $timeInForce
     *          订单期限，参考 TimeInForce 类的定义
     *     @type bool $fillOutsideRTH
     *          是否允许美股订单盘前盘后成交
     *     @type float $auxPrice
     *          触发价格
     *     @type int $trailType
     *          跟踪类型, 参见Trd_Common.TrailType的枚举定义
     *     @type float $trailValue
     *          跟踪金额/百分比
     *     @type float $trailSpread
     *          指定价差
     *     @type int $currency
     *           货币类型，取值参考 Currency
     *     @type int $trdMarket
     *          交易市场, 参见TrdMarket的枚举定义
     *     @type int $session
     *          美股订单时段, 参见Common.Session的枚举定义
     *     @type int $jpAccType
     *          JP子账户类型，取值见 TrdSubAccType
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *交易方向, 参见TrdSide的枚举定义
     *
     * Generated from protobuf field <code>int32 trdSide = 1;</code>
     * @return int
     */
    public function getTrdSide()
    {
        return $this->trdSide;
    }

    /**
     *交易方向, 参见TrdSide的枚举定义
     *
     * Generated from protobuf field <code>int32 trdSide = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTrdSide(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->trdSide = $var;

        return $this;
    }

    /**
     *订单类型, 参见OrderType的枚举定义
     *
     * Generated from protobuf field <code>int32 orderType = 2;</code>
     * @return int
     */
    public function getOrderType()
    {
        return $this->orderType;
    }

    /**
     *订单类型, 参见OrderType的枚举定义
     *
     * Generated from protobuf field <code>int32 orderType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->orderType = $var;

        return $this;
    }

    /**
     *订单状态, 参见OrderStatus的枚举定义
     *
     * Generated from protobuf field <code>int32 orderStatus = 3;</code>
     * @return int
     */
    public function getOrderStatus()
    {
        return $this->orderStatus;
    }

    /**
     *订单状态, 参见OrderStatus的枚举定义
     *
     * Generated from protobuf field <code>int32 orderStatus = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderStatus(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->orderStatus = $var;

        return $this;
    }

    /**
     *订单号
     *
     * Generated from protobuf field <code>uint64 orderID = 4;</code>
     * @return int|string
     */
    public function getOrderID()
    {
        return $this->orderID;
    }

    /**
     *订单号
     *
     * Generated from protobuf field <code>uint64 orderID = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->orderID = $var;

        return $this;
    }

    /**
     *扩展订单号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string orderIDEx = 5;</code>
     * @return string
     */
    public function getOrderIDEx()
    {
        return $this->orderIDEx;
    }

    /**
     *扩展订单号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string orderIDEx = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderIDEx(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->orderIDEx = $var;

        return $this;
    }

    /**
     *代码
     *
     * Generated from protobuf field <code>string code = 6;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *代码
     *
     * Generated from protobuf field <code>string code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->code = $var;

        return $this;
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 7;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     *订单数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double qty = 8;</code>
     * @return float
     */
    public function getQty()
    {
        return $this->qty;
    }

    /**
     *订单数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double qty = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setQty(float $var)
    {
        $this->qty = $var;

        return $this;
    }

    /**
     *订单价格，3位精度
     *
     * Generated from protobuf field <code>double price = 9;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     *订单价格，3位精度
     *
     * Generated from protobuf field <code>double price = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice(float $var)
    {
        $this->price = $var;

        return $this;
    }

    /**
     *创建时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string createTime = 10;</code>
     * @return string
     */
    public function getCreateTime()
    {
        return $this->createTime;
    }

    /**
     *创建时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string createTime = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->createTime = $var;

        return $this;
    }

    /**
     *最后更新时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string updateTime = 11;</code>
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->updateTime;
    }

    /**
     *最后更新时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string updateTime = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->updateTime = $var;

        return $this;
    }

    /**
     *成交数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double fillQty = 12;</code>
     * @return float
     */
    public function getFillQty()
    {
        return $this->fillQty;
    }

    /**
     *成交数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double fillQty = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setFillQty(float $var)
    {
        $this->fillQty = $var;

        return $this;
    }

    /**
     *成交均价，无精度限制
     *
     * Generated from protobuf field <code>double fillAvgPrice = 13;</code>
     * @return float
     */
    public function getFillAvgPrice()
    {
        return $this->fillAvgPrice;
    }

    /**
     *成交均价，无精度限制
     *
     * Generated from protobuf field <code>double fillAvgPrice = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setFillAvgPrice(float $var)
    {
        $this->fillAvgPrice = $var;

        return $this;
    }

    /**
     *最后的错误描述，如果有错误，会有此描述最后一次错误的原因，无错误为空
     *
     * Generated from protobuf field <code>string lastErrMsg = 14;</code>
     * @return string
     */
    public function getLastErrMsg()
    {
        return $this->lastErrMsg;
    }

    /**
     *最后的错误描述，如果有错误，会有此描述最后一次错误的原因，无错误为空
     *
     * Generated from protobuf field <code>string lastErrMsg = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setLastErrMsg(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->lastErrMsg = $var;

        return $this;
    }

    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 15;</code>
     * @return int
     */
    public function getSecMarket()
    {
        return $this->secMarket;
    }

    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setSecMarket(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->secMarket = $var;

        return $this;
    }

    /**
     *创建时间戳
     *
     * Generated from protobuf field <code>double createTimestamp = 16;</code>
     * @return float
     */
    public function getCreateTimestamp()
    {
        return $this->createTimestamp;
    }

    /**
     *创建时间戳
     *
     * Generated from protobuf field <code>double createTimestamp = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setCreateTimestamp(float $var)
    {
        $this->createTimestamp = $var;

        return $this;
    }

    /**
     *最后更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 17;</code>
     * @return float
     */
    public function getUpdateTimestamp()
    {
        return $this->updateTimestamp;
    }

    /**
     *最后更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 17;</code>
     * @param float $var
     * @return $this
     */
    public function setUpdateTimestamp(float $var)
    {
        $this->updateTimestamp = $var;

        return $this;
    }

    /**
     *用户备注字符串，最大长度64字节
     *
     * Generated from protobuf field <code>string remark = 18;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     *用户备注字符串，最大长度64字节
     *
     * Generated from protobuf field <code>string remark = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->remark = $var;

        return $this;
    }

    /**
     *订单期限，参考 TimeInForce 类的定义
     *
     * Generated from protobuf field <code>int32 timeInForce = 19;</code>
     * @return int
     */
    public function getTimeInForce()
    {
        return $this->timeInForce;
    }

    /**
     *订单期限，参考 TimeInForce 类的定义
     *
     * Generated from protobuf field <code>int32 timeInForce = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeInForce(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->timeInForce = $var;

        return $this;
    }

    /**
     *是否允许美股订单盘前盘后成交
     *
     * Generated from protobuf field <code>bool fillOutsideRTH = 20;</code>
     * @return bool
     */
    public function getFillOutsideRTH()
    {
        return $this->fillOutsideRTH;
    }

    /**
     *是否允许美股订单盘前盘后成交
     *
     * Generated from protobuf field <code>bool fillOutsideRTH = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setFillOutsideRTH(bool $var)
    {
        $this->fillOutsideRTH = $var;

        return $this;
    }

    /**
     *触发价格
     *
     * Generated from protobuf field <code>double auxPrice = 21;</code>
     * @return float
     */
    public function getAuxPrice()
    {
        return $this->auxPrice;
    }

    /**
     *触发价格
     *
     * Generated from protobuf field <code>double auxPrice = 21;</code>
     * @param float $var
     * @return $this
     */
    public function setAuxPrice(float $var)
    {
        $this->auxPrice = $var;

        return $this;
    }

    /**
     *跟踪类型, 参见Trd_Common.TrailType的枚举定义
     *
     * Generated from protobuf field <code>int32 trailType = 22;</code>
     * @return int
     */
    public function getTrailType()
    {
        return $this->trailType;
    }

    /**
     *跟踪类型, 参见Trd_Common.TrailType的枚举定义
     *
     * Generated from protobuf field <code>int32 trailType = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setTrailType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->trailType = $var;

        return $this;
    }

    /**
     *跟踪金额/百分比
     *
     * Generated from protobuf field <code>double trailValue = 23;</code>
     * @return float
     */
    public function getTrailValue()
    {
        return $this->trailValue;
    }

    /**
     *跟踪金额/百分比
     *
     * Generated from protobuf field <code>double trailValue = 23;</code>
     * @param float $var
     * @return $this
     */
    public function setTrailValue(float $var)
    {
        $this->trailValue = $var;

        return $this;
    }

    /**
     *指定价差
     *
     * Generated from protobuf field <code>double trailSpread = 24;</code>
     * @return float
     */
    public function getTrailSpread()
    {
        return $this->trailSpread;
    }

    /**
     *指定价差
     *
     * Generated from protobuf field <code>double trailSpread = 24;</code>
     * @param float $var
     * @return $this
     */
    public function setTrailSpread(float $var)
    {
        $this->trailSpread = $var;

        return $this;
    }

    /**
     * 货币类型，取值参考 Currency
     *
     * Generated from protobuf field <code>int32 currency = 25;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * 货币类型，取值参考 Currency
     *
     * Generated from protobuf field <code>int32 currency = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->currency = $var;

        return $this;
    }

    /**
     *交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 trdMarket = 26;</code>
     * @return int
     */
    public function getTrdMarket()
    {
        return $this->trdMarket;
    }

    /**
     *交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 trdMarket = 26;</code>
     * @param int $var
     * @return $this
     */
    public function setTrdMarket(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->trdMarket = $var;

        return $this;
    }

    /**
     *美股订单时段, 参见Common.Session的枚举定义
     *
     * Generated from protobuf field <code>int32 session = 27;</code>
     * @return int
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     *美股订单时段, 参见Common.Session的枚举定义
     *
     * Generated from protobuf field <code>int32 session = 27;</code>
     * @param int $var
     * @return $this
     */
    public function setSession(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->session = $var;

        return $this;
    }

    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 28;</code>
     * @return int
     */
    public function getJpAccType()
    {
        return $this->jpAccType;
    }

    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 28;</code>
     * @param int $var
     * @return $this
     */
    public function setJpAccType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->jpAccType = $var;

        return $this;
    }

}

