<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_Common.OrderFee</code>
 */
class OrderFee extends \Google\Protobuf\Internal\Message
{
    /**
     *扩展订单号
     *
     * Generated from protobuf field <code>string orderIDEx = 1;</code>
     */
    protected $orderIDEx = '';
    /**
     *费用总额
     *
     * Generated from protobuf field <code>double feeAmount = 2;</code>
     */
    protected $feeAmount = 0.0;
    /**
     *费用明细
     *
     * Generated from protobuf field <code>repeated .Trd_Common.OrderFeeItem feeList = 3;</code>
     */
    private $feeList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderIDEx
     *          扩展订单号
     *     @type float $feeAmount
     *          费用总额
     *     @type \Futu\Trd_Common\OrderFeeItem[] $feeList
     *          费用明细
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *扩展订单号
     *
     * Generated from protobuf field <code>string orderIDEx = 1;</code>
     * @return string
     */
    public function getOrderIDEx()
    {
        return $this->orderIDEx;
    }

    /**
     *扩展订单号
     *
     * Generated from protobuf field <code>string orderIDEx = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderIDEx(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->orderIDEx = $var;

        return $this;
    }

    /**
     *费用总额
     *
     * Generated from protobuf field <code>double feeAmount = 2;</code>
     * @return float
     */
    public function getFeeAmount()
    {
        return $this->feeAmount;
    }

    /**
     *费用总额
     *
     * Generated from protobuf field <code>double feeAmount = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setFeeAmount(float $var)
    {
        $this->feeAmount = $var;

        return $this;
    }

    /**
     *费用明细
     *
     * Generated from protobuf field <code>repeated .Trd_Common.OrderFeeItem feeList = 3;</code>
     * @return RepeatedField<\Futu\Trd_Common\OrderFeeItem>
     */
    public function getFeeList()
    {
        return $this->feeList;
    }

    /**
     *费用明细
     *
     * Generated from protobuf field <code>repeated .Trd_Common.OrderFeeItem feeList = 3;</code>
     * @param \Futu\Trd_Common\OrderFeeItem[] $var
     * @return $this
     */
    public function setFeeList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Trd_Common\OrderFeeItem::class);
        $this->feeList = $arr;

        return $this;
    }

}

