<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *成交结构
 *
 * Generated from protobuf message <code>Trd_Common.OrderFill</code>
 */
class OrderFill extends \Google\Protobuf\Internal\Message
{
    /**
     *交易方向, 参见TrdSide的枚举定义
     *
     * Generated from protobuf field <code>int32 trdSide = 1;</code>
     */
    protected $trdSide = 0;
    /**
     *成交号
     *
     * Generated from protobuf field <code>uint64 fillID = 2;</code>
     */
    protected $fillID = 0;
    /**
     *扩展成交号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string fillIDEx = 3;</code>
     */
    protected $fillIDEx = '';
    /**
     *订单号
     *
     * Generated from protobuf field <code>uint64 orderID = 4;</code>
     */
    protected $orderID = 0;
    /**
     *扩展订单号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string orderIDEx = 5;</code>
     */
    protected $orderIDEx = '';
    /**
     *代码
     *
     * Generated from protobuf field <code>string code = 6;</code>
     */
    protected $code = '';
    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 7;</code>
     */
    protected $name = '';
    /**
     *成交数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double qty = 8;</code>
     */
    protected $qty = 0.0;
    /**
     *成交价格，3位精度
     *
     * Generated from protobuf field <code>double price = 9;</code>
     */
    protected $price = 0.0;
    /**
     *创建时间（成交时间），严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string createTime = 10;</code>
     */
    protected $createTime = '';
    /**
     *对手经纪号，港股有效
     *
     * Generated from protobuf field <code>int32 counterBrokerID = 11;</code>
     */
    protected $counterBrokerID = 0;
    /**
     *对手经纪名称，港股有效
     *
     * Generated from protobuf field <code>string counterBrokerName = 12;</code>
     */
    protected $counterBrokerName = '';
    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 13;</code>
     */
    protected $secMarket = 0;
    /**
     *创建时间戳
     *
     * Generated from protobuf field <code>double createTimestamp = 14;</code>
     */
    protected $createTimestamp = 0.0;
    /**
     *最后更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 15;</code>
     */
    protected $updateTimestamp = 0.0;
    /**
     *成交状态, 参见OrderFillStatus的枚举定义
     *
     * Generated from protobuf field <code>int32 status = 16;</code>
     */
    protected $status = 0;
    /**
     *交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 trdMarket = 17;</code>
     */
    protected $trdMarket = 0;
    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 18;</code>
     */
    protected $jpAccType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $trdSide
     *          交易方向, 参见TrdSide的枚举定义
     *     @type int|string $fillID
     *          成交号
     *     @type string $fillIDEx
     *          扩展成交号(仅查问题时备用)
     *     @type int|string $orderID
     *          订单号
     *     @type string $orderIDEx
     *          扩展订单号(仅查问题时备用)
     *     @type string $code
     *          代码
     *     @type string $name
     *          名称
     *     @type float $qty
     *          成交数量，2位精度，期权单位是"张"
     *     @type float $price
     *          成交价格，3位精度
     *     @type string $createTime
     *          创建时间（成交时间），严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *     @type int $counterBrokerID
     *          对手经纪号，港股有效
     *     @type string $counterBrokerName
     *          对手经纪名称，港股有效
     *     @type int $secMarket
     *          证券所属市场，参见TrdSecMarket的枚举定义
     *     @type float $createTimestamp
     *          创建时间戳
     *     @type float $updateTimestamp
     *          最后更新时间戳
     *     @type int $status
     *          成交状态, 参见OrderFillStatus的枚举定义
     *     @type int $trdMarket
     *          交易市场, 参见TrdMarket的枚举定义
     *     @type int $jpAccType
     *          JP子账户类型，取值见 TrdSubAccType
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *交易方向, 参见TrdSide的枚举定义
     *
     * Generated from protobuf field <code>int32 trdSide = 1;</code>
     * @return int
     */
    public function getTrdSide()
    {
        return $this->trdSide;
    }

    /**
     *交易方向, 参见TrdSide的枚举定义
     *
     * Generated from protobuf field <code>int32 trdSide = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTrdSide(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->trdSide = $var;

        return $this;
    }

    /**
     *成交号
     *
     * Generated from protobuf field <code>uint64 fillID = 2;</code>
     * @return int|string
     */
    public function getFillID()
    {
        return $this->fillID;
    }

    /**
     *成交号
     *
     * Generated from protobuf field <code>uint64 fillID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFillID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->fillID = $var;

        return $this;
    }

    /**
     *扩展成交号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string fillIDEx = 3;</code>
     * @return string
     */
    public function getFillIDEx()
    {
        return $this->fillIDEx;
    }

    /**
     *扩展成交号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string fillIDEx = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFillIDEx(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->fillIDEx = $var;

        return $this;
    }

    /**
     *订单号
     *
     * Generated from protobuf field <code>uint64 orderID = 4;</code>
     * @return int|string
     */
    public function getOrderID()
    {
        return $this->orderID;
    }

    /**
     *订单号
     *
     * Generated from protobuf field <code>uint64 orderID = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->orderID = $var;

        return $this;
    }

    /**
     *扩展订单号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string orderIDEx = 5;</code>
     * @return string
     */
    public function getOrderIDEx()
    {
        return $this->orderIDEx;
    }

    /**
     *扩展订单号(仅查问题时备用)
     *
     * Generated from protobuf field <code>string orderIDEx = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderIDEx(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->orderIDEx = $var;

        return $this;
    }

    /**
     *代码
     *
     * Generated from protobuf field <code>string code = 6;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *代码
     *
     * Generated from protobuf field <code>string code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->code = $var;

        return $this;
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 7;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     *成交数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double qty = 8;</code>
     * @return float
     */
    public function getQty()
    {
        return $this->qty;
    }

    /**
     *成交数量，2位精度，期权单位是"张"
     *
     * Generated from protobuf field <code>double qty = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setQty(float $var)
    {
        $this->qty = $var;

        return $this;
    }

    /**
     *成交价格，3位精度
     *
     * Generated from protobuf field <code>double price = 9;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     *成交价格，3位精度
     *
     * Generated from protobuf field <code>double price = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice(float $var)
    {
        $this->price = $var;

        return $this;
    }

    /**
     *创建时间（成交时间），严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string createTime = 10;</code>
     * @return string
     */
    public function getCreateTime()
    {
        return $this->createTime;
    }

    /**
     *创建时间（成交时间），严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传
     *
     * Generated from protobuf field <code>string createTime = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->createTime = $var;

        return $this;
    }

    /**
     *对手经纪号，港股有效
     *
     * Generated from protobuf field <code>int32 counterBrokerID = 11;</code>
     * @return int
     */
    public function getCounterBrokerID()
    {
        return $this->counterBrokerID;
    }

    /**
     *对手经纪号，港股有效
     *
     * Generated from protobuf field <code>int32 counterBrokerID = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCounterBrokerID(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->counterBrokerID = $var;

        return $this;
    }

    /**
     *对手经纪名称，港股有效
     *
     * Generated from protobuf field <code>string counterBrokerName = 12;</code>
     * @return string
     */
    public function getCounterBrokerName()
    {
        return $this->counterBrokerName;
    }

    /**
     *对手经纪名称，港股有效
     *
     * Generated from protobuf field <code>string counterBrokerName = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCounterBrokerName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->counterBrokerName = $var;

        return $this;
    }

    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 13;</code>
     * @return int
     */
    public function getSecMarket()
    {
        return $this->secMarket;
    }

    /**
     *证券所属市场，参见TrdSecMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 secMarket = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setSecMarket(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->secMarket = $var;

        return $this;
    }

    /**
     *创建时间戳
     *
     * Generated from protobuf field <code>double createTimestamp = 14;</code>
     * @return float
     */
    public function getCreateTimestamp()
    {
        return $this->createTimestamp;
    }

    /**
     *创建时间戳
     *
     * Generated from protobuf field <code>double createTimestamp = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setCreateTimestamp(float $var)
    {
        $this->createTimestamp = $var;

        return $this;
    }

    /**
     *最后更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 15;</code>
     * @return float
     */
    public function getUpdateTimestamp()
    {
        return $this->updateTimestamp;
    }

    /**
     *最后更新时间戳
     *
     * Generated from protobuf field <code>double updateTimestamp = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setUpdateTimestamp(float $var)
    {
        $this->updateTimestamp = $var;

        return $this;
    }

    /**
     *成交状态, 参见OrderFillStatus的枚举定义
     *
     * Generated from protobuf field <code>int32 status = 16;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *成交状态, 参见OrderFillStatus的枚举定义
     *
     * Generated from protobuf field <code>int32 status = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     *交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 trdMarket = 17;</code>
     * @return int
     */
    public function getTrdMarket()
    {
        return $this->trdMarket;
    }

    /**
     *交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 trdMarket = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setTrdMarket(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->trdMarket = $var;

        return $this;
    }

    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 18;</code>
     * @return int
     */
    public function getJpAccType()
    {
        return $this->jpAccType;
    }

    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setJpAccType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->jpAccType = $var;

        return $this;
    }

}

