<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use UnexpectedValueException;

/**
 *模拟交易账户类型
 *
 * Protobuf type <code>Trd_Common.SimAccType</code>
 */
class SimAccType
{
    /**
     *未知
     *
     * Generated from protobuf enum <code>SimAccType_Unknown = 0;</code>
     */
    const SimAccType_Unknown = 0;
    /**
     *股票模拟账户（仅用于交易证券类产品，不支持交易期权）
     *
     * Generated from protobuf enum <code>SimAccType_Stock = 1;</code>
     */
    const SimAccType_Stock = 1;
    /**
     *期权模拟账户（仅用于交易期权，不支持交易股票证券类产品）
     *
     * Generated from protobuf enum <code>SimAccType_Option = 2;</code>
     */
    const SimAccType_Option = 2;
    /**
     *期货模拟账户
     *
     * Generated from protobuf enum <code>SimAccType_Futures = 3;</code>
     */
    const SimAccType_Futures = 3;

    private static $valueToName = [
        self::SimAccType_Unknown => 'SimAccType_Unknown',
        self::SimAccType_Stock => 'SimAccType_Stock',
        self::SimAccType_Option => 'SimAccType_Option',
        self::SimAccType_Futures => 'SimAccType_Futures',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

