<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use UnexpectedValueException;

/**
 *订单有效期
 *
 * Protobuf type <code>Trd_Common.TimeInForce</code>
 */
class TimeInForce
{
    /**
     * 当日有效
     *
     * Generated from protobuf enum <code>TimeInForce_DAY = 0;</code>
     */
    const TimeInForce_DAY = 0;
    /**
     * 撤单前有效，最多持续90自然日。
     *
     * Generated from protobuf enum <code>TimeInForce_GTC = 1;</code>
     */
    const TimeInForce_GTC = 1;

    private static $valueToName = [
        self::TimeInForce_DAY => 'TimeInForce_DAY',
        self::TimeInForce_GTC => 'TimeInForce_GTC',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

