<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use UnexpectedValueException;

/**
 *交易账户类型
 *
 * Protobuf type <code>Trd_Common.TrdAccType</code>
 */
class TrdAccType
{
    /**
     *未知类型
     *
     * Generated from protobuf enum <code>TrdAccType_Unknown = 0;</code>
     */
    const TrdAccType_Unknown = 0;
    /**
     *现金账户
     *
     * Generated from protobuf enum <code>TrdAccType_Cash = 1;</code>
     */
    const TrdAccType_Cash = 1;
    /**
     *保证金账户
     *
     * Generated from protobuf enum <code>TrdAccType_Margin = 2;</code>
     */
    const TrdAccType_Margin = 2;
    /**
     *加拿大免税账户
     *
     * Generated from protobuf enum <code>TrdAccType_TFSA = 3;</code>
     */
    const TrdAccType_TFSA = 3;
    /**
     *加拿大注册退休账户
     *
     * Generated from protobuf enum <code>TrdAccType_RRSP = 4;</code>
     */
    const TrdAccType_RRSP = 4;
    /**
     *加拿大配偶退休账户
     *
     * Generated from protobuf enum <code>TrdAccType_SRRSP = 5;</code>
     */
    const TrdAccType_SRRSP = 5;
    /**
     *日本衍生品账户
     *
     * Generated from protobuf enum <code>TrdAccType_Derivatives = 6;</code>
     */
    const TrdAccType_Derivatives = 6;

    private static $valueToName = [
        self::TrdAccType_Unknown => 'TrdAccType_Unknown',
        self::TrdAccType_Cash => 'TrdAccType_Cash',
        self::TrdAccType_Margin => 'TrdAccType_Margin',
        self::TrdAccType_TFSA => 'TrdAccType_TFSA',
        self::TrdAccType_RRSP => 'TrdAccType_RRSP',
        self::TrdAccType_SRRSP => 'TrdAccType_SRRSP',
        self::TrdAccType_Derivatives => 'TrdAccType_Derivatives',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

