<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use UnexpectedValueException;

/**
 * 账户类型
 *
 * Protobuf type <code>Trd_Common.TrdAccRole</code>
 */
class TrdAccRole
{
    /**
     *未知
     *
     * Generated from protobuf enum <code>TrdAccRole_Unknown = 0;</code>
     */
    const TrdAccRole_Unknown = 0;
    /**
     *普通账户
     *
     * Generated from protobuf enum <code>TrdAccRole_Normal = 1;</code>
     */
    const TrdAccRole_Normal = 1;
    /**
     *主账户
     *
     * Generated from protobuf enum <code>TrdAccRole_Master = 2;</code>
     */
    const TrdAccRole_Master = 2;
    /**
     *IPO 账户，仅MY券商
     *
     * Generated from protobuf enum <code>TrdAccRole_IPO = 3;</code>
     */
    const TrdAccRole_IPO = 3;

    private static $valueToName = [
        self::TrdAccRole_Unknown => 'TrdAccRole_Unknown',
        self::TrdAccRole_Normal => 'TrdAccRole_Normal',
        self::TrdAccRole_Master => 'TrdAccRole_Master',
        self::TrdAccRole_IPO => 'TrdAccRole_IPO',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

