<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *交易业务账户结构
 *
 * Generated from protobuf message <code>Trd_Common.TrdAcc</code>
 */
class TrdAcc extends \Google\Protobuf\Internal\Message
{
    /**
     *交易环境，参见TrdEnv的枚举定义
     *
     * Generated from protobuf field <code>int32 trdEnv = 1;</code>
     */
    protected $trdEnv = 0;
    /**
     *业务账号
     *
     * Generated from protobuf field <code>uint64 accID = 2;</code>
     */
    protected $accID = 0;
    /**
     *业务账户支持的交易市场权限，即此账户能交易那些市场, 可拥有多个交易市场权限，目前仅单个，取值参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>repeated int32 trdMarketAuthList = 3;</code>
     */
    private $trdMarketAuthList;
    /**
     *账户类型，取值见TrdAccType
     *
     * Generated from protobuf field <code>int32 accType = 4;</code>
     */
    protected $accType = 0;
    /**
     *卡号
     *
     * Generated from protobuf field <code>string cardNum = 5;</code>
     */
    protected $cardNum = '';
    /**
     *所属券商，取值见SecurityFirm
     *
     * Generated from protobuf field <code>int32 securityFirm = 6;</code>
     */
    protected $securityFirm = 0;
    /**
     *模拟交易账号类型，取值见SimAccType
     *
     * Generated from protobuf field <code>int32 simAccType = 7;</code>
     */
    protected $simAccType = 0;
    /**
     *所属综合账户卡号
     *
     * Generated from protobuf field <code>string uniCardNum = 8;</code>
     */
    protected $uniCardNum = '';
    /**
     *账号状态，取值见TrdAccStatus
     *
     * Generated from protobuf field <code>int32 accStatus = 9;</code>
     */
    protected $accStatus = 0;
    /**
     *账号分类，是不是主账号，取值见TrdAccRole
     *
     * Generated from protobuf field <code>int32 accRole = 10;</code>
     */
    protected $accRole = 0;
    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 11;</code>
     */
    protected $jpAccType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $trdEnv
     *          交易环境，参见TrdEnv的枚举定义
     *     @type int|string $accID
     *          业务账号
     *     @type int[] $trdMarketAuthList
     *          业务账户支持的交易市场权限，即此账户能交易那些市场, 可拥有多个交易市场权限，目前仅单个，取值参见TrdMarket的枚举定义
     *     @type int $accType
     *          账户类型，取值见TrdAccType
     *     @type string $cardNum
     *          卡号
     *     @type int $securityFirm
     *          所属券商，取值见SecurityFirm
     *     @type int $simAccType
     *          模拟交易账号类型，取值见SimAccType
     *     @type string $uniCardNum
     *          所属综合账户卡号
     *     @type int $accStatus
     *          账号状态，取值见TrdAccStatus
     *     @type int $accRole
     *          账号分类，是不是主账号，取值见TrdAccRole
     *     @type int $jpAccType
     *          JP子账户类型，取值见 TrdSubAccType
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *交易环境，参见TrdEnv的枚举定义
     *
     * Generated from protobuf field <code>int32 trdEnv = 1;</code>
     * @return int
     */
    public function getTrdEnv()
    {
        return $this->trdEnv;
    }

    /**
     *交易环境，参见TrdEnv的枚举定义
     *
     * Generated from protobuf field <code>int32 trdEnv = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTrdEnv(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->trdEnv = $var;

        return $this;
    }

    /**
     *业务账号
     *
     * Generated from protobuf field <code>uint64 accID = 2;</code>
     * @return int|string
     */
    public function getAccID()
    {
        return $this->accID;
    }

    /**
     *业务账号
     *
     * Generated from protobuf field <code>uint64 accID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAccID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->accID = $var;

        return $this;
    }

    /**
     *业务账户支持的交易市场权限，即此账户能交易那些市场, 可拥有多个交易市场权限，目前仅单个，取值参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>repeated int32 trdMarketAuthList = 3;</code>
     * @return RepeatedField<int>
     */
    public function getTrdMarketAuthList()
    {
        return $this->trdMarketAuthList;
    }

    /**
     *业务账户支持的交易市场权限，即此账户能交易那些市场, 可拥有多个交易市场权限，目前仅单个，取值参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>repeated int32 trdMarketAuthList = 3;</code>
     * @param int[] $var
     * @return $this
     */
    public function setTrdMarketAuthList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->trdMarketAuthList = $arr;

        return $this;
    }

    /**
     *账户类型，取值见TrdAccType
     *
     * Generated from protobuf field <code>int32 accType = 4;</code>
     * @return int
     */
    public function getAccType()
    {
        return $this->accType;
    }

    /**
     *账户类型，取值见TrdAccType
     *
     * Generated from protobuf field <code>int32 accType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAccType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->accType = $var;

        return $this;
    }

    /**
     *卡号
     *
     * Generated from protobuf field <code>string cardNum = 5;</code>
     * @return string
     */
    public function getCardNum()
    {
        return $this->cardNum;
    }

    /**
     *卡号
     *
     * Generated from protobuf field <code>string cardNum = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCardNum(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cardNum = $var;

        return $this;
    }

    /**
     *所属券商，取值见SecurityFirm
     *
     * Generated from protobuf field <code>int32 securityFirm = 6;</code>
     * @return int
     */
    public function getSecurityFirm()
    {
        return $this->securityFirm;
    }

    /**
     *所属券商，取值见SecurityFirm
     *
     * Generated from protobuf field <code>int32 securityFirm = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSecurityFirm(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->securityFirm = $var;

        return $this;
    }

    /**
     *模拟交易账号类型，取值见SimAccType
     *
     * Generated from protobuf field <code>int32 simAccType = 7;</code>
     * @return int
     */
    public function getSimAccType()
    {
        return $this->simAccType;
    }

    /**
     *模拟交易账号类型，取值见SimAccType
     *
     * Generated from protobuf field <code>int32 simAccType = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSimAccType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->simAccType = $var;

        return $this;
    }

    /**
     *所属综合账户卡号
     *
     * Generated from protobuf field <code>string uniCardNum = 8;</code>
     * @return string
     */
    public function getUniCardNum()
    {
        return $this->uniCardNum;
    }

    /**
     *所属综合账户卡号
     *
     * Generated from protobuf field <code>string uniCardNum = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUniCardNum(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->uniCardNum = $var;

        return $this;
    }

    /**
     *账号状态，取值见TrdAccStatus
     *
     * Generated from protobuf field <code>int32 accStatus = 9;</code>
     * @return int
     */
    public function getAccStatus()
    {
        return $this->accStatus;
    }

    /**
     *账号状态，取值见TrdAccStatus
     *
     * Generated from protobuf field <code>int32 accStatus = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setAccStatus(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->accStatus = $var;

        return $this;
    }

    /**
     *账号分类，是不是主账号，取值见TrdAccRole
     *
     * Generated from protobuf field <code>int32 accRole = 10;</code>
     * @return int
     */
    public function getAccRole()
    {
        return $this->accRole;
    }

    /**
     *账号分类，是不是主账号，取值见TrdAccRole
     *
     * Generated from protobuf field <code>int32 accRole = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setAccRole(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->accRole = $var;

        return $this;
    }

    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 11;</code>
     * @return int
     */
    public function getJpAccType()
    {
        return $this->jpAccType;
    }

    /**
     *JP子账户类型，取值见 TrdSubAccType
     *
     * Generated from protobuf field <code>int32 jpAccType = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setJpAccType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->jpAccType = $var;

        return $this;
    }

}

