<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *过滤条件，条件组合是"与"不是"或"，用于获取订单、成交、持仓等时二次过滤
 *
 * Generated from protobuf message <code>Trd_Common.TrdFilterConditions</code>
 */
class TrdFilterConditions extends \Google\Protobuf\Internal\Message
{
    /**
     *代码过滤，只返回包含这些代码的数据，没传不过滤
     *
     * Generated from protobuf field <code>repeated string codeList = 1;</code>
     */
    private $codeList;
    /**
     *ID主键过滤，只返回包含这些ID的数据，没传不过滤，订单是orderID、成交是fillID、持仓是positionID
     *
     * Generated from protobuf field <code>repeated uint64 idList = 2;</code>
     */
    private $idList;
    /**
     *开始时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
     *
     * Generated from protobuf field <code>string beginTime = 3;</code>
     */
    protected $beginTime = '';
    /**
     *结束时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
     *
     * Generated from protobuf field <code>string endTime = 4;</code>
     */
    protected $endTime = '';
    /**
     * 服务器订单ID，可以用来替代orderID，二选一
     *
     * Generated from protobuf field <code>repeated string orderIDExList = 5;</code>
     */
    private $orderIDExList;
    /**
     *指定交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 filterMarket = 6;</code>
     */
    protected $filterMarket = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $codeList
     *          代码过滤，只返回包含这些代码的数据，没传不过滤
     *     @type int[]|string[] $idList
     *          ID主键过滤，只返回包含这些ID的数据，没传不过滤，订单是orderID、成交是fillID、持仓是positionID
     *     @type string $beginTime
     *          开始时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
     *     @type string $endTime
     *          结束时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
     *     @type string[] $orderIDExList
     *           服务器订单ID，可以用来替代orderID，二选一
     *     @type int $filterMarket
     *          指定交易市场, 参见TrdMarket的枚举定义
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *代码过滤，只返回包含这些代码的数据，没传不过滤
     *
     * Generated from protobuf field <code>repeated string codeList = 1;</code>
     * @return RepeatedField<string>
     */
    public function getCodeList()
    {
        return $this->codeList;
    }

    /**
     *代码过滤，只返回包含这些代码的数据，没传不过滤
     *
     * Generated from protobuf field <code>repeated string codeList = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setCodeList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->codeList = $arr;

        return $this;
    }

    /**
     *ID主键过滤，只返回包含这些ID的数据，没传不过滤，订单是orderID、成交是fillID、持仓是positionID
     *
     * Generated from protobuf field <code>repeated uint64 idList = 2;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getIdList()
    {
        return $this->idList;
    }

    /**
     *ID主键过滤，只返回包含这些ID的数据，没传不过滤，订单是orderID、成交是fillID、持仓是positionID
     *
     * Generated from protobuf field <code>repeated uint64 idList = 2;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setIdList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->idList = $arr;

        return $this;
    }

    /**
     *开始时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
     *
     * Generated from protobuf field <code>string beginTime = 3;</code>
     * @return string
     */
    public function getBeginTime()
    {
        return $this->beginTime;
    }

    /**
     *开始时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
     *
     * Generated from protobuf field <code>string beginTime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBeginTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->beginTime = $var;

        return $this;
    }

    /**
     *结束时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
     *
     * Generated from protobuf field <code>string endTime = 4;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     *结束时间，严格按YYYY-MM-DD HH:MM:SS或YYYY-MM-DD HH:MM:SS.MS格式传，对持仓无效，拉历史数据必须填
     *
     * Generated from protobuf field <code>string endTime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endTime = $var;

        return $this;
    }

    /**
     * 服务器订单ID，可以用来替代orderID，二选一
     *
     * Generated from protobuf field <code>repeated string orderIDExList = 5;</code>
     * @return RepeatedField<string>
     */
    public function getOrderIDExList()
    {
        return $this->orderIDExList;
    }

    /**
     * 服务器订单ID，可以用来替代orderID，二选一
     *
     * Generated from protobuf field <code>repeated string orderIDExList = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setOrderIDExList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->orderIDExList = $arr;

        return $this;
    }

    /**
     *指定交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 filterMarket = 6;</code>
     * @return int
     */
    public function getFilterMarket()
    {
        return $this->filterMarket;
    }

    /**
     *指定交易市场, 参见TrdMarket的枚举定义
     *
     * Generated from protobuf field <code>int32 filterMarket = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setFilterMarket(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->filterMarket = $var;

        return $this;
    }

}

