<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use UnexpectedValueException;

/**
 *交易市场，是大的市场，不是具体品种
 *
 * Protobuf type <code>Trd_Common.TrdMarket</code>
 */
class TrdMarket
{
    /**
     *未知市场
     *
     * Generated from protobuf enum <code>TrdMarket_Unknown = 0;</code>
     */
    const TrdMarket_Unknown = 0;
    /**
     *香港市场
     *
     * Generated from protobuf enum <code>TrdMarket_HK = 1;</code>
     */
    const TrdMarket_HK = 1;
    /**
     *美国市场
     *
     * Generated from protobuf enum <code>TrdMarket_US = 2;</code>
     */
    const TrdMarket_US = 2;
    /**
     *大陆市场
     *
     * Generated from protobuf enum <code>TrdMarket_CN = 3;</code>
     */
    const TrdMarket_CN = 3;
    /**
     *香港A股通市场
     *
     * Generated from protobuf enum <code>TrdMarket_HKCC = 4;</code>
     */
    const TrdMarket_HKCC = 4;
    /**
     *期货市场
     *
     * Generated from protobuf enum <code>TrdMarket_Futures = 5;</code>
     */
    const TrdMarket_Futures = 5;
    /**
     *期货市场
     *
     * Generated from protobuf enum <code>TrdMarket_SG = 6;</code>
     */
    const TrdMarket_SG = 6;
    /**
     *澳洲市场
     *
     * Generated from protobuf enum <code>TrdMarket_AU = 8;</code>
     */
    const TrdMarket_AU = 8;
    /**
     * 模拟交易期货市场
     *
     * Generated from protobuf enum <code>TrdMarket_Futures_Simulate_HK = 10;</code>
     */
    const TrdMarket_Futures_Simulate_HK = 10;
    /**
     * Generated from protobuf enum <code>TrdMarket_Futures_Simulate_US = 11;</code>
     */
    const TrdMarket_Futures_Simulate_US = 11;
    /**
     * Generated from protobuf enum <code>TrdMarket_Futures_Simulate_SG = 12;</code>
     */
    const TrdMarket_Futures_Simulate_SG = 12;
    /**
     * Generated from protobuf enum <code>TrdMarket_Futures_Simulate_JP = 13;</code>
     */
    const TrdMarket_Futures_Simulate_JP = 13;
    /**
     * Generated from protobuf enum <code>TrdMarket_JP = 15;</code>
     */
    const TrdMarket_JP = 15;
    /**
     * Generated from protobuf enum <code>TrdMarket_MY = 111;</code>
     */
    const TrdMarket_MY = 111;
    /**
     * Generated from protobuf enum <code>TrdMarket_CA = 112;</code>
     */
    const TrdMarket_CA = 112;
    /**
     *香港基金市场
     *
     * Generated from protobuf enum <code>TrdMarket_HK_Fund = 113;</code>
     */
    const TrdMarket_HK_Fund = 113;
    /**
     *美国基金市场
     *
     * Generated from protobuf enum <code>TrdMarket_US_Fund = 123;</code>
     */
    const TrdMarket_US_Fund = 123;
    /**
     *新加坡基金市场
     *
     * Generated from protobuf enum <code>TrdMarket_SG_Fund = 124;</code>
     */
    const TrdMarket_SG_Fund = 124;
    /**
     *马来西亚基金市场
     *
     * Generated from protobuf enum <code>TrdMarket_MY_Fund = 125;</code>
     */
    const TrdMarket_MY_Fund = 125;
    /**
     *日本基金市场
     *
     * Generated from protobuf enum <code>TrdMarket_JP_Fund = 126;</code>
     */
    const TrdMarket_JP_Fund = 126;

    private static $valueToName = [
        self::TrdMarket_Unknown => 'TrdMarket_Unknown',
        self::TrdMarket_HK => 'TrdMarket_HK',
        self::TrdMarket_US => 'TrdMarket_US',
        self::TrdMarket_CN => 'TrdMarket_CN',
        self::TrdMarket_HKCC => 'TrdMarket_HKCC',
        self::TrdMarket_Futures => 'TrdMarket_Futures',
        self::TrdMarket_SG => 'TrdMarket_SG',
        self::TrdMarket_AU => 'TrdMarket_AU',
        self::TrdMarket_Futures_Simulate_HK => 'TrdMarket_Futures_Simulate_HK',
        self::TrdMarket_Futures_Simulate_US => 'TrdMarket_Futures_Simulate_US',
        self::TrdMarket_Futures_Simulate_SG => 'TrdMarket_Futures_Simulate_SG',
        self::TrdMarket_Futures_Simulate_JP => 'TrdMarket_Futures_Simulate_JP',
        self::TrdMarket_JP => 'TrdMarket_JP',
        self::TrdMarket_MY => 'TrdMarket_MY',
        self::TrdMarket_CA => 'TrdMarket_CA',
        self::TrdMarket_HK_Fund => 'TrdMarket_HK_Fund',
        self::TrdMarket_US_Fund => 'TrdMarket_US_Fund',
        self::TrdMarket_SG_Fund => 'TrdMarket_SG_Fund',
        self::TrdMarket_MY_Fund => 'TrdMarket_MY_Fund',
        self::TrdMarket_JP_Fund => 'TrdMarket_JP_Fund',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

