<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_Common.proto

namespace Futu\Trd_Common;

use UnexpectedValueException;

/**
 *交易方向
 *
 * Protobuf type <code>Trd_Common.TrdSide</code>
 */
class TrdSide
{
    /**
     *客户端下单只传Buy或Sell即可，SellShort是美股订单时服务器返回有此方向，BuyBack目前不存在，但也不排除服务器会传
     *
     * Generated from protobuf enum <code>TrdSide_Unknown = 0;</code>
     */
    const TrdSide_Unknown = 0;
    /**
     *买入
     *
     * Generated from protobuf enum <code>TrdSide_Buy = 1;</code>
     */
    const TrdSide_Buy = 1;
    /**
     *卖出
     *
     * Generated from protobuf enum <code>TrdSide_Sell = 2;</code>
     */
    const TrdSide_Sell = 2;
    /**
     *卖空
     *
     * Generated from protobuf enum <code>TrdSide_SellShort = 3;</code>
     */
    const TrdSide_SellShort = 3;
    /**
     *买回
     *
     * Generated from protobuf enum <code>TrdSide_BuyBack = 4;</code>
     */
    const TrdSide_BuyBack = 4;

    private static $valueToName = [
        self::TrdSide_Unknown => 'TrdSide_Unknown',
        self::TrdSide_Buy => 'TrdSide_Buy',
        self::TrdSide_Sell => 'TrdSide_Sell',
        self::TrdSide_SellShort => 'TrdSide_SellShort',
        self::TrdSide_BuyBack => 'TrdSide_BuyBack',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

