<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: KeepAlive.proto

namespace Futu\KeepAlive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>KeepAlive.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *服务器回包时的格林威治时间戳，单位秒
     *
     * Generated from protobuf field <code>int64 time = 1;</code>
     */
    protected $time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $time
     *          服务器回包时的格林威治时间戳，单位秒
     * }
     */
    public function __construct($data = NULL) {
        \Futu\KeepAlive\pb\KeepAlive::initOnce();
        parent::__construct($data);
    }

    /**
     *服务器回包时的格林威治时间戳，单位秒
     *
     * Generated from protobuf field <code>int64 time = 1;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *服务器回包时的格林威治时间戳，单位秒
     *
     * Generated from protobuf field <code>int64 time = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

