<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetAccList.proto

namespace Futu\Trd_GetAccList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_GetAccList.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *历史原因，目前已废弃，填0即可
     *
     * Generated from protobuf field <code>uint64 userID = 1;</code>
     */
    protected $userID = 0;
    /**
     *交易品类，参考 Trd_Common.TrdCategory
     *
     * Generated from protobuf field <code>int32 trdCategory = 2;</code>
     */
    protected $trdCategory = 0;
    /**
     *是否返回全能账户，仅SG用户需要
     *
     * Generated from protobuf field <code>bool needGeneralSecAccount = 3;</code>
     */
    protected $needGeneralSecAccount = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $userID
     *          历史原因，目前已废弃，填0即可
     *     @type int $trdCategory
     *          交易品类，参考 Trd_Common.TrdCategory
     *     @type bool $needGeneralSecAccount
     *          是否返回全能账户，仅SG用户需要
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_GetAccList\pb\TrdGetAccList::initOnce();
        parent::__construct($data);
    }

    /**
     *历史原因，目前已废弃，填0即可
     *
     * Generated from protobuf field <code>uint64 userID = 1;</code>
     * @return int|string
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     *历史原因，目前已废弃，填0即可
     *
     * Generated from protobuf field <code>uint64 userID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->userID = $var;

        return $this;
    }

    /**
     *交易品类，参考 Trd_Common.TrdCategory
     *
     * Generated from protobuf field <code>int32 trdCategory = 2;</code>
     * @return int
     */
    public function getTrdCategory()
    {
        return $this->trdCategory;
    }

    /**
     *交易品类，参考 Trd_Common.TrdCategory
     *
     * Generated from protobuf field <code>int32 trdCategory = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTrdCategory(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->trdCategory = $var;

        return $this;
    }

    /**
     *是否返回全能账户，仅SG用户需要
     *
     * Generated from protobuf field <code>bool needGeneralSecAccount = 3;</code>
     * @return bool
     */
    public function getNeedGeneralSecAccount()
    {
        return $this->needGeneralSecAccount;
    }

    /**
     *是否返回全能账户，仅SG用户需要
     *
     * Generated from protobuf field <code>bool needGeneralSecAccount = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedGeneralSecAccount(bool $var)
    {
        $this->needGeneralSecAccount = $var;

        return $this;
    }

}

