<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetOrderFillList.proto

namespace Futu\Trd_GetOrderFillList\pb;

class TrdGetOrderFillList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEB\x03\x0A\x1ATrd_GetOrderFillList.proto\x12\x14Trd_GetOrderFillList\"}\x0A\x03C2S\x12%\x0A\x06header\x18\x01 \x01(\x0B2\x15.Trd_Common.TrdHeader\x129\x0A\x10filterConditions\x18\x02 \x01(\x0B2\x1F.Trd_Common.TrdFilterConditions\x12\x14\x0A\x0CrefreshCache\x18\x03 \x01(\x08\"Z\x0A\x03S2C\x12%\x0A\x06header\x18\x01 \x01(\x0B2\x15.Trd_Common.TrdHeader\x12,\x0A\x0DorderFillList\x18\x02 \x03(\x0B2\x15.Trd_Common.OrderFill\"1\x0A\x07Request\x12&\x0A\x03c2s\x18\x01 \x01(\x0B2\x19.Trd_GetOrderFillList.C2S\"d\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12&\x0A\x03s2c\x18\x04 \x01(\x0B2\x19.Trd_GetOrderFillList.S2CB;\xCA\x02\x19Futu\\Trd_GetOrderFillList\xE2\x02\x1CFutu\\Trd_GetOrderFillList\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

