<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetFutureInfo.proto

namespace Futu\Qot_GetFutureInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetFutureInfo.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *股票列表
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Security securityList = 1;</code>
     */
    private $securityList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security[] $securityList
     *          股票列表
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetFutureInfo\pb\QotGetFutureInfo::initOnce();
        parent::__construct($data);
    }

    /**
     *股票列表
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Security securityList = 1;</code>
     * @return RepeatedField<\Futu\Qot_Common\Security>
     */
    public function getSecurityList()
    {
        return $this->securityList;
    }

    /**
     *股票列表
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Security securityList = 1;</code>
     * @param \Futu\Qot_Common\Security[] $var
     * @return $this
     */
    public function setSecurityList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\Security::class);
        $this->securityList = $arr;

        return $this;
    }

}

