<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetFutureInfo.proto

namespace Futu\Qot_GetFutureInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetFutureInfo.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Qot_GetFutureInfo.C2S c2s = 1;</code>
     */
    protected $c2s = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_GetFutureInfo\C2S $c2s
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetFutureInfo\pb\QotGetFutureInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Qot_GetFutureInfo.C2S c2s = 1;</code>
     * @return \Futu\Qot_GetFutureInfo\C2S|null
     */
    public function getC2S()
    {
        return $this->c2s;
    }

    public function hasC2S()
    {
        return isset($this->c2s);
    }

    public function clearC2S()
    {
        unset($this->c2s);
    }

    /**
     * Generated from protobuf field <code>.Qot_GetFutureInfo.C2S c2s = 1;</code>
     * @param \Futu\Qot_GetFutureInfo\C2S $var
     * @return $this
     */
    public function setC2S(\Futu\Qot_GetFutureInfo\C2S|null $var)
    {
        $this->c2s = $var;

        return $this;
    }

}

