<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetFutureInfo.proto

namespace Futu\Qot_GetFutureInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *交易时间
 *
 * Generated from protobuf message <code>Qot_GetFutureInfo.TradeTime</code>
 */
class TradeTime extends \Google\Protobuf\Internal\Message
{
    /**
     * 开始时间,以分钟为单位
     *
     * Generated from protobuf field <code>double begin = 1;</code>
     */
    protected $begin = 0.0;
    /**
     * 结束时间,以分钟为单位
     *
     * Generated from protobuf field <code>double end = 2;</code>
     */
    protected $end = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $begin
     *           开始时间,以分钟为单位
     *     @type float $end
     *           结束时间,以分钟为单位
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetFutureInfo\pb\QotGetFutureInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * 开始时间,以分钟为单位
     *
     * Generated from protobuf field <code>double begin = 1;</code>
     * @return float
     */
    public function getBegin()
    {
        return $this->begin;
    }

    /**
     * 开始时间,以分钟为单位
     *
     * Generated from protobuf field <code>double begin = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setBegin(float $var)
    {
        $this->begin = $var;

        return $this;
    }

    /**
     * 结束时间,以分钟为单位
     *
     * Generated from protobuf field <code>double end = 2;</code>
     * @return float
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * 结束时间,以分钟为单位
     *
     * Generated from protobuf field <code>double end = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setEnd(float $var)
    {
        $this->end = $var;

        return $this;
    }

}

