<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestRehab.proto

namespace Futu\Qot_RequestRehab\pb;

class QotRequestRehab
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD4\x02\x0A\x16Qot_RequestRehab.proto\x12\x10Qot_RequestRehab\"-\x0A\x03C2S\x12&\x0A\x08security\x18\x01 \x01(\x0B2\x14.Qot_Common.Security\"+\x0A\x03S2C\x12\$\x0A\x09rehabList\x18\x01 \x03(\x0B2\x11.Qot_Common.Rehab\"-\x0A\x07Request\x12\"\x0A\x03c2s\x18\x01 \x01(\x0B2\x15.Qot_RequestRehab.C2S\"`\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12\"\x0A\x03s2c\x18\x04 \x01(\x0B2\x15.Qot_RequestRehab.S2CB3\xCA\x02\x15Futu\\Qot_RequestRehab\xE2\x02\x18Futu\\Qot_RequestRehab\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

