<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetPositionList.proto

namespace Futu\Trd_GetPositionList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_GetPositionList.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     */
    protected $header = null;
    /**
     *过滤条件
     *
     * Generated from protobuf field <code>.Trd_Common.TrdFilterConditions filterConditions = 2;</code>
     */
    protected $filterConditions = null;
    /**
     *过滤盈亏百分比下限，高于此比例的会返回，比如传10.0，返回盈亏比例大于10%的持仓
     *
     * Generated from protobuf field <code>double filterPLRatioMin = 3;</code>
     */
    protected $filterPLRatioMin = 0.0;
    /**
     *过滤盈亏百分比上限，低于此比例的会返回，比如传20.0，返回盈亏比例小于20%的持仓
     *
     * Generated from protobuf field <code>double filterPLRatioMax = 4;</code>
     */
    protected $filterPLRatioMax = 0.0;
    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 5;</code>
     */
    protected $refreshCache = false;
    /**
     *正常情况下，服务器有更新就会立即推送到OpenD，OpenD缓存着数据，API请求过来，返回同步的缓存数据，一般不需要指定刷新缓存，保证快速返回且减少对服务器的压力
     *如果遇到丢包等情况，可能出现缓存数据与服务器不一致，用户如果发现数据更新有异样，可指定刷新缓存，解决数据同步的问题。
     *
     * Generated from protobuf field <code>int32 assetCategory = 6;</code>
     */
    protected $assetCategory = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Trd_Common\TrdHeader $header
     *          交易公共参数头
     *     @type \Futu\Trd_Common\TrdFilterConditions $filterConditions
     *          过滤条件
     *     @type float $filterPLRatioMin
     *          过滤盈亏百分比下限，高于此比例的会返回，比如传10.0，返回盈亏比例大于10%的持仓
     *     @type float $filterPLRatioMax
     *          过滤盈亏百分比上限，低于此比例的会返回，比如传20.0，返回盈亏比例小于20%的持仓
     *     @type bool $refreshCache
     *          立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *     @type int $assetCategory
     *          正常情况下，服务器有更新就会立即推送到OpenD，OpenD缓存着数据，API请求过来，返回同步的缓存数据，一般不需要指定刷新缓存，保证快速返回且减少对服务器的压力
     *          如果遇到丢包等情况，可能出现缓存数据与服务器不一致，用户如果发现数据更新有异样，可指定刷新缓存，解决数据同步的问题。
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_GetPositionList\pb\TrdGetPositionList::initOnce();
        parent::__construct($data);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @return \Futu\Trd_Common\TrdHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @param \Futu\Trd_Common\TrdHeader $var
     * @return $this
     */
    public function setHeader(\Futu\Trd_Common\TrdHeader|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     *过滤条件
     *
     * Generated from protobuf field <code>.Trd_Common.TrdFilterConditions filterConditions = 2;</code>
     * @return \Futu\Trd_Common\TrdFilterConditions|null
     */
    public function getFilterConditions()
    {
        return $this->filterConditions;
    }

    public function hasFilterConditions()
    {
        return isset($this->filterConditions);
    }

    public function clearFilterConditions()
    {
        unset($this->filterConditions);
    }

    /**
     *过滤条件
     *
     * Generated from protobuf field <code>.Trd_Common.TrdFilterConditions filterConditions = 2;</code>
     * @param \Futu\Trd_Common\TrdFilterConditions $var
     * @return $this
     */
    public function setFilterConditions(\Futu\Trd_Common\TrdFilterConditions|null $var)
    {
        $this->filterConditions = $var;

        return $this;
    }

    /**
     *过滤盈亏百分比下限，高于此比例的会返回，比如传10.0，返回盈亏比例大于10%的持仓
     *
     * Generated from protobuf field <code>double filterPLRatioMin = 3;</code>
     * @return float
     */
    public function getFilterPLRatioMin()
    {
        return $this->filterPLRatioMin;
    }

    /**
     *过滤盈亏百分比下限，高于此比例的会返回，比如传10.0，返回盈亏比例大于10%的持仓
     *
     * Generated from protobuf field <code>double filterPLRatioMin = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setFilterPLRatioMin(float $var)
    {
        $this->filterPLRatioMin = $var;

        return $this;
    }

    /**
     *过滤盈亏百分比上限，低于此比例的会返回，比如传20.0，返回盈亏比例小于20%的持仓
     *
     * Generated from protobuf field <code>double filterPLRatioMax = 4;</code>
     * @return float
     */
    public function getFilterPLRatioMax()
    {
        return $this->filterPLRatioMax;
    }

    /**
     *过滤盈亏百分比上限，低于此比例的会返回，比如传20.0，返回盈亏比例小于20%的持仓
     *
     * Generated from protobuf field <code>double filterPLRatioMax = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setFilterPLRatioMax(float $var)
    {
        $this->filterPLRatioMax = $var;

        return $this;
    }

    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 5;</code>
     * @return bool
     */
    public function getRefreshCache()
    {
        return $this->refreshCache;
    }

    /**
     *立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
     *
     * Generated from protobuf field <code>bool refreshCache = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setRefreshCache(bool $var)
    {
        $this->refreshCache = $var;

        return $this;
    }

    /**
     *正常情况下，服务器有更新就会立即推送到OpenD，OpenD缓存着数据，API请求过来，返回同步的缓存数据，一般不需要指定刷新缓存，保证快速返回且减少对服务器的压力
     *如果遇到丢包等情况，可能出现缓存数据与服务器不一致，用户如果发现数据更新有异样，可指定刷新缓存，解决数据同步的问题。
     *
     * Generated from protobuf field <code>int32 assetCategory = 6;</code>
     * @return int
     */
    public function getAssetCategory()
    {
        return $this->assetCategory;
    }

    /**
     *正常情况下，服务器有更新就会立即推送到OpenD，OpenD缓存着数据，API请求过来，返回同步的缓存数据，一般不需要指定刷新缓存，保证快速返回且减少对服务器的压力
     *如果遇到丢包等情况，可能出现缓存数据与服务器不一致，用户如果发现数据更新有异样，可指定刷新缓存，解决数据同步的问题。
     *
     * Generated from protobuf field <code>int32 assetCategory = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setAssetCategory(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->assetCategory = $var;

        return $this;
    }

}

