<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_SubAccPush.proto

namespace Futu\Trd_SubAccPush\pb;

class TrdSubAccPush
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x8D\x02\x0A\x14Trd_SubAccPush.proto\x12\x0ETrd_SubAccPush\"\x18\x0A\x03C2S\x12\x11\x0A\x09accIDList\x18\x01 \x03(\x04\"\x05\x0A\x03S2C\"+\x0A\x07Request\x12 \x0A\x03c2s\x18\x01 \x01(\x0B2\x13.Trd_SubAccPush.C2S\"^\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12 \x0A\x03s2c\x18\x04 \x01(\x0B2\x13.Trd_SubAccPush.S2CB/\xCA\x02\x13Futu\\Trd_SubAccPush\xE2\x02\x16Futu\\Trd_SubAccPush\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

