<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestHistoryKLQuota.proto

namespace Futu\Qot_RequestHistoryKLQuota\pb;

class QotRequestHistoryKLQuota
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA6\x04\x0A\x1FQot_RequestHistoryKLQuota.proto\x12\x19Qot_RequestHistoryKLQuota\"q\x0A\x0ADetailItem\x12&\x0A\x08security\x18\x01 \x01(\x0B2\x14.Qot_Common.Security\x12\x0C\x0A\x04name\x18\x04 \x01(\x09\x12\x13\x0A\x0BrequestTime\x18\x02 \x01(\x09\x12\x18\x0A\x10requestTimeStamp\x18\x03 \x01(\x03\"\x19\x0A\x03C2S\x12\x12\x0A\x0AbGetDetail\x18\x02 \x01(\x08\"h\x0A\x03S2C\x12\x11\x0A\x09usedQuota\x18\x01 \x01(\x05\x12\x13\x0A\x0BremainQuota\x18\x02 \x01(\x05\x129\x0A\x0AdetailList\x18\x03 \x03(\x0B2%.Qot_RequestHistoryKLQuota.DetailItem\"6\x0A\x07Request\x12+\x0A\x03c2s\x18\x01 \x01(\x0B2\x1E.Qot_RequestHistoryKLQuota.C2S\"i\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12+\x0A\x03s2c\x18\x04 \x01(\x0B2\x1E.Qot_RequestHistoryKLQuota.S2CBE\xCA\x02\x1EFutu\\Qot_RequestHistoryKLQuota\xE2\x02!Futu\\Qot_RequestHistoryKLQuota\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

