<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetBasicQot.proto

namespace Futu\Qot_GetBasicQot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetBasicQot.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *股票基本行情
     *
     * Generated from protobuf field <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     */
    private $basicQotList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\BasicQot[] $basicQotList
     *          股票基本行情
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetBasicQot\pb\QotGetBasicQot::initOnce();
        parent::__construct($data);
    }

    /**
     *股票基本行情
     *
     * Generated from protobuf field <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     * @return RepeatedField<\Futu\Qot_Common\BasicQot>
     */
    public function getBasicQotList()
    {
        return $this->basicQotList;
    }

    /**
     *股票基本行情
     *
     * Generated from protobuf field <code>repeated .Qot_Common.BasicQot basicQotList = 1;</code>
     * @param \Futu\Qot_Common\BasicQot[] $var
     * @return $this
     */
    public function setBasicQotList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\BasicQot::class);
        $this->basicQotList = $arr;

        return $this;
    }

}

