<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetUserSecurity.proto

namespace Futu\Qot_GetUserSecurity\pb;

class QotGetUserSecurity
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE3\x02\x0A\x19Qot_GetUserSecurity.proto\x12\x13Qot_GetUserSecurity\"\x18\x0A\x03C2S\x12\x11\x0A\x09groupName\x18\x01 \x01(\x09\"=\x0A\x03S2C\x126\x0A\x0EstaticInfoList\x18\x01 \x03(\x0B2\x1E.Qot_Common.SecurityStaticInfo\"0\x0A\x07Request\x12%\x0A\x03c2s\x18\x01 \x01(\x0B2\x18.Qot_GetUserSecurity.C2S\"c\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12%\x0A\x03s2c\x18\x04 \x01(\x0B2\x18.Qot_GetUserSecurity.S2CB9\xCA\x02\x18Futu\\Qot_GetUserSecurity\xE2\x02\x1BFutu\\Qot_GetUserSecurity\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

