<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetReference.proto

namespace Futu\Qot_GetReference\pb;

class QotGetReference
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDD\x03\x0A\x16Qot_GetReference.proto\x12\x10Qot_GetReference\"D\x0A\x03C2S\x12&\x0A\x08security\x18\x01 \x01(\x0B2\x14.Qot_Common.Security\x12\x15\x0A\x0DreferenceType\x18\x02 \x01(\x05\"=\x0A\x03S2C\x126\x0A\x0EstaticInfoList\x18\x02 \x03(\x0B2\x1E.Qot_Common.SecurityStaticInfo\"-\x0A\x07Request\x12\"\x0A\x03c2s\x18\x01 \x01(\x0B2\x15.Qot_GetReference.C2S\"`\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12\"\x0A\x03s2c\x18\x04 \x01(\x0B2\x15.Qot_GetReference.S2C*^\x0A\x0DReferenceType\x12\x18\x0A\x14ReferenceType_Unknow\x10\x00\x12\x19\x0A\x15ReferenceType_Warrant\x10\x01\x12\x18\x0A\x14ReferenceType_Future\x10\x02B3\xCA\x02\x15Futu\\Qot_GetReference\xE2\x02\x18Futu\\Qot_GetReference\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

