<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestRehab.proto

namespace Futu\Qot_RequestRehab;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_RequestRehab.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *复权信息
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Rehab rehabList = 1;</code>
     */
    private $rehabList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Rehab[] $rehabList
     *          复权信息
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_RequestRehab\pb\QotRequestRehab::initOnce();
        parent::__construct($data);
    }

    /**
     *复权信息
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Rehab rehabList = 1;</code>
     * @return RepeatedField<\Futu\Qot_Common\Rehab>
     */
    public function getRehabList()
    {
        return $this->rehabList;
    }

    /**
     *复权信息
     *
     * Generated from protobuf field <code>repeated .Qot_Common.Rehab rehabList = 1;</code>
     * @param \Futu\Qot_Common\Rehab[] $var
     * @return $this
     */
    public function setRehabList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\Rehab::class);
        $this->rehabList = $arr;

        return $this;
    }

}

