<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestTradeDate.proto

namespace Futu\Qot_RequestTradeDate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_RequestTradeDate.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *交易日,注意该交易日是通过自然日去除周末以及节假日得到，不包括临时休市数据。
     *
     * Generated from protobuf field <code>repeated .Qot_RequestTradeDate.TradeDate tradeDateList = 1;</code>
     */
    private $tradeDateList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_RequestTradeDate\TradeDate[] $tradeDateList
     *          交易日,注意该交易日是通过自然日去除周末以及节假日得到，不包括临时休市数据。
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_RequestTradeDate\pb\QotRequestTradeDate::initOnce();
        parent::__construct($data);
    }

    /**
     *交易日,注意该交易日是通过自然日去除周末以及节假日得到，不包括临时休市数据。
     *
     * Generated from protobuf field <code>repeated .Qot_RequestTradeDate.TradeDate tradeDateList = 1;</code>
     * @return RepeatedField<\Futu\Qot_RequestTradeDate\TradeDate>
     */
    public function getTradeDateList()
    {
        return $this->tradeDateList;
    }

    /**
     *交易日,注意该交易日是通过自然日去除周末以及节假日得到，不包括临时休市数据。
     *
     * Generated from protobuf field <code>repeated .Qot_RequestTradeDate.TradeDate tradeDateList = 1;</code>
     * @param \Futu\Qot_RequestTradeDate\TradeDate[] $var
     * @return $this
     */
    public function setTradeDateList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_RequestTradeDate\TradeDate::class);
        $this->tradeDateList = $arr;

        return $this;
    }

}

