<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetAccList.proto

namespace Futu\Trd_GetAccList\pb;

class TrdGetAccList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE3\x02\x0A\x14Trd_GetAccList.proto\x12\x0ETrd_GetAccList\"I\x0A\x03C2S\x12\x0E\x0A\x06userID\x18\x01 \x01(\x04\x12\x13\x0A\x0BtrdCategory\x18\x02 \x01(\x05\x12\x1D\x0A\x15needGeneralSecAccount\x18\x03 \x01(\x08\"*\x0A\x03S2C\x12#\x0A\x07accList\x18\x01 \x03(\x0B2\x12.Trd_Common.TrdAcc\"+\x0A\x07Request\x12 \x0A\x03c2s\x18\x01 \x01(\x0B2\x13.Trd_GetAccList.C2S\"^\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12 \x0A\x03s2c\x18\x04 \x01(\x0B2\x13.Trd_GetAccList.S2CB/\xCA\x02\x13Futu\\Trd_GetAccList\xE2\x02\x16Futu\\Trd_GetAccList\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

