<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestHistoryKLQuota.proto

namespace Futu\Qot_RequestHistoryKLQuota;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_RequestHistoryKLQuota.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *是否返回详细拉取过的历史纪录
     *
     * Generated from protobuf field <code>bool bGetDetail = 2;</code>
     */
    protected $bGetDetail = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $bGetDetail
     *          是否返回详细拉取过的历史纪录
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_RequestHistoryKLQuota\pb\QotRequestHistoryKLQuota::initOnce();
        parent::__construct($data);
    }

    /**
     *是否返回详细拉取过的历史纪录
     *
     * Generated from protobuf field <code>bool bGetDetail = 2;</code>
     * @return bool
     */
    public function getBGetDetail()
    {
        return $this->bGetDetail;
    }

    /**
     *是否返回详细拉取过的历史纪录
     *
     * Generated from protobuf field <code>bool bGetDetail = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBGetDetail(bool $var)
    {
        $this->bGetDetail = $var;

        return $this;
    }

}

