<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestHistoryKLQuota.proto

namespace Futu\Qot_RequestHistoryKLQuota;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_RequestHistoryKLQuota.DetailItem</code>
 */
class DetailItem extends \Google\Protobuf\Internal\Message
{
    /**
     *拉取的股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     */
    protected $security = null;
    /**
     *股票名称
     *
     * Generated from protobuf field <code>string name = 4;</code>
     */
    protected $name = '';
    /**
     *拉取的时间字符串
     *
     * Generated from protobuf field <code>string requestTime = 2;</code>
     */
    protected $requestTime = '';
    /**
     *拉取的时间戳
     *
     * Generated from protobuf field <code>int64 requestTimeStamp = 3;</code>
     */
    protected $requestTimeStamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\Security $security
     *          拉取的股票
     *     @type string $name
     *          股票名称
     *     @type string $requestTime
     *          拉取的时间字符串
     *     @type int|string $requestTimeStamp
     *          拉取的时间戳
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_RequestHistoryKLQuota\pb\QotRequestHistoryKLQuota::initOnce();
        parent::__construct($data);
    }

    /**
     *拉取的股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @return \Futu\Qot_Common\Security|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     *拉取的股票
     *
     * Generated from protobuf field <code>.Qot_Common.Security security = 1;</code>
     * @param \Futu\Qot_Common\Security $var
     * @return $this
     */
    public function setSecurity(\Futu\Qot_Common\Security|null $var)
    {
        $this->security = $var;

        return $this;
    }

    /**
     *股票名称
     *
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *股票名称
     *
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     *拉取的时间字符串
     *
     * Generated from protobuf field <code>string requestTime = 2;</code>
     * @return string
     */
    public function getRequestTime()
    {
        return $this->requestTime;
    }

    /**
     *拉取的时间字符串
     *
     * Generated from protobuf field <code>string requestTime = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->requestTime = $var;

        return $this;
    }

    /**
     *拉取的时间戳
     *
     * Generated from protobuf field <code>int64 requestTimeStamp = 3;</code>
     * @return int|string
     */
    public function getRequestTimeStamp()
    {
        return $this->requestTimeStamp;
    }

    /**
     *拉取的时间戳
     *
     * Generated from protobuf field <code>int64 requestTimeStamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestTimeStamp(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->requestTimeStamp = $var;

        return $this;
    }

}

