<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetGlobalState.proto

namespace Futu\GetGlobalState;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>GetGlobalState.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *历史原因，目前已废弃，填0即可
     *
     * Generated from protobuf field <code>uint64 userID = 1;</code>
     */
    protected $userID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $userID
     *          历史原因，目前已废弃，填0即可
     * }
     */
    public function __construct($data = NULL) {
        \Futu\GetGlobalState\pb\GetGlobalState::initOnce();
        parent::__construct($data);
    }

    /**
     *历史原因，目前已废弃，填0即可
     *
     * Generated from protobuf field <code>uint64 userID = 1;</code>
     * @return int|string
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     *历史原因，目前已废弃，填0即可
     *
     * Generated from protobuf field <code>uint64 userID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->userID = $var;

        return $this;
    }

}

