<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetSubInfo.proto

namespace Futu\Qot_GetSubInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetSubInfo.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *订阅订阅信息
     *
     * Generated from protobuf field <code>repeated .Qot_Common.ConnSubInfo connSubInfoList = 1;</code>
     */
    private $connSubInfoList;
    /**
     *FutuOpenD已使用的订阅额度
     *
     * Generated from protobuf field <code>int32 totalUsedQuota = 2;</code>
     */
    protected $totalUsedQuota = 0;
    /**
     *FutuOpenD剩余订阅额度
     *
     * Generated from protobuf field <code>int32 remainQuota = 3;</code>
     */
    protected $remainQuota = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\ConnSubInfo[] $connSubInfoList
     *          订阅订阅信息
     *     @type int $totalUsedQuota
     *          FutuOpenD已使用的订阅额度
     *     @type int $remainQuota
     *          FutuOpenD剩余订阅额度
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetSubInfo\pb\QotGetSubInfo::initOnce();
        parent::__construct($data);
    }

    /**
     *订阅订阅信息
     *
     * Generated from protobuf field <code>repeated .Qot_Common.ConnSubInfo connSubInfoList = 1;</code>
     * @return RepeatedField<\Futu\Qot_Common\ConnSubInfo>
     */
    public function getConnSubInfoList()
    {
        return $this->connSubInfoList;
    }

    /**
     *订阅订阅信息
     *
     * Generated from protobuf field <code>repeated .Qot_Common.ConnSubInfo connSubInfoList = 1;</code>
     * @param \Futu\Qot_Common\ConnSubInfo[] $var
     * @return $this
     */
    public function setConnSubInfoList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\ConnSubInfo::class);
        $this->connSubInfoList = $arr;

        return $this;
    }

    /**
     *FutuOpenD已使用的订阅额度
     *
     * Generated from protobuf field <code>int32 totalUsedQuota = 2;</code>
     * @return int
     */
    public function getTotalUsedQuota()
    {
        return $this->totalUsedQuota;
    }

    /**
     *FutuOpenD已使用的订阅额度
     *
     * Generated from protobuf field <code>int32 totalUsedQuota = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalUsedQuota(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->totalUsedQuota = $var;

        return $this;
    }

    /**
     *FutuOpenD剩余订阅额度
     *
     * Generated from protobuf field <code>int32 remainQuota = 3;</code>
     * @return int
     */
    public function getRemainQuota()
    {
        return $this->remainQuota;
    }

    /**
     *FutuOpenD剩余订阅额度
     *
     * Generated from protobuf field <code>int32 remainQuota = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRemainQuota(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->remainQuota = $var;

        return $this;
    }

}

