<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetUserSecurity.proto

namespace Futu\Qot_GetUserSecurity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetUserSecurity.C2S</code>
 */
class C2S extends \Google\Protobuf\Internal\Message
{
    /**
     *分组名,有同名的返回排序首个
     *
     * Generated from protobuf field <code>string groupName = 1;</code>
     */
    protected $groupName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $groupName
     *          分组名,有同名的返回排序首个
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetUserSecurity\pb\QotGetUserSecurity::initOnce();
        parent::__construct($data);
    }

    /**
     *分组名,有同名的返回排序首个
     *
     * Generated from protobuf field <code>string groupName = 1;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->groupName;
    }

    /**
     *分组名,有同名的返回排序首个
     *
     * Generated from protobuf field <code>string groupName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->groupName = $var;

        return $this;
    }

}

