<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetUserSecurity.proto

namespace Futu\Qot_GetUserSecurity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Qot_GetUserSecurity.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *自选股分组下的股票列表
     *
     * Generated from protobuf field <code>repeated .Qot_Common.SecurityStaticInfo staticInfoList = 1;</code>
     */
    private $staticInfoList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Qot_Common\SecurityStaticInfo[] $staticInfoList
     *          自选股分组下的股票列表
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Qot_GetUserSecurity\pb\QotGetUserSecurity::initOnce();
        parent::__construct($data);
    }

    /**
     *自选股分组下的股票列表
     *
     * Generated from protobuf field <code>repeated .Qot_Common.SecurityStaticInfo staticInfoList = 1;</code>
     * @return RepeatedField<\Futu\Qot_Common\SecurityStaticInfo>
     */
    public function getStaticInfoList()
    {
        return $this->staticInfoList;
    }

    /**
     *自选股分组下的股票列表
     *
     * Generated from protobuf field <code>repeated .Qot_Common.SecurityStaticInfo staticInfoList = 1;</code>
     * @param \Futu\Qot_Common\SecurityStaticInfo[] $var
     * @return $this
     */
    public function setStaticInfoList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Qot_Common\SecurityStaticInfo::class);
        $this->staticInfoList = $arr;

        return $this;
    }

}

