<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetOrderFee.proto

namespace Futu\Trd_GetOrderFee;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_GetOrderFee.S2C</code>
 */
class S2C extends \Google\Protobuf\Internal\Message
{
    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     */
    protected $header = null;
    /**
     *订单费用列表
     *
     * Generated from protobuf field <code>repeated .Trd_Common.OrderFee orderFeeList = 2;</code>
     */
    private $orderFeeList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Futu\Trd_Common\TrdHeader $header
     *          交易公共参数头
     *     @type \Futu\Trd_Common\OrderFee[] $orderFeeList
     *          订单费用列表
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_GetOrderFee\pb\TrdGetOrderFee::initOnce();
        parent::__construct($data);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @return \Futu\Trd_Common\TrdHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     *交易公共参数头
     *
     * Generated from protobuf field <code>.Trd_Common.TrdHeader header = 1;</code>
     * @param \Futu\Trd_Common\TrdHeader $var
     * @return $this
     */
    public function setHeader(\Futu\Trd_Common\TrdHeader|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     *订单费用列表
     *
     * Generated from protobuf field <code>repeated .Trd_Common.OrderFee orderFeeList = 2;</code>
     * @return RepeatedField<\Futu\Trd_Common\OrderFee>
     */
    public function getOrderFeeList()
    {
        return $this->orderFeeList;
    }

    /**
     *订单费用列表
     *
     * Generated from protobuf field <code>repeated .Trd_Common.OrderFee orderFeeList = 2;</code>
     * @param \Futu\Trd_Common\OrderFee[] $var
     * @return $this
     */
    public function setOrderFeeList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Futu\Trd_Common\OrderFee::class);
        $this->orderFeeList = $arr;

        return $this;
    }

}

