<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetHistoryOrderList.proto

namespace Futu\Trd_GetHistoryOrderList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Trd_GetHistoryOrderList.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     *
     * Generated from protobuf field <code>int32 retType = 1;</code>
     */
    protected $retType = 0;
    /**
     * Generated from protobuf field <code>string retMsg = 2;</code>
     */
    protected $retMsg = '';
    /**
     * Generated from protobuf field <code>int32 errCode = 3;</code>
     */
    protected $errCode = 0;
    /**
     * Generated from protobuf field <code>.Trd_GetHistoryOrderList.S2C s2c = 4;</code>
     */
    protected $s2c = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $retType
     *          以下3个字段每条协议都有，注释说明在InitConnect.proto中
     *     @type string $retMsg
     *     @type int $errCode
     *     @type \Futu\Trd_GetHistoryOrderList\S2C $s2c
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Trd_GetHistoryOrderList\pb\TrdGetHistoryOrderList::initOnce();
        parent::__construct($data);
    }

    /**
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     *
     * Generated from protobuf field <code>int32 retType = 1;</code>
     * @return int
     */
    public function getRetType()
    {
        return $this->retType;
    }

    /**
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     *
     * Generated from protobuf field <code>int32 retType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRetType(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->retType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string retMsg = 2;</code>
     * @return string
     */
    public function getRetMsg()
    {
        return $this->retMsg;
    }

    /**
     * Generated from protobuf field <code>string retMsg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRetMsg(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->retMsg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 errCode = 3;</code>
     * @return int
     */
    public function getErrCode()
    {
        return $this->errCode;
    }

    /**
     * Generated from protobuf field <code>int32 errCode = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setErrCode(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->errCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Trd_GetHistoryOrderList.S2C s2c = 4;</code>
     * @return \Futu\Trd_GetHistoryOrderList\S2C|null
     */
    public function getS2C()
    {
        return $this->s2c;
    }

    public function hasS2C()
    {
        return isset($this->s2c);
    }

    public function clearS2C()
    {
        unset($this->s2c);
    }

    /**
     * Generated from protobuf field <code>.Trd_GetHistoryOrderList.S2C s2c = 4;</code>
     * @param \Futu\Trd_GetHistoryOrderList\S2C $var
     * @return $this
     */
    public function setS2C(\Futu\Trd_GetHistoryOrderList\S2C|null $var)
    {
        $this->s2c = $var;

        return $this;
    }

}

