<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Common.proto

namespace Futu\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *包的唯一标识，用于回放攻击的识别和保护
 *
 * Generated from protobuf message <code>Common.PacketID</code>
 */
class PacketID extends \Google\Protobuf\Internal\Message
{
    /**
     *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
     *
     * Generated from protobuf field <code>uint64 connID = 1;</code>
     */
    protected $connID = 0;
    /**
     *自增序列号
     *
     * Generated from protobuf field <code>uint32 serialNo = 2;</code>
     */
    protected $serialNo = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $connID
     *          当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
     *     @type int $serialNo
     *          自增序列号
     * }
     */
    public function __construct($data = NULL) {
        \Futu\Common\pb\Common::initOnce();
        parent::__construct($data);
    }

    /**
     *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
     *
     * Generated from protobuf field <code>uint64 connID = 1;</code>
     * @return int|string
     */
    public function getConnID()
    {
        return $this->connID;
    }

    /**
     *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
     *
     * Generated from protobuf field <code>uint64 connID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConnID(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->connID = $var;

        return $this;
    }

    /**
     *自增序列号
     *
     * Generated from protobuf field <code>uint32 serialNo = 2;</code>
     * @return int
     */
    public function getSerialNo()
    {
        return $this->serialNo;
    }

    /**
     *自增序列号
     *
     * Generated from protobuf field <code>uint32 serialNo = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSerialNo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->serialNo = $var;

        return $this;
    }

}

