<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Common.proto

namespace Futu\Common;

use UnexpectedValueException;

/**
 *协议格式，请求协议在请求头中指定，推送协议在Init时指定
 *
 * Protobuf type <code>Common.ProtoFmt</code>
 */
class ProtoFmt
{
    /**
     *Google Protobuf格式
     *
     * Generated from protobuf enum <code>ProtoFmt_Protobuf = 0;</code>
     */
    const ProtoFmt_Protobuf = 0;
    /**
     *Json格式
     *
     * Generated from protobuf enum <code>ProtoFmt_Json = 1;</code>
     */
    const ProtoFmt_Json = 1;

    private static $valueToName = [
        self::ProtoFmt_Protobuf => 'ProtoFmt_Protobuf',
        self::ProtoFmt_Json => 'ProtoFmt_Json',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

