<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Common.proto

namespace Futu\Common;

use UnexpectedValueException;

/**
 *返回结果
 *
 * Protobuf type <code>Common.RetType</code>
 */
class RetType
{
    /**
     *成功
     *
     * Generated from protobuf enum <code>RetType_Succeed = 0;</code>
     */
    const RetType_Succeed = 0;
    /**
     *失败
     *
     * Generated from protobuf enum <code>RetType_Failed = -1;</code>
     */
    const RetType_Failed = -1;
    /**
     *超时
     *
     * Generated from protobuf enum <code>RetType_TimeOut = -100;</code>
     */
    const RetType_TimeOut = -100;
    /**
     *连接断开
     *
     * Generated from protobuf enum <code>RetType_DisConnect = -200;</code>
     */
    const RetType_DisConnect = -200;
    /**
     *未知结果
     *
     * Generated from protobuf enum <code>RetType_Unknown = -400;</code>
     */
    const RetType_Unknown = -400;
    /**
     *包内容非法
     *
     * Generated from protobuf enum <code>RetType_Invalid = -500;</code>
     */
    const RetType_Invalid = -500;

    private static $valueToName = [
        self::RetType_Succeed => 'RetType_Succeed',
        self::RetType_Failed => 'RetType_Failed',
        self::RetType_TimeOut => 'RetType_TimeOut',
        self::RetType_DisConnect => 'RetType_DisConnect',
        self::RetType_Unknown => 'RetType_Unknown',
        self::RetType_Invalid => 'RetType_Invalid',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

