<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Common.proto

namespace Futu\Common;

use UnexpectedValueException;

/**
 *用户注册归属地
 *
 * Protobuf type <code>Common.UserAttribution</code>
 */
class UserAttribution
{
    /**
     *
     * Generated from protobuf enum <code>UserAttribution_Unknown = 0;</code>
     */
    const UserAttribution_Unknown = 0;
    /**
     *大陆
     *
     * Generated from protobuf enum <code>UserAttribution_NN = 1;</code>
     */
    const UserAttribution_NN = 1;
    /**
     *MooMoo
     *
     * Generated from protobuf enum <code>UserAttribution_MM = 2;</code>
     */
    const UserAttribution_MM = 2;
    /**
     *新加坡
     *
     * Generated from protobuf enum <code>UserAttribution_SG = 3;</code>
     */
    const UserAttribution_SG = 3;
    /**
     *澳洲
     *
     * Generated from protobuf enum <code>UserAttribution_AU = 4;</code>
     */
    const UserAttribution_AU = 4;
    /**
     *日本
     *
     * Generated from protobuf enum <code>UserAttribution_JP = 5;</code>
     */
    const UserAttribution_JP = 5;
    /**
     *香港
     *
     * Generated from protobuf enum <code>UserAttribution_HK = 6;</code>
     */
    const UserAttribution_HK = 6;

    private static $valueToName = [
        self::UserAttribution_Unknown => 'UserAttribution_Unknown',
        self::UserAttribution_NN => 'UserAttribution_NN',
        self::UserAttribution_MM => 'UserAttribution_MM',
        self::UserAttribution_SG => 'UserAttribution_SG',
        self::UserAttribution_AU => 'UserAttribution_AU',
        self::UserAttribution_JP => 'UserAttribution_JP',
        self::UserAttribution_HK => 'UserAttribution_HK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

