<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetMarginRatio.proto

namespace Futu\Trd_GetMarginRatio\pb;

class TrdGetMarginRatio
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Futu\Trd_Common\pb\TrdCommon::initOnce();
        \Futu\Qot_Common\pb\QotCommon::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAC\x06\x0A\x18Trd_GetMarginRatio.proto\x12\x12Trd_GetMarginRatio\x1A\x10Qot_Common.proto\"\xC9\x02\x0A\x0FMarginRatioInfo\x12&\x0A\x08security\x18\x01 \x01(\x0B2\x14.Qot_Common.Security\x12\x14\x0A\x0CisLongPermit\x18\x02 \x01(\x08\x12\x15\x0A\x0DisShortPermit\x18\x03 \x01(\x08\x12\x17\x0A\x0FshortPoolRemain\x18\x04 \x01(\x01\x12\x14\x0A\x0CshortFeeRate\x18\x05 \x01(\x01\x12\x16\x0A\x0EalertLongRatio\x18\x06 \x01(\x01\x12\x17\x0A\x0FalertShortRatio\x18\x07 \x01(\x01\x12\x13\x0A\x0BimLongRatio\x18\x08 \x01(\x01\x12\x14\x0A\x0CimShortRatio\x18\x09 \x01(\x01\x12\x14\x0A\x0CmcmLongRatio\x18\x0A \x01(\x01\x12\x15\x0A\x0DmcmShortRatio\x18\x0B \x01(\x01\x12\x13\x0A\x0BmmLongRatio\x18\x0C \x01(\x01\x12\x14\x0A\x0CmmShortRatio\x18\x0D \x01(\x01\"X\x0A\x03C2S\x12%\x0A\x06header\x18\x01 \x01(\x0B2\x15.Trd_Common.TrdHeader\x12*\x0A\x0CsecurityList\x18\x02 \x03(\x0B2\x14.Qot_Common.Security\"n\x0A\x03S2C\x12%\x0A\x06header\x18\x01 \x01(\x0B2\x15.Trd_Common.TrdHeader\x12@\x0A\x13marginRatioInfoList\x18\x02 \x03(\x0B2#.Trd_GetMarginRatio.MarginRatioInfo\"/\x0A\x07Request\x12\$\x0A\x03c2s\x18\x01 \x01(\x0B2\x17.Trd_GetMarginRatio.C2S\"b\x0A\x08Response\x12\x0F\x0A\x07retType\x18\x01 \x01(\x05\x12\x0E\x0A\x06retMsg\x18\x02 \x01(\x09\x12\x0F\x0A\x07errCode\x18\x03 \x01(\x05\x12\$\x0A\x03s2c\x18\x04 \x01(\x0B2\x17.Trd_GetMarginRatio.S2CB7\xCA\x02\x17Futu\\Trd_GetMarginRatio\xE2\x02\x1AFutu\\Trd_GetMarginRatio\\pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

